// Code generated by ent, DO NOT EDIT.

package merchantintegration

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the merchantintegration type in the database.
	Label = "merchant_integration"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldMerchantCode holds the string denoting the merchant_code field in the database.
	FieldMerchantCode = "merchant_code"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldRedirectHosts holds the string denoting the redirect_hosts field in the database.
	FieldRedirectHosts = "redirect_hosts"
	// EdgeEndpoints holds the string denoting the endpoints edge name in mutations.
	EdgeEndpoints = "endpoints"
	// EdgeBindings holds the string denoting the bindings edge name in mutations.
	EdgeBindings = "bindings"
	// EdgeRechargeRecords holds the string denoting the recharge_records edge name in mutations.
	EdgeRechargeRecords = "recharge_records"
	// Table holds the table name of the merchantintegration in the database.
	Table = "merchant_integrations"
	// EndpointsTable is the table that holds the endpoints relation/edge.
	EndpointsTable = "merchant_api_endpoints"
	// EndpointsInverseTable is the table name for the MerchantAPIEndpoint entity.
	// It exists in this package in order to avoid circular dependency with the "merchantapiendpoint" package.
	EndpointsInverseTable = "merchant_api_endpoints"
	// EndpointsColumn is the table column denoting the endpoints relation/edge.
	EndpointsColumn = "integration_id"
	// BindingsTable is the table that holds the bindings relation/edge.
	BindingsTable = "merchant_bindings"
	// BindingsInverseTable is the table name for the MerchantBinding entity.
	// It exists in this package in order to avoid circular dependency with the "merchantbinding" package.
	BindingsInverseTable = "merchant_bindings"
	// BindingsColumn is the table column denoting the bindings relation/edge.
	BindingsColumn = "integration_id"
	// RechargeRecordsTable is the table that holds the recharge_records relation/edge.
	RechargeRecordsTable = "merchant_recharge_records"
	// RechargeRecordsInverseTable is the table name for the MerchantRechargeRecord entity.
	// It exists in this package in order to avoid circular dependency with the "merchantrechargerecord" package.
	RechargeRecordsInverseTable = "merchant_recharge_records"
	// RechargeRecordsColumn is the table column denoting the recharge_records relation/edge.
	RechargeRecordsColumn = "integration_id"
)

// Columns holds all SQL columns for merchantintegration fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldCode,
	FieldMode,
	FieldMerchantCode,
	FieldDescription,
	FieldStatus,
	FieldEnabled,
	FieldRedirectHosts,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultMode holds the default value on creation for the "mode" field.
	DefaultMode string
	// ModeValidator is a validator for the "mode" field. It is called by the builders before save.
	ModeValidator func(string) error
	// DefaultMerchantCode holds the default value on creation for the "merchant_code" field.
	DefaultMerchantCode string
	// MerchantCodeValidator is a validator for the "merchant_code" field. It is called by the builders before save.
	MerchantCodeValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the MerchantIntegration queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByMerchantCode orders the results by the merchant_code field.
func ByMerchantCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMerchantCode, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByEndpointsCount orders the results by endpoints count.
func ByEndpointsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEndpointsStep(), opts...)
	}
}

// ByEndpoints orders the results by endpoints terms.
func ByEndpoints(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEndpointsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBindingsCount orders the results by bindings count.
func ByBindingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBindingsStep(), opts...)
	}
}

// ByBindings orders the results by bindings terms.
func ByBindings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBindingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRechargeRecordsCount orders the results by recharge_records count.
func ByRechargeRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRechargeRecordsStep(), opts...)
	}
}

// ByRechargeRecords orders the results by recharge_records terms.
func ByRechargeRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRechargeRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEndpointsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EndpointsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EndpointsTable, EndpointsColumn),
	)
}
func newBindingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BindingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BindingsTable, BindingsColumn),
	)
}
func newRechargeRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RechargeRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RechargeRecordsTable, RechargeRecordsColumn),
	)
}
