// Code generated by ent, DO NOT EDIT.

package merchantintegration

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldName, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldCode, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldMode, v))
}

// MerchantCode applies equality check predicate on the "merchant_code" field. It's identical to MerchantCodeEQ.
func MerchantCode(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldMerchantCode, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldStatus, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldContainsFold(FieldName, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldContainsFold(FieldCode, v))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldContainsFold(FieldMode, v))
}

// MerchantCodeEQ applies the EQ predicate on the "merchant_code" field.
func MerchantCodeEQ(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldMerchantCode, v))
}

// MerchantCodeNEQ applies the NEQ predicate on the "merchant_code" field.
func MerchantCodeNEQ(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNEQ(FieldMerchantCode, v))
}

// MerchantCodeIn applies the In predicate on the "merchant_code" field.
func MerchantCodeIn(vs ...string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldIn(FieldMerchantCode, vs...))
}

// MerchantCodeNotIn applies the NotIn predicate on the "merchant_code" field.
func MerchantCodeNotIn(vs ...string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNotIn(FieldMerchantCode, vs...))
}

// MerchantCodeGT applies the GT predicate on the "merchant_code" field.
func MerchantCodeGT(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGT(FieldMerchantCode, v))
}

// MerchantCodeGTE applies the GTE predicate on the "merchant_code" field.
func MerchantCodeGTE(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGTE(FieldMerchantCode, v))
}

// MerchantCodeLT applies the LT predicate on the "merchant_code" field.
func MerchantCodeLT(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLT(FieldMerchantCode, v))
}

// MerchantCodeLTE applies the LTE predicate on the "merchant_code" field.
func MerchantCodeLTE(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLTE(FieldMerchantCode, v))
}

// MerchantCodeContains applies the Contains predicate on the "merchant_code" field.
func MerchantCodeContains(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldContains(FieldMerchantCode, v))
}

// MerchantCodeHasPrefix applies the HasPrefix predicate on the "merchant_code" field.
func MerchantCodeHasPrefix(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldHasPrefix(FieldMerchantCode, v))
}

// MerchantCodeHasSuffix applies the HasSuffix predicate on the "merchant_code" field.
func MerchantCodeHasSuffix(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldHasSuffix(FieldMerchantCode, v))
}

// MerchantCodeEqualFold applies the EqualFold predicate on the "merchant_code" field.
func MerchantCodeEqualFold(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEqualFold(FieldMerchantCode, v))
}

// MerchantCodeContainsFold applies the ContainsFold predicate on the "merchant_code" field.
func MerchantCodeContainsFold(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldContainsFold(FieldMerchantCode, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldContainsFold(FieldStatus, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.FieldNEQ(FieldEnabled, v))
}

// HasEndpoints applies the HasEdge predicate on the "endpoints" edge.
func HasEndpoints() predicate.MerchantIntegration {
	return predicate.MerchantIntegration(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EndpointsTable, EndpointsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEndpointsWith applies the HasEdge predicate on the "endpoints" edge with a given conditions (other predicates).
func HasEndpointsWith(preds ...predicate.MerchantAPIEndpoint) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(func(s *sql.Selector) {
		step := newEndpointsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBindings applies the HasEdge predicate on the "bindings" edge.
func HasBindings() predicate.MerchantIntegration {
	return predicate.MerchantIntegration(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BindingsTable, BindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBindingsWith applies the HasEdge predicate on the "bindings" edge with a given conditions (other predicates).
func HasBindingsWith(preds ...predicate.MerchantBinding) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(func(s *sql.Selector) {
		step := newBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRechargeRecords applies the HasEdge predicate on the "recharge_records" edge.
func HasRechargeRecords() predicate.MerchantIntegration {
	return predicate.MerchantIntegration(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RechargeRecordsTable, RechargeRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRechargeRecordsWith applies the HasEdge predicate on the "recharge_records" edge with a given conditions (other predicates).
func HasRechargeRecordsWith(preds ...predicate.MerchantRechargeRecord) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(func(s *sql.Selector) {
		step := newRechargeRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MerchantIntegration) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MerchantIntegration) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MerchantIntegration) predicate.MerchantIntegration {
	return predicate.MerchantIntegration(sql.NotPredicates(p))
}
