// Code generated by ent, DO NOT EDIT.

package merchantbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the merchantbinding type in the database.
	Label = "merchant_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldIntegrationID holds the string denoting the integration_id field in the database.
	FieldIntegrationID = "integration_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldExternalUserID holds the string denoting the external_user_id field in the database.
	FieldExternalUserID = "external_user_id"
	// FieldExternalAccount holds the string denoting the external_account field in the database.
	FieldExternalAccount = "external_account"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLastLoginAt holds the string denoting the last_login_at field in the database.
	FieldLastLoginAt = "last_login_at"
	// FieldLastSyncAt holds the string denoting the last_sync_at field in the database.
	FieldLastSyncAt = "last_sync_at"
	// FieldLastRechargeSyncAt holds the string denoting the last_recharge_sync_at field in the database.
	FieldLastRechargeSyncAt = "last_recharge_sync_at"
	// EdgeIntegration holds the string denoting the integration edge name in mutations.
	EdgeIntegration = "integration"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the merchantbinding in the database.
	Table = "merchant_bindings"
	// IntegrationTable is the table that holds the integration relation/edge.
	IntegrationTable = "merchant_bindings"
	// IntegrationInverseTable is the table name for the MerchantIntegration entity.
	// It exists in this package in order to avoid circular dependency with the "merchantintegration" package.
	IntegrationInverseTable = "merchant_integrations"
	// IntegrationColumn is the table column denoting the integration relation/edge.
	IntegrationColumn = "integration_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "merchant_bindings"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for merchantbinding fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldIntegrationID,
	FieldUserID,
	FieldExternalUserID,
	FieldExternalAccount,
	FieldStatus,
	FieldLastLoginAt,
	FieldLastSyncAt,
	FieldLastRechargeSyncAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ExternalUserIDValidator is a validator for the "external_user_id" field. It is called by the builders before save.
	ExternalUserIDValidator func(string) error
	// DefaultExternalAccount holds the default value on creation for the "external_account" field.
	DefaultExternalAccount string
	// ExternalAccountValidator is a validator for the "external_account" field. It is called by the builders before save.
	ExternalAccountValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the MerchantBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByIntegrationID orders the results by the integration_id field.
func ByIntegrationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntegrationID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByExternalUserID orders the results by the external_user_id field.
func ByExternalUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalUserID, opts...).ToFunc()
}

// ByExternalAccount orders the results by the external_account field.
func ByExternalAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalAccount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastLoginAt orders the results by the last_login_at field.
func ByLastLoginAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLoginAt, opts...).ToFunc()
}

// ByLastSyncAt orders the results by the last_sync_at field.
func ByLastSyncAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncAt, opts...).ToFunc()
}

// ByLastRechargeSyncAt orders the results by the last_recharge_sync_at field.
func ByLastRechargeSyncAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRechargeSyncAt, opts...).ToFunc()
}

// ByIntegrationField orders the results by integration field.
func ByIntegrationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIntegrationStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newIntegrationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IntegrationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, IntegrationTable, IntegrationColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
