// Code generated by ent, DO NOT EDIT.

package merchantbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// IntegrationID applies equality check predicate on the "integration_id" field. It's identical to IntegrationIDEQ.
func IntegrationID(v int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldIntegrationID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldUserID, v))
}

// ExternalUserID applies equality check predicate on the "external_user_id" field. It's identical to ExternalUserIDEQ.
func ExternalUserID(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldExternalUserID, v))
}

// ExternalAccount applies equality check predicate on the "external_account" field. It's identical to ExternalAccountEQ.
func ExternalAccount(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldExternalAccount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldStatus, v))
}

// LastLoginAt applies equality check predicate on the "last_login_at" field. It's identical to LastLoginAtEQ.
func LastLoginAt(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastSyncAt applies equality check predicate on the "last_sync_at" field. It's identical to LastSyncAtEQ.
func LastSyncAt(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastRechargeSyncAt applies equality check predicate on the "last_recharge_sync_at" field. It's identical to LastRechargeSyncAtEQ.
func LastRechargeSyncAt(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldLastRechargeSyncAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// IntegrationIDEQ applies the EQ predicate on the "integration_id" field.
func IntegrationIDEQ(v int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldIntegrationID, v))
}

// IntegrationIDNEQ applies the NEQ predicate on the "integration_id" field.
func IntegrationIDNEQ(v int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNEQ(FieldIntegrationID, v))
}

// IntegrationIDIn applies the In predicate on the "integration_id" field.
func IntegrationIDIn(vs ...int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIn(FieldIntegrationID, vs...))
}

// IntegrationIDNotIn applies the NotIn predicate on the "integration_id" field.
func IntegrationIDNotIn(vs ...int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotIn(FieldIntegrationID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotIn(FieldUserID, vs...))
}

// ExternalUserIDEQ applies the EQ predicate on the "external_user_id" field.
func ExternalUserIDEQ(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldExternalUserID, v))
}

// ExternalUserIDNEQ applies the NEQ predicate on the "external_user_id" field.
func ExternalUserIDNEQ(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNEQ(FieldExternalUserID, v))
}

// ExternalUserIDIn applies the In predicate on the "external_user_id" field.
func ExternalUserIDIn(vs ...string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIn(FieldExternalUserID, vs...))
}

// ExternalUserIDNotIn applies the NotIn predicate on the "external_user_id" field.
func ExternalUserIDNotIn(vs ...string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotIn(FieldExternalUserID, vs...))
}

// ExternalUserIDGT applies the GT predicate on the "external_user_id" field.
func ExternalUserIDGT(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGT(FieldExternalUserID, v))
}

// ExternalUserIDGTE applies the GTE predicate on the "external_user_id" field.
func ExternalUserIDGTE(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGTE(FieldExternalUserID, v))
}

// ExternalUserIDLT applies the LT predicate on the "external_user_id" field.
func ExternalUserIDLT(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLT(FieldExternalUserID, v))
}

// ExternalUserIDLTE applies the LTE predicate on the "external_user_id" field.
func ExternalUserIDLTE(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLTE(FieldExternalUserID, v))
}

// ExternalUserIDContains applies the Contains predicate on the "external_user_id" field.
func ExternalUserIDContains(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldContains(FieldExternalUserID, v))
}

// ExternalUserIDHasPrefix applies the HasPrefix predicate on the "external_user_id" field.
func ExternalUserIDHasPrefix(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldHasPrefix(FieldExternalUserID, v))
}

// ExternalUserIDHasSuffix applies the HasSuffix predicate on the "external_user_id" field.
func ExternalUserIDHasSuffix(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldHasSuffix(FieldExternalUserID, v))
}

// ExternalUserIDEqualFold applies the EqualFold predicate on the "external_user_id" field.
func ExternalUserIDEqualFold(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEqualFold(FieldExternalUserID, v))
}

// ExternalUserIDContainsFold applies the ContainsFold predicate on the "external_user_id" field.
func ExternalUserIDContainsFold(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldContainsFold(FieldExternalUserID, v))
}

// ExternalAccountEQ applies the EQ predicate on the "external_account" field.
func ExternalAccountEQ(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldExternalAccount, v))
}

// ExternalAccountNEQ applies the NEQ predicate on the "external_account" field.
func ExternalAccountNEQ(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNEQ(FieldExternalAccount, v))
}

// ExternalAccountIn applies the In predicate on the "external_account" field.
func ExternalAccountIn(vs ...string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIn(FieldExternalAccount, vs...))
}

// ExternalAccountNotIn applies the NotIn predicate on the "external_account" field.
func ExternalAccountNotIn(vs ...string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotIn(FieldExternalAccount, vs...))
}

// ExternalAccountGT applies the GT predicate on the "external_account" field.
func ExternalAccountGT(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGT(FieldExternalAccount, v))
}

// ExternalAccountGTE applies the GTE predicate on the "external_account" field.
func ExternalAccountGTE(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGTE(FieldExternalAccount, v))
}

// ExternalAccountLT applies the LT predicate on the "external_account" field.
func ExternalAccountLT(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLT(FieldExternalAccount, v))
}

// ExternalAccountLTE applies the LTE predicate on the "external_account" field.
func ExternalAccountLTE(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLTE(FieldExternalAccount, v))
}

// ExternalAccountContains applies the Contains predicate on the "external_account" field.
func ExternalAccountContains(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldContains(FieldExternalAccount, v))
}

// ExternalAccountHasPrefix applies the HasPrefix predicate on the "external_account" field.
func ExternalAccountHasPrefix(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldHasPrefix(FieldExternalAccount, v))
}

// ExternalAccountHasSuffix applies the HasSuffix predicate on the "external_account" field.
func ExternalAccountHasSuffix(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldHasSuffix(FieldExternalAccount, v))
}

// ExternalAccountEqualFold applies the EqualFold predicate on the "external_account" field.
func ExternalAccountEqualFold(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEqualFold(FieldExternalAccount, v))
}

// ExternalAccountContainsFold applies the ContainsFold predicate on the "external_account" field.
func ExternalAccountContainsFold(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldContainsFold(FieldExternalAccount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldContainsFold(FieldStatus, v))
}

// LastLoginAtEQ applies the EQ predicate on the "last_login_at" field.
func LastLoginAtEQ(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastLoginAtNEQ applies the NEQ predicate on the "last_login_at" field.
func LastLoginAtNEQ(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNEQ(FieldLastLoginAt, v))
}

// LastLoginAtIn applies the In predicate on the "last_login_at" field.
func LastLoginAtIn(vs ...time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIn(FieldLastLoginAt, vs...))
}

// LastLoginAtNotIn applies the NotIn predicate on the "last_login_at" field.
func LastLoginAtNotIn(vs ...time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotIn(FieldLastLoginAt, vs...))
}

// LastLoginAtGT applies the GT predicate on the "last_login_at" field.
func LastLoginAtGT(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGT(FieldLastLoginAt, v))
}

// LastLoginAtGTE applies the GTE predicate on the "last_login_at" field.
func LastLoginAtGTE(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGTE(FieldLastLoginAt, v))
}

// LastLoginAtLT applies the LT predicate on the "last_login_at" field.
func LastLoginAtLT(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLT(FieldLastLoginAt, v))
}

// LastLoginAtLTE applies the LTE predicate on the "last_login_at" field.
func LastLoginAtLTE(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLTE(FieldLastLoginAt, v))
}

// LastLoginAtIsNil applies the IsNil predicate on the "last_login_at" field.
func LastLoginAtIsNil() predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIsNull(FieldLastLoginAt))
}

// LastLoginAtNotNil applies the NotNil predicate on the "last_login_at" field.
func LastLoginAtNotNil() predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotNull(FieldLastLoginAt))
}

// LastSyncAtEQ applies the EQ predicate on the "last_sync_at" field.
func LastSyncAtEQ(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncAtNEQ applies the NEQ predicate on the "last_sync_at" field.
func LastSyncAtNEQ(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNEQ(FieldLastSyncAt, v))
}

// LastSyncAtIn applies the In predicate on the "last_sync_at" field.
func LastSyncAtIn(vs ...time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIn(FieldLastSyncAt, vs...))
}

// LastSyncAtNotIn applies the NotIn predicate on the "last_sync_at" field.
func LastSyncAtNotIn(vs ...time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotIn(FieldLastSyncAt, vs...))
}

// LastSyncAtGT applies the GT predicate on the "last_sync_at" field.
func LastSyncAtGT(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGT(FieldLastSyncAt, v))
}

// LastSyncAtGTE applies the GTE predicate on the "last_sync_at" field.
func LastSyncAtGTE(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGTE(FieldLastSyncAt, v))
}

// LastSyncAtLT applies the LT predicate on the "last_sync_at" field.
func LastSyncAtLT(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLT(FieldLastSyncAt, v))
}

// LastSyncAtLTE applies the LTE predicate on the "last_sync_at" field.
func LastSyncAtLTE(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLTE(FieldLastSyncAt, v))
}

// LastSyncAtIsNil applies the IsNil predicate on the "last_sync_at" field.
func LastSyncAtIsNil() predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIsNull(FieldLastSyncAt))
}

// LastSyncAtNotNil applies the NotNil predicate on the "last_sync_at" field.
func LastSyncAtNotNil() predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotNull(FieldLastSyncAt))
}

// LastRechargeSyncAtEQ applies the EQ predicate on the "last_recharge_sync_at" field.
func LastRechargeSyncAtEQ(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldEQ(FieldLastRechargeSyncAt, v))
}

// LastRechargeSyncAtNEQ applies the NEQ predicate on the "last_recharge_sync_at" field.
func LastRechargeSyncAtNEQ(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNEQ(FieldLastRechargeSyncAt, v))
}

// LastRechargeSyncAtIn applies the In predicate on the "last_recharge_sync_at" field.
func LastRechargeSyncAtIn(vs ...time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIn(FieldLastRechargeSyncAt, vs...))
}

// LastRechargeSyncAtNotIn applies the NotIn predicate on the "last_recharge_sync_at" field.
func LastRechargeSyncAtNotIn(vs ...time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotIn(FieldLastRechargeSyncAt, vs...))
}

// LastRechargeSyncAtGT applies the GT predicate on the "last_recharge_sync_at" field.
func LastRechargeSyncAtGT(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGT(FieldLastRechargeSyncAt, v))
}

// LastRechargeSyncAtGTE applies the GTE predicate on the "last_recharge_sync_at" field.
func LastRechargeSyncAtGTE(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldGTE(FieldLastRechargeSyncAt, v))
}

// LastRechargeSyncAtLT applies the LT predicate on the "last_recharge_sync_at" field.
func LastRechargeSyncAtLT(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLT(FieldLastRechargeSyncAt, v))
}

// LastRechargeSyncAtLTE applies the LTE predicate on the "last_recharge_sync_at" field.
func LastRechargeSyncAtLTE(v time.Time) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldLTE(FieldLastRechargeSyncAt, v))
}

// LastRechargeSyncAtIsNil applies the IsNil predicate on the "last_recharge_sync_at" field.
func LastRechargeSyncAtIsNil() predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldIsNull(FieldLastRechargeSyncAt))
}

// LastRechargeSyncAtNotNil applies the NotNil predicate on the "last_recharge_sync_at" field.
func LastRechargeSyncAtNotNil() predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.FieldNotNull(FieldLastRechargeSyncAt))
}

// HasIntegration applies the HasEdge predicate on the "integration" edge.
func HasIntegration() predicate.MerchantBinding {
	return predicate.MerchantBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IntegrationTable, IntegrationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIntegrationWith applies the HasEdge predicate on the "integration" edge with a given conditions (other predicates).
func HasIntegrationWith(preds ...predicate.MerchantIntegration) predicate.MerchantBinding {
	return predicate.MerchantBinding(func(s *sql.Selector) {
		step := newIntegrationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.MerchantBinding {
	return predicate.MerchantBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.MerchantBinding {
	return predicate.MerchantBinding(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MerchantBinding) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MerchantBinding) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MerchantBinding) predicate.MerchantBinding {
	return predicate.MerchantBinding(sql.NotPredicates(p))
}
