// Code generated by ent, DO NOT EDIT.

package rewardcampaignjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the rewardcampaignjob type in the database.
	Label = "reward_campaign_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCampaignID holds the string denoting the campaign_id field in the database.
	FieldCampaignID = "campaign_id"
	// FieldCampaignVersionID holds the string denoting the campaign_version_id field in the database.
	FieldCampaignVersionID = "campaign_version_id"
	// FieldJobType holds the string denoting the job_type field in the database.
	FieldJobType = "job_type"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCursorUserID holds the string denoting the cursor_user_id field in the database.
	FieldCursorUserID = "cursor_user_id"
	// FieldMaxUserID holds the string denoting the max_user_id field in the database.
	FieldMaxUserID = "max_user_id"
	// FieldLeaseOwner holds the string denoting the lease_owner field in the database.
	FieldLeaseOwner = "lease_owner"
	// FieldLeaseExpiresAt holds the string denoting the lease_expires_at field in the database.
	FieldLeaseExpiresAt = "lease_expires_at"
	// FieldScheduledAt holds the string denoting the scheduled_at field in the database.
	FieldScheduledAt = "scheduled_at"
	// FieldNextAttemptAt holds the string denoting the next_attempt_at field in the database.
	FieldNextAttemptAt = "next_attempt_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldAttemptCount holds the string denoting the attempt_count field in the database.
	FieldAttemptCount = "attempt_count"
	// FieldMaxAttempts holds the string denoting the max_attempts field in the database.
	FieldMaxAttempts = "max_attempts"
	// FieldTotalUsers holds the string denoting the total_users field in the database.
	FieldTotalUsers = "total_users"
	// FieldScannedUsers holds the string denoting the scanned_users field in the database.
	FieldScannedUsers = "scanned_users"
	// FieldMatchedUsers holds the string denoting the matched_users field in the database.
	FieldMatchedUsers = "matched_users"
	// FieldGrantedUsers holds the string denoting the granted_users field in the database.
	FieldGrantedUsers = "granted_users"
	// FieldSkippedUsers holds the string denoting the skipped_users field in the database.
	FieldSkippedUsers = "skipped_users"
	// FieldFailedUsers holds the string denoting the failed_users field in the database.
	FieldFailedUsers = "failed_users"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// EdgeCampaign holds the string denoting the campaign edge name in mutations.
	EdgeCampaign = "campaign"
	// EdgeCampaignVersion holds the string denoting the campaign_version edge name in mutations.
	EdgeCampaignVersion = "campaign_version"
	// EdgeGrants holds the string denoting the grants edge name in mutations.
	EdgeGrants = "grants"
	// Table holds the table name of the rewardcampaignjob in the database.
	Table = "reward_campaign_jobs"
	// CampaignTable is the table that holds the campaign relation/edge.
	CampaignTable = "reward_campaign_jobs"
	// CampaignInverseTable is the table name for the RewardCampaign entity.
	// It exists in this package in order to avoid circular dependency with the "rewardcampaign" package.
	CampaignInverseTable = "reward_campaigns"
	// CampaignColumn is the table column denoting the campaign relation/edge.
	CampaignColumn = "campaign_id"
	// CampaignVersionTable is the table that holds the campaign_version relation/edge.
	CampaignVersionTable = "reward_campaign_jobs"
	// CampaignVersionInverseTable is the table name for the RewardCampaignVersion entity.
	// It exists in this package in order to avoid circular dependency with the "rewardcampaignversion" package.
	CampaignVersionInverseTable = "reward_campaign_versions"
	// CampaignVersionColumn is the table column denoting the campaign_version relation/edge.
	CampaignVersionColumn = "campaign_version_id"
	// GrantsTable is the table that holds the grants relation/edge.
	GrantsTable = "user_reward_grants"
	// GrantsInverseTable is the table name for the UserRewardGrant entity.
	// It exists in this package in order to avoid circular dependency with the "userrewardgrant" package.
	GrantsInverseTable = "user_reward_grants"
	// GrantsColumn is the table column denoting the grants relation/edge.
	GrantsColumn = "job_id"
)

// Columns holds all SQL columns for rewardcampaignjob fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCampaignID,
	FieldCampaignVersionID,
	FieldJobType,
	FieldIdempotencyKey,
	FieldStatus,
	FieldCursorUserID,
	FieldMaxUserID,
	FieldLeaseOwner,
	FieldLeaseExpiresAt,
	FieldScheduledAt,
	FieldNextAttemptAt,
	FieldStartedAt,
	FieldFinishedAt,
	FieldAttemptCount,
	FieldMaxAttempts,
	FieldTotalUsers,
	FieldScannedUsers,
	FieldMatchedUsers,
	FieldGrantedUsers,
	FieldSkippedUsers,
	FieldFailedUsers,
	FieldLastError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultJobType holds the default value on creation for the "job_type" field.
	DefaultJobType string
	// JobTypeValidator is a validator for the "job_type" field. It is called by the builders before save.
	JobTypeValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCursorUserID holds the default value on creation for the "cursor_user_id" field.
	DefaultCursorUserID int64
	// CursorUserIDValidator is a validator for the "cursor_user_id" field. It is called by the builders before save.
	CursorUserIDValidator func(int64) error
	// DefaultMaxUserID holds the default value on creation for the "max_user_id" field.
	DefaultMaxUserID int64
	// MaxUserIDValidator is a validator for the "max_user_id" field. It is called by the builders before save.
	MaxUserIDValidator func(int64) error
	// DefaultLeaseOwner holds the default value on creation for the "lease_owner" field.
	DefaultLeaseOwner string
	// LeaseOwnerValidator is a validator for the "lease_owner" field. It is called by the builders before save.
	LeaseOwnerValidator func(string) error
	// DefaultAttemptCount holds the default value on creation for the "attempt_count" field.
	DefaultAttemptCount int
	// AttemptCountValidator is a validator for the "attempt_count" field. It is called by the builders before save.
	AttemptCountValidator func(int) error
	// DefaultMaxAttempts holds the default value on creation for the "max_attempts" field.
	DefaultMaxAttempts int
	// MaxAttemptsValidator is a validator for the "max_attempts" field. It is called by the builders before save.
	MaxAttemptsValidator func(int) error
	// DefaultTotalUsers holds the default value on creation for the "total_users" field.
	DefaultTotalUsers int64
	// TotalUsersValidator is a validator for the "total_users" field. It is called by the builders before save.
	TotalUsersValidator func(int64) error
	// DefaultScannedUsers holds the default value on creation for the "scanned_users" field.
	DefaultScannedUsers int64
	// ScannedUsersValidator is a validator for the "scanned_users" field. It is called by the builders before save.
	ScannedUsersValidator func(int64) error
	// DefaultMatchedUsers holds the default value on creation for the "matched_users" field.
	DefaultMatchedUsers int64
	// MatchedUsersValidator is a validator for the "matched_users" field. It is called by the builders before save.
	MatchedUsersValidator func(int64) error
	// DefaultGrantedUsers holds the default value on creation for the "granted_users" field.
	DefaultGrantedUsers int64
	// GrantedUsersValidator is a validator for the "granted_users" field. It is called by the builders before save.
	GrantedUsersValidator func(int64) error
	// DefaultSkippedUsers holds the default value on creation for the "skipped_users" field.
	DefaultSkippedUsers int64
	// SkippedUsersValidator is a validator for the "skipped_users" field. It is called by the builders before save.
	SkippedUsersValidator func(int64) error
	// DefaultFailedUsers holds the default value on creation for the "failed_users" field.
	DefaultFailedUsers int64
	// FailedUsersValidator is a validator for the "failed_users" field. It is called by the builders before save.
	FailedUsersValidator func(int64) error
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
)

// OrderOption defines the ordering options for the RewardCampaignJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCampaignID orders the results by the campaign_id field.
func ByCampaignID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCampaignID, opts...).ToFunc()
}

// ByCampaignVersionID orders the results by the campaign_version_id field.
func ByCampaignVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCampaignVersionID, opts...).ToFunc()
}

// ByJobType orders the results by the job_type field.
func ByJobType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobType, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCursorUserID orders the results by the cursor_user_id field.
func ByCursorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCursorUserID, opts...).ToFunc()
}

// ByMaxUserID orders the results by the max_user_id field.
func ByMaxUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxUserID, opts...).ToFunc()
}

// ByLeaseOwner orders the results by the lease_owner field.
func ByLeaseOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseOwner, opts...).ToFunc()
}

// ByLeaseExpiresAt orders the results by the lease_expires_at field.
func ByLeaseExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseExpiresAt, opts...).ToFunc()
}

// ByScheduledAt orders the results by the scheduled_at field.
func ByScheduledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScheduledAt, opts...).ToFunc()
}

// ByNextAttemptAt orders the results by the next_attempt_at field.
func ByNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextAttemptAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attempt_count field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByMaxAttempts orders the results by the max_attempts field.
func ByMaxAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxAttempts, opts...).ToFunc()
}

// ByTotalUsers orders the results by the total_users field.
func ByTotalUsers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalUsers, opts...).ToFunc()
}

// ByScannedUsers orders the results by the scanned_users field.
func ByScannedUsers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScannedUsers, opts...).ToFunc()
}

// ByMatchedUsers orders the results by the matched_users field.
func ByMatchedUsers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchedUsers, opts...).ToFunc()
}

// ByGrantedUsers orders the results by the granted_users field.
func ByGrantedUsers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantedUsers, opts...).ToFunc()
}

// BySkippedUsers orders the results by the skipped_users field.
func BySkippedUsers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkippedUsers, opts...).ToFunc()
}

// ByFailedUsers orders the results by the failed_users field.
func ByFailedUsers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedUsers, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCampaignField orders the results by campaign field.
func ByCampaignField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCampaignStep(), sql.OrderByField(field, opts...))
	}
}

// ByCampaignVersionField orders the results by campaign_version field.
func ByCampaignVersionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCampaignVersionStep(), sql.OrderByField(field, opts...))
	}
}

// ByGrantsCount orders the results by grants count.
func ByGrantsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGrantsStep(), opts...)
	}
}

// ByGrants orders the results by grants terms.
func ByGrants(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGrantsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCampaignStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CampaignInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CampaignTable, CampaignColumn),
	)
}
func newCampaignVersionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CampaignVersionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CampaignVersionTable, CampaignVersionColumn),
	)
}
func newGrantsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GrantsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GrantsTable, GrantsColumn),
	)
}
