// Code generated by ent, DO NOT EDIT.

package rewardcampaignjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// CampaignID applies equality check predicate on the "campaign_id" field. It's identical to CampaignIDEQ.
func CampaignID(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldCampaignID, v))
}

// CampaignVersionID applies equality check predicate on the "campaign_version_id" field. It's identical to CampaignVersionIDEQ.
func CampaignVersionID(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldCampaignVersionID, v))
}

// JobType applies equality check predicate on the "job_type" field. It's identical to JobTypeEQ.
func JobType(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldJobType, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldIdempotencyKey, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldStatus, v))
}

// CursorUserID applies equality check predicate on the "cursor_user_id" field. It's identical to CursorUserIDEQ.
func CursorUserID(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldCursorUserID, v))
}

// MaxUserID applies equality check predicate on the "max_user_id" field. It's identical to MaxUserIDEQ.
func MaxUserID(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldMaxUserID, v))
}

// LeaseOwner applies equality check predicate on the "lease_owner" field. It's identical to LeaseOwnerEQ.
func LeaseOwner(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseExpiresAt applies equality check predicate on the "lease_expires_at" field. It's identical to LeaseExpiresAtEQ.
func LeaseExpiresAt(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldLeaseExpiresAt, v))
}

// ScheduledAt applies equality check predicate on the "scheduled_at" field. It's identical to ScheduledAtEQ.
func ScheduledAt(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldScheduledAt, v))
}

// NextAttemptAt applies equality check predicate on the "next_attempt_at" field. It's identical to NextAttemptAtEQ.
func NextAttemptAt(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldNextAttemptAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldFinishedAt, v))
}

// AttemptCount applies equality check predicate on the "attempt_count" field. It's identical to AttemptCountEQ.
func AttemptCount(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldAttemptCount, v))
}

// MaxAttempts applies equality check predicate on the "max_attempts" field. It's identical to MaxAttemptsEQ.
func MaxAttempts(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldMaxAttempts, v))
}

// TotalUsers applies equality check predicate on the "total_users" field. It's identical to TotalUsersEQ.
func TotalUsers(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldTotalUsers, v))
}

// ScannedUsers applies equality check predicate on the "scanned_users" field. It's identical to ScannedUsersEQ.
func ScannedUsers(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldScannedUsers, v))
}

// MatchedUsers applies equality check predicate on the "matched_users" field. It's identical to MatchedUsersEQ.
func MatchedUsers(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldMatchedUsers, v))
}

// GrantedUsers applies equality check predicate on the "granted_users" field. It's identical to GrantedUsersEQ.
func GrantedUsers(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldGrantedUsers, v))
}

// SkippedUsers applies equality check predicate on the "skipped_users" field. It's identical to SkippedUsersEQ.
func SkippedUsers(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldSkippedUsers, v))
}

// FailedUsers applies equality check predicate on the "failed_users" field. It's identical to FailedUsersEQ.
func FailedUsers(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldFailedUsers, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// CampaignIDEQ applies the EQ predicate on the "campaign_id" field.
func CampaignIDEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldCampaignID, v))
}

// CampaignIDNEQ applies the NEQ predicate on the "campaign_id" field.
func CampaignIDNEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldCampaignID, v))
}

// CampaignIDIn applies the In predicate on the "campaign_id" field.
func CampaignIDIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldCampaignID, vs...))
}

// CampaignIDNotIn applies the NotIn predicate on the "campaign_id" field.
func CampaignIDNotIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldCampaignID, vs...))
}

// CampaignVersionIDEQ applies the EQ predicate on the "campaign_version_id" field.
func CampaignVersionIDEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldCampaignVersionID, v))
}

// CampaignVersionIDNEQ applies the NEQ predicate on the "campaign_version_id" field.
func CampaignVersionIDNEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldCampaignVersionID, v))
}

// CampaignVersionIDIn applies the In predicate on the "campaign_version_id" field.
func CampaignVersionIDIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldCampaignVersionID, vs...))
}

// CampaignVersionIDNotIn applies the NotIn predicate on the "campaign_version_id" field.
func CampaignVersionIDNotIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldCampaignVersionID, vs...))
}

// JobTypeEQ applies the EQ predicate on the "job_type" field.
func JobTypeEQ(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldJobType, v))
}

// JobTypeNEQ applies the NEQ predicate on the "job_type" field.
func JobTypeNEQ(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldJobType, v))
}

// JobTypeIn applies the In predicate on the "job_type" field.
func JobTypeIn(vs ...string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldJobType, vs...))
}

// JobTypeNotIn applies the NotIn predicate on the "job_type" field.
func JobTypeNotIn(vs ...string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldJobType, vs...))
}

// JobTypeGT applies the GT predicate on the "job_type" field.
func JobTypeGT(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldJobType, v))
}

// JobTypeGTE applies the GTE predicate on the "job_type" field.
func JobTypeGTE(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldJobType, v))
}

// JobTypeLT applies the LT predicate on the "job_type" field.
func JobTypeLT(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldJobType, v))
}

// JobTypeLTE applies the LTE predicate on the "job_type" field.
func JobTypeLTE(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldJobType, v))
}

// JobTypeContains applies the Contains predicate on the "job_type" field.
func JobTypeContains(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldContains(FieldJobType, v))
}

// JobTypeHasPrefix applies the HasPrefix predicate on the "job_type" field.
func JobTypeHasPrefix(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldHasPrefix(FieldJobType, v))
}

// JobTypeHasSuffix applies the HasSuffix predicate on the "job_type" field.
func JobTypeHasSuffix(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldHasSuffix(FieldJobType, v))
}

// JobTypeEqualFold applies the EqualFold predicate on the "job_type" field.
func JobTypeEqualFold(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEqualFold(FieldJobType, v))
}

// JobTypeContainsFold applies the ContainsFold predicate on the "job_type" field.
func JobTypeContainsFold(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldContainsFold(FieldJobType, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldContainsFold(FieldStatus, v))
}

// CursorUserIDEQ applies the EQ predicate on the "cursor_user_id" field.
func CursorUserIDEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldCursorUserID, v))
}

// CursorUserIDNEQ applies the NEQ predicate on the "cursor_user_id" field.
func CursorUserIDNEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldCursorUserID, v))
}

// CursorUserIDIn applies the In predicate on the "cursor_user_id" field.
func CursorUserIDIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldCursorUserID, vs...))
}

// CursorUserIDNotIn applies the NotIn predicate on the "cursor_user_id" field.
func CursorUserIDNotIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldCursorUserID, vs...))
}

// CursorUserIDGT applies the GT predicate on the "cursor_user_id" field.
func CursorUserIDGT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldCursorUserID, v))
}

// CursorUserIDGTE applies the GTE predicate on the "cursor_user_id" field.
func CursorUserIDGTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldCursorUserID, v))
}

// CursorUserIDLT applies the LT predicate on the "cursor_user_id" field.
func CursorUserIDLT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldCursorUserID, v))
}

// CursorUserIDLTE applies the LTE predicate on the "cursor_user_id" field.
func CursorUserIDLTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldCursorUserID, v))
}

// MaxUserIDEQ applies the EQ predicate on the "max_user_id" field.
func MaxUserIDEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldMaxUserID, v))
}

// MaxUserIDNEQ applies the NEQ predicate on the "max_user_id" field.
func MaxUserIDNEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldMaxUserID, v))
}

// MaxUserIDIn applies the In predicate on the "max_user_id" field.
func MaxUserIDIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldMaxUserID, vs...))
}

// MaxUserIDNotIn applies the NotIn predicate on the "max_user_id" field.
func MaxUserIDNotIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldMaxUserID, vs...))
}

// MaxUserIDGT applies the GT predicate on the "max_user_id" field.
func MaxUserIDGT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldMaxUserID, v))
}

// MaxUserIDGTE applies the GTE predicate on the "max_user_id" field.
func MaxUserIDGTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldMaxUserID, v))
}

// MaxUserIDLT applies the LT predicate on the "max_user_id" field.
func MaxUserIDLT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldMaxUserID, v))
}

// MaxUserIDLTE applies the LTE predicate on the "max_user_id" field.
func MaxUserIDLTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldMaxUserID, v))
}

// LeaseOwnerEQ applies the EQ predicate on the "lease_owner" field.
func LeaseOwnerEQ(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseOwnerNEQ applies the NEQ predicate on the "lease_owner" field.
func LeaseOwnerNEQ(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldLeaseOwner, v))
}

// LeaseOwnerIn applies the In predicate on the "lease_owner" field.
func LeaseOwnerIn(vs ...string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerNotIn applies the NotIn predicate on the "lease_owner" field.
func LeaseOwnerNotIn(vs ...string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerGT applies the GT predicate on the "lease_owner" field.
func LeaseOwnerGT(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldLeaseOwner, v))
}

// LeaseOwnerGTE applies the GTE predicate on the "lease_owner" field.
func LeaseOwnerGTE(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldLeaseOwner, v))
}

// LeaseOwnerLT applies the LT predicate on the "lease_owner" field.
func LeaseOwnerLT(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldLeaseOwner, v))
}

// LeaseOwnerLTE applies the LTE predicate on the "lease_owner" field.
func LeaseOwnerLTE(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldLeaseOwner, v))
}

// LeaseOwnerContains applies the Contains predicate on the "lease_owner" field.
func LeaseOwnerContains(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldContains(FieldLeaseOwner, v))
}

// LeaseOwnerHasPrefix applies the HasPrefix predicate on the "lease_owner" field.
func LeaseOwnerHasPrefix(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldHasPrefix(FieldLeaseOwner, v))
}

// LeaseOwnerHasSuffix applies the HasSuffix predicate on the "lease_owner" field.
func LeaseOwnerHasSuffix(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldHasSuffix(FieldLeaseOwner, v))
}

// LeaseOwnerEqualFold applies the EqualFold predicate on the "lease_owner" field.
func LeaseOwnerEqualFold(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEqualFold(FieldLeaseOwner, v))
}

// LeaseOwnerContainsFold applies the ContainsFold predicate on the "lease_owner" field.
func LeaseOwnerContainsFold(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldContainsFold(FieldLeaseOwner, v))
}

// LeaseExpiresAtEQ applies the EQ predicate on the "lease_expires_at" field.
func LeaseExpiresAtEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtNEQ applies the NEQ predicate on the "lease_expires_at" field.
func LeaseExpiresAtNEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtIn applies the In predicate on the "lease_expires_at" field.
func LeaseExpiresAtIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldLeaseExpiresAt, vs...))
}

// LeaseExpiresAtNotIn applies the NotIn predicate on the "lease_expires_at" field.
func LeaseExpiresAtNotIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldLeaseExpiresAt, vs...))
}

// LeaseExpiresAtGT applies the GT predicate on the "lease_expires_at" field.
func LeaseExpiresAtGT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtGTE applies the GTE predicate on the "lease_expires_at" field.
func LeaseExpiresAtGTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtLT applies the LT predicate on the "lease_expires_at" field.
func LeaseExpiresAtLT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtLTE applies the LTE predicate on the "lease_expires_at" field.
func LeaseExpiresAtLTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtIsNil applies the IsNil predicate on the "lease_expires_at" field.
func LeaseExpiresAtIsNil() predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIsNull(FieldLeaseExpiresAt))
}

// LeaseExpiresAtNotNil applies the NotNil predicate on the "lease_expires_at" field.
func LeaseExpiresAtNotNil() predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotNull(FieldLeaseExpiresAt))
}

// ScheduledAtEQ applies the EQ predicate on the "scheduled_at" field.
func ScheduledAtEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldScheduledAt, v))
}

// ScheduledAtNEQ applies the NEQ predicate on the "scheduled_at" field.
func ScheduledAtNEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldScheduledAt, v))
}

// ScheduledAtIn applies the In predicate on the "scheduled_at" field.
func ScheduledAtIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldScheduledAt, vs...))
}

// ScheduledAtNotIn applies the NotIn predicate on the "scheduled_at" field.
func ScheduledAtNotIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldScheduledAt, vs...))
}

// ScheduledAtGT applies the GT predicate on the "scheduled_at" field.
func ScheduledAtGT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldScheduledAt, v))
}

// ScheduledAtGTE applies the GTE predicate on the "scheduled_at" field.
func ScheduledAtGTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldScheduledAt, v))
}

// ScheduledAtLT applies the LT predicate on the "scheduled_at" field.
func ScheduledAtLT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldScheduledAt, v))
}

// ScheduledAtLTE applies the LTE predicate on the "scheduled_at" field.
func ScheduledAtLTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldScheduledAt, v))
}

// NextAttemptAtEQ applies the EQ predicate on the "next_attempt_at" field.
func NextAttemptAtEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtNEQ applies the NEQ predicate on the "next_attempt_at" field.
func NextAttemptAtNEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtIn applies the In predicate on the "next_attempt_at" field.
func NextAttemptAtIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtNotIn applies the NotIn predicate on the "next_attempt_at" field.
func NextAttemptAtNotIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtGT applies the GT predicate on the "next_attempt_at" field.
func NextAttemptAtGT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldNextAttemptAt, v))
}

// NextAttemptAtGTE applies the GTE predicate on the "next_attempt_at" field.
func NextAttemptAtGTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldNextAttemptAt, v))
}

// NextAttemptAtLT applies the LT predicate on the "next_attempt_at" field.
func NextAttemptAtLT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldNextAttemptAt, v))
}

// NextAttemptAtLTE applies the LTE predicate on the "next_attempt_at" field.
func NextAttemptAtLTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldNextAttemptAt, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotNull(FieldFinishedAt))
}

// AttemptCountEQ applies the EQ predicate on the "attempt_count" field.
func AttemptCountEQ(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attempt_count" field.
func AttemptCountNEQ(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attempt_count" field.
func AttemptCountIn(vs ...int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attempt_count" field.
func AttemptCountNotIn(vs ...int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attempt_count" field.
func AttemptCountGT(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attempt_count" field.
func AttemptCountGTE(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attempt_count" field.
func AttemptCountLT(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attempt_count" field.
func AttemptCountLTE(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldAttemptCount, v))
}

// MaxAttemptsEQ applies the EQ predicate on the "max_attempts" field.
func MaxAttemptsEQ(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldMaxAttempts, v))
}

// MaxAttemptsNEQ applies the NEQ predicate on the "max_attempts" field.
func MaxAttemptsNEQ(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldMaxAttempts, v))
}

// MaxAttemptsIn applies the In predicate on the "max_attempts" field.
func MaxAttemptsIn(vs ...int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldMaxAttempts, vs...))
}

// MaxAttemptsNotIn applies the NotIn predicate on the "max_attempts" field.
func MaxAttemptsNotIn(vs ...int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldMaxAttempts, vs...))
}

// MaxAttemptsGT applies the GT predicate on the "max_attempts" field.
func MaxAttemptsGT(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldMaxAttempts, v))
}

// MaxAttemptsGTE applies the GTE predicate on the "max_attempts" field.
func MaxAttemptsGTE(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldMaxAttempts, v))
}

// MaxAttemptsLT applies the LT predicate on the "max_attempts" field.
func MaxAttemptsLT(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldMaxAttempts, v))
}

// MaxAttemptsLTE applies the LTE predicate on the "max_attempts" field.
func MaxAttemptsLTE(v int) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldMaxAttempts, v))
}

// TotalUsersEQ applies the EQ predicate on the "total_users" field.
func TotalUsersEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldTotalUsers, v))
}

// TotalUsersNEQ applies the NEQ predicate on the "total_users" field.
func TotalUsersNEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldTotalUsers, v))
}

// TotalUsersIn applies the In predicate on the "total_users" field.
func TotalUsersIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldTotalUsers, vs...))
}

// TotalUsersNotIn applies the NotIn predicate on the "total_users" field.
func TotalUsersNotIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldTotalUsers, vs...))
}

// TotalUsersGT applies the GT predicate on the "total_users" field.
func TotalUsersGT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldTotalUsers, v))
}

// TotalUsersGTE applies the GTE predicate on the "total_users" field.
func TotalUsersGTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldTotalUsers, v))
}

// TotalUsersLT applies the LT predicate on the "total_users" field.
func TotalUsersLT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldTotalUsers, v))
}

// TotalUsersLTE applies the LTE predicate on the "total_users" field.
func TotalUsersLTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldTotalUsers, v))
}

// ScannedUsersEQ applies the EQ predicate on the "scanned_users" field.
func ScannedUsersEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldScannedUsers, v))
}

// ScannedUsersNEQ applies the NEQ predicate on the "scanned_users" field.
func ScannedUsersNEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldScannedUsers, v))
}

// ScannedUsersIn applies the In predicate on the "scanned_users" field.
func ScannedUsersIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldScannedUsers, vs...))
}

// ScannedUsersNotIn applies the NotIn predicate on the "scanned_users" field.
func ScannedUsersNotIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldScannedUsers, vs...))
}

// ScannedUsersGT applies the GT predicate on the "scanned_users" field.
func ScannedUsersGT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldScannedUsers, v))
}

// ScannedUsersGTE applies the GTE predicate on the "scanned_users" field.
func ScannedUsersGTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldScannedUsers, v))
}

// ScannedUsersLT applies the LT predicate on the "scanned_users" field.
func ScannedUsersLT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldScannedUsers, v))
}

// ScannedUsersLTE applies the LTE predicate on the "scanned_users" field.
func ScannedUsersLTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldScannedUsers, v))
}

// MatchedUsersEQ applies the EQ predicate on the "matched_users" field.
func MatchedUsersEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldMatchedUsers, v))
}

// MatchedUsersNEQ applies the NEQ predicate on the "matched_users" field.
func MatchedUsersNEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldMatchedUsers, v))
}

// MatchedUsersIn applies the In predicate on the "matched_users" field.
func MatchedUsersIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldMatchedUsers, vs...))
}

// MatchedUsersNotIn applies the NotIn predicate on the "matched_users" field.
func MatchedUsersNotIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldMatchedUsers, vs...))
}

// MatchedUsersGT applies the GT predicate on the "matched_users" field.
func MatchedUsersGT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldMatchedUsers, v))
}

// MatchedUsersGTE applies the GTE predicate on the "matched_users" field.
func MatchedUsersGTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldMatchedUsers, v))
}

// MatchedUsersLT applies the LT predicate on the "matched_users" field.
func MatchedUsersLT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldMatchedUsers, v))
}

// MatchedUsersLTE applies the LTE predicate on the "matched_users" field.
func MatchedUsersLTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldMatchedUsers, v))
}

// GrantedUsersEQ applies the EQ predicate on the "granted_users" field.
func GrantedUsersEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldGrantedUsers, v))
}

// GrantedUsersNEQ applies the NEQ predicate on the "granted_users" field.
func GrantedUsersNEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldGrantedUsers, v))
}

// GrantedUsersIn applies the In predicate on the "granted_users" field.
func GrantedUsersIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldGrantedUsers, vs...))
}

// GrantedUsersNotIn applies the NotIn predicate on the "granted_users" field.
func GrantedUsersNotIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldGrantedUsers, vs...))
}

// GrantedUsersGT applies the GT predicate on the "granted_users" field.
func GrantedUsersGT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldGrantedUsers, v))
}

// GrantedUsersGTE applies the GTE predicate on the "granted_users" field.
func GrantedUsersGTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldGrantedUsers, v))
}

// GrantedUsersLT applies the LT predicate on the "granted_users" field.
func GrantedUsersLT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldGrantedUsers, v))
}

// GrantedUsersLTE applies the LTE predicate on the "granted_users" field.
func GrantedUsersLTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldGrantedUsers, v))
}

// SkippedUsersEQ applies the EQ predicate on the "skipped_users" field.
func SkippedUsersEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldSkippedUsers, v))
}

// SkippedUsersNEQ applies the NEQ predicate on the "skipped_users" field.
func SkippedUsersNEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldSkippedUsers, v))
}

// SkippedUsersIn applies the In predicate on the "skipped_users" field.
func SkippedUsersIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldSkippedUsers, vs...))
}

// SkippedUsersNotIn applies the NotIn predicate on the "skipped_users" field.
func SkippedUsersNotIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldSkippedUsers, vs...))
}

// SkippedUsersGT applies the GT predicate on the "skipped_users" field.
func SkippedUsersGT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldSkippedUsers, v))
}

// SkippedUsersGTE applies the GTE predicate on the "skipped_users" field.
func SkippedUsersGTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldSkippedUsers, v))
}

// SkippedUsersLT applies the LT predicate on the "skipped_users" field.
func SkippedUsersLT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldSkippedUsers, v))
}

// SkippedUsersLTE applies the LTE predicate on the "skipped_users" field.
func SkippedUsersLTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldSkippedUsers, v))
}

// FailedUsersEQ applies the EQ predicate on the "failed_users" field.
func FailedUsersEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldFailedUsers, v))
}

// FailedUsersNEQ applies the NEQ predicate on the "failed_users" field.
func FailedUsersNEQ(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldFailedUsers, v))
}

// FailedUsersIn applies the In predicate on the "failed_users" field.
func FailedUsersIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldFailedUsers, vs...))
}

// FailedUsersNotIn applies the NotIn predicate on the "failed_users" field.
func FailedUsersNotIn(vs ...int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldFailedUsers, vs...))
}

// FailedUsersGT applies the GT predicate on the "failed_users" field.
func FailedUsersGT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldFailedUsers, v))
}

// FailedUsersGTE applies the GTE predicate on the "failed_users" field.
func FailedUsersGTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldFailedUsers, v))
}

// FailedUsersLT applies the LT predicate on the "failed_users" field.
func FailedUsersLT(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldFailedUsers, v))
}

// FailedUsersLTE applies the LTE predicate on the "failed_users" field.
func FailedUsersLTE(v int64) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldFailedUsers, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.FieldContainsFold(FieldLastError, v))
}

// HasCampaign applies the HasEdge predicate on the "campaign" edge.
func HasCampaign() predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CampaignTable, CampaignColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCampaignWith applies the HasEdge predicate on the "campaign" edge with a given conditions (other predicates).
func HasCampaignWith(preds ...predicate.RewardCampaign) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(func(s *sql.Selector) {
		step := newCampaignStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCampaignVersion applies the HasEdge predicate on the "campaign_version" edge.
func HasCampaignVersion() predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CampaignVersionTable, CampaignVersionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCampaignVersionWith applies the HasEdge predicate on the "campaign_version" edge with a given conditions (other predicates).
func HasCampaignVersionWith(preds ...predicate.RewardCampaignVersion) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(func(s *sql.Selector) {
		step := newCampaignVersionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGrants applies the HasEdge predicate on the "grants" edge.
func HasGrants() predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GrantsTable, GrantsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGrantsWith applies the HasEdge predicate on the "grants" edge with a given conditions (other predicates).
func HasGrantsWith(preds ...predicate.UserRewardGrant) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(func(s *sql.Selector) {
		step := newGrantsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RewardCampaignJob) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RewardCampaignJob) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RewardCampaignJob) predicate.RewardCampaignJob {
	return predicate.RewardCampaignJob(sql.NotPredicates(p))
}
