// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/merchantapiendpoint"
	"github.com/Wei-Shaw/sub2api/ent/merchantbinding"
	"github.com/Wei-Shaw/sub2api/ent/merchantintegration"
	"github.com/Wei-Shaw/sub2api/ent/merchantrechargerecord"
)

// MerchantIntegrationCreate is the builder for creating a MerchantIntegration entity.
type MerchantIntegrationCreate struct {
	config
	mutation *MerchantIntegrationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MerchantIntegrationCreate) SetCreatedAt(v time.Time) *MerchantIntegrationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MerchantIntegrationCreate) SetNillableCreatedAt(v *time.Time) *MerchantIntegrationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MerchantIntegrationCreate) SetUpdatedAt(v time.Time) *MerchantIntegrationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MerchantIntegrationCreate) SetNillableUpdatedAt(v *time.Time) *MerchantIntegrationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *MerchantIntegrationCreate) SetName(v string) *MerchantIntegrationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *MerchantIntegrationCreate) SetCode(v string) *MerchantIntegrationCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *MerchantIntegrationCreate) SetMode(v string) *MerchantIntegrationCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *MerchantIntegrationCreate) SetNillableMode(v *string) *MerchantIntegrationCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetMerchantCode sets the "merchant_code" field.
func (_c *MerchantIntegrationCreate) SetMerchantCode(v string) *MerchantIntegrationCreate {
	_c.mutation.SetMerchantCode(v)
	return _c
}

// SetNillableMerchantCode sets the "merchant_code" field if the given value is not nil.
func (_c *MerchantIntegrationCreate) SetNillableMerchantCode(v *string) *MerchantIntegrationCreate {
	if v != nil {
		_c.SetMerchantCode(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *MerchantIntegrationCreate) SetDescription(v string) *MerchantIntegrationCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MerchantIntegrationCreate) SetNillableDescription(v *string) *MerchantIntegrationCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *MerchantIntegrationCreate) SetStatus(v string) *MerchantIntegrationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MerchantIntegrationCreate) SetNillableStatus(v *string) *MerchantIntegrationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *MerchantIntegrationCreate) SetEnabled(v bool) *MerchantIntegrationCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *MerchantIntegrationCreate) SetNillableEnabled(v *bool) *MerchantIntegrationCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRedirectHosts sets the "redirect_hosts" field.
func (_c *MerchantIntegrationCreate) SetRedirectHosts(v []string) *MerchantIntegrationCreate {
	_c.mutation.SetRedirectHosts(v)
	return _c
}

// AddEndpointIDs adds the "endpoints" edge to the MerchantAPIEndpoint entity by IDs.
func (_c *MerchantIntegrationCreate) AddEndpointIDs(ids ...int64) *MerchantIntegrationCreate {
	_c.mutation.AddEndpointIDs(ids...)
	return _c
}

// AddEndpoints adds the "endpoints" edges to the MerchantAPIEndpoint entity.
func (_c *MerchantIntegrationCreate) AddEndpoints(v ...*MerchantAPIEndpoint) *MerchantIntegrationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEndpointIDs(ids...)
}

// AddBindingIDs adds the "bindings" edge to the MerchantBinding entity by IDs.
func (_c *MerchantIntegrationCreate) AddBindingIDs(ids ...int64) *MerchantIntegrationCreate {
	_c.mutation.AddBindingIDs(ids...)
	return _c
}

// AddBindings adds the "bindings" edges to the MerchantBinding entity.
func (_c *MerchantIntegrationCreate) AddBindings(v ...*MerchantBinding) *MerchantIntegrationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBindingIDs(ids...)
}

// AddRechargeRecordIDs adds the "recharge_records" edge to the MerchantRechargeRecord entity by IDs.
func (_c *MerchantIntegrationCreate) AddRechargeRecordIDs(ids ...int64) *MerchantIntegrationCreate {
	_c.mutation.AddRechargeRecordIDs(ids...)
	return _c
}

// AddRechargeRecords adds the "recharge_records" edges to the MerchantRechargeRecord entity.
func (_c *MerchantIntegrationCreate) AddRechargeRecords(v ...*MerchantRechargeRecord) *MerchantIntegrationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRechargeRecordIDs(ids...)
}

// Mutation returns the MerchantIntegrationMutation object of the builder.
func (_c *MerchantIntegrationCreate) Mutation() *MerchantIntegrationMutation {
	return _c.mutation
}

// Save creates the MerchantIntegration in the database.
func (_c *MerchantIntegrationCreate) Save(ctx context.Context) (*MerchantIntegration, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MerchantIntegrationCreate) SaveX(ctx context.Context) *MerchantIntegration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MerchantIntegrationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MerchantIntegrationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MerchantIntegrationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := merchantintegration.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := merchantintegration.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Mode(); !ok {
		v := merchantintegration.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.MerchantCode(); !ok {
		v := merchantintegration.DefaultMerchantCode
		_c.mutation.SetMerchantCode(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := merchantintegration.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := merchantintegration.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := merchantintegration.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MerchantIntegrationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MerchantIntegration.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MerchantIntegration.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MerchantIntegration.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := merchantintegration.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MerchantIntegration.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "MerchantIntegration.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := merchantintegration.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "MerchantIntegration.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "MerchantIntegration.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := merchantintegration.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "MerchantIntegration.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MerchantCode(); !ok {
		return &ValidationError{Name: "merchant_code", err: errors.New(`ent: missing required field "MerchantIntegration.merchant_code"`)}
	}
	if v, ok := _c.mutation.MerchantCode(); ok {
		if err := merchantintegration.MerchantCodeValidator(v); err != nil {
			return &ValidationError{Name: "merchant_code", err: fmt.Errorf(`ent: validator failed for field "MerchantIntegration.merchant_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "MerchantIntegration.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := merchantintegration.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "MerchantIntegration.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MerchantIntegration.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := merchantintegration.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MerchantIntegration.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "MerchantIntegration.enabled"`)}
	}
	if _, ok := _c.mutation.RedirectHosts(); !ok {
		return &ValidationError{Name: "redirect_hosts", err: errors.New(`ent: missing required field "MerchantIntegration.redirect_hosts"`)}
	}
	return nil
}

func (_c *MerchantIntegrationCreate) sqlSave(ctx context.Context) (*MerchantIntegration, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MerchantIntegrationCreate) createSpec() (*MerchantIntegration, *sqlgraph.CreateSpec) {
	var (
		_node = &MerchantIntegration{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(merchantintegration.Table, sqlgraph.NewFieldSpec(merchantintegration.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(merchantintegration.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(merchantintegration.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(merchantintegration.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(merchantintegration.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(merchantintegration.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.MerchantCode(); ok {
		_spec.SetField(merchantintegration.FieldMerchantCode, field.TypeString, value)
		_node.MerchantCode = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(merchantintegration.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(merchantintegration.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(merchantintegration.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.RedirectHosts(); ok {
		_spec.SetField(merchantintegration.FieldRedirectHosts, field.TypeJSON, value)
		_node.RedirectHosts = value
	}
	if nodes := _c.mutation.EndpointsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   merchantintegration.EndpointsTable,
			Columns: []string{merchantintegration.EndpointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchantapiendpoint.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   merchantintegration.BindingsTable,
			Columns: []string{merchantintegration.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchantbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RechargeRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   merchantintegration.RechargeRecordsTable,
			Columns: []string{merchantintegration.RechargeRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchantrechargerecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MerchantIntegration.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MerchantIntegrationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MerchantIntegrationCreate) OnConflict(opts ...sql.ConflictOption) *MerchantIntegrationUpsertOne {
	_c.conflict = opts
	return &MerchantIntegrationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MerchantIntegration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MerchantIntegrationCreate) OnConflictColumns(columns ...string) *MerchantIntegrationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MerchantIntegrationUpsertOne{
		create: _c,
	}
}

type (
	// MerchantIntegrationUpsertOne is the builder for "upsert"-ing
	//  one MerchantIntegration node.
	MerchantIntegrationUpsertOne struct {
		create *MerchantIntegrationCreate
	}

	// MerchantIntegrationUpsert is the "OnConflict" setter.
	MerchantIntegrationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MerchantIntegrationUpsert) SetUpdatedAt(v time.Time) *MerchantIntegrationUpsert {
	u.Set(merchantintegration.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MerchantIntegrationUpsert) UpdateUpdatedAt() *MerchantIntegrationUpsert {
	u.SetExcluded(merchantintegration.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *MerchantIntegrationUpsert) SetName(v string) *MerchantIntegrationUpsert {
	u.Set(merchantintegration.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MerchantIntegrationUpsert) UpdateName() *MerchantIntegrationUpsert {
	u.SetExcluded(merchantintegration.FieldName)
	return u
}

// SetCode sets the "code" field.
func (u *MerchantIntegrationUpsert) SetCode(v string) *MerchantIntegrationUpsert {
	u.Set(merchantintegration.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *MerchantIntegrationUpsert) UpdateCode() *MerchantIntegrationUpsert {
	u.SetExcluded(merchantintegration.FieldCode)
	return u
}

// SetMode sets the "mode" field.
func (u *MerchantIntegrationUpsert) SetMode(v string) *MerchantIntegrationUpsert {
	u.Set(merchantintegration.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *MerchantIntegrationUpsert) UpdateMode() *MerchantIntegrationUpsert {
	u.SetExcluded(merchantintegration.FieldMode)
	return u
}

// SetMerchantCode sets the "merchant_code" field.
func (u *MerchantIntegrationUpsert) SetMerchantCode(v string) *MerchantIntegrationUpsert {
	u.Set(merchantintegration.FieldMerchantCode, v)
	return u
}

// UpdateMerchantCode sets the "merchant_code" field to the value that was provided on create.
func (u *MerchantIntegrationUpsert) UpdateMerchantCode() *MerchantIntegrationUpsert {
	u.SetExcluded(merchantintegration.FieldMerchantCode)
	return u
}

// SetDescription sets the "description" field.
func (u *MerchantIntegrationUpsert) SetDescription(v string) *MerchantIntegrationUpsert {
	u.Set(merchantintegration.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MerchantIntegrationUpsert) UpdateDescription() *MerchantIntegrationUpsert {
	u.SetExcluded(merchantintegration.FieldDescription)
	return u
}

// SetStatus sets the "status" field.
func (u *MerchantIntegrationUpsert) SetStatus(v string) *MerchantIntegrationUpsert {
	u.Set(merchantintegration.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MerchantIntegrationUpsert) UpdateStatus() *MerchantIntegrationUpsert {
	u.SetExcluded(merchantintegration.FieldStatus)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *MerchantIntegrationUpsert) SetEnabled(v bool) *MerchantIntegrationUpsert {
	u.Set(merchantintegration.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *MerchantIntegrationUpsert) UpdateEnabled() *MerchantIntegrationUpsert {
	u.SetExcluded(merchantintegration.FieldEnabled)
	return u
}

// SetRedirectHosts sets the "redirect_hosts" field.
func (u *MerchantIntegrationUpsert) SetRedirectHosts(v []string) *MerchantIntegrationUpsert {
	u.Set(merchantintegration.FieldRedirectHosts, v)
	return u
}

// UpdateRedirectHosts sets the "redirect_hosts" field to the value that was provided on create.
func (u *MerchantIntegrationUpsert) UpdateRedirectHosts() *MerchantIntegrationUpsert {
	u.SetExcluded(merchantintegration.FieldRedirectHosts)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MerchantIntegration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MerchantIntegrationUpsertOne) UpdateNewValues() *MerchantIntegrationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(merchantintegration.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MerchantIntegration.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MerchantIntegrationUpsertOne) Ignore() *MerchantIntegrationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MerchantIntegrationUpsertOne) DoNothing() *MerchantIntegrationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MerchantIntegrationCreate.OnConflict
// documentation for more info.
func (u *MerchantIntegrationUpsertOne) Update(set func(*MerchantIntegrationUpsert)) *MerchantIntegrationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MerchantIntegrationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MerchantIntegrationUpsertOne) SetUpdatedAt(v time.Time) *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertOne) UpdateUpdatedAt() *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *MerchantIntegrationUpsertOne) SetName(v string) *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertOne) UpdateName() *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateName()
	})
}

// SetCode sets the "code" field.
func (u *MerchantIntegrationUpsertOne) SetCode(v string) *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertOne) UpdateCode() *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateCode()
	})
}

// SetMode sets the "mode" field.
func (u *MerchantIntegrationUpsertOne) SetMode(v string) *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertOne) UpdateMode() *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateMode()
	})
}

// SetMerchantCode sets the "merchant_code" field.
func (u *MerchantIntegrationUpsertOne) SetMerchantCode(v string) *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetMerchantCode(v)
	})
}

// UpdateMerchantCode sets the "merchant_code" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertOne) UpdateMerchantCode() *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateMerchantCode()
	})
}

// SetDescription sets the "description" field.
func (u *MerchantIntegrationUpsertOne) SetDescription(v string) *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertOne) UpdateDescription() *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateDescription()
	})
}

// SetStatus sets the "status" field.
func (u *MerchantIntegrationUpsertOne) SetStatus(v string) *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertOne) UpdateStatus() *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateStatus()
	})
}

// SetEnabled sets the "enabled" field.
func (u *MerchantIntegrationUpsertOne) SetEnabled(v bool) *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertOne) UpdateEnabled() *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateEnabled()
	})
}

// SetRedirectHosts sets the "redirect_hosts" field.
func (u *MerchantIntegrationUpsertOne) SetRedirectHosts(v []string) *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetRedirectHosts(v)
	})
}

// UpdateRedirectHosts sets the "redirect_hosts" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertOne) UpdateRedirectHosts() *MerchantIntegrationUpsertOne {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateRedirectHosts()
	})
}

// Exec executes the query.
func (u *MerchantIntegrationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MerchantIntegrationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MerchantIntegrationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MerchantIntegrationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MerchantIntegrationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MerchantIntegrationCreateBulk is the builder for creating many MerchantIntegration entities in bulk.
type MerchantIntegrationCreateBulk struct {
	config
	err      error
	builders []*MerchantIntegrationCreate
	conflict []sql.ConflictOption
}

// Save creates the MerchantIntegration entities in the database.
func (_c *MerchantIntegrationCreateBulk) Save(ctx context.Context) ([]*MerchantIntegration, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MerchantIntegration, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MerchantIntegrationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MerchantIntegrationCreateBulk) SaveX(ctx context.Context) []*MerchantIntegration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MerchantIntegrationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MerchantIntegrationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MerchantIntegration.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MerchantIntegrationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MerchantIntegrationCreateBulk) OnConflict(opts ...sql.ConflictOption) *MerchantIntegrationUpsertBulk {
	_c.conflict = opts
	return &MerchantIntegrationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MerchantIntegration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MerchantIntegrationCreateBulk) OnConflictColumns(columns ...string) *MerchantIntegrationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MerchantIntegrationUpsertBulk{
		create: _c,
	}
}

// MerchantIntegrationUpsertBulk is the builder for "upsert"-ing
// a bulk of MerchantIntegration nodes.
type MerchantIntegrationUpsertBulk struct {
	create *MerchantIntegrationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MerchantIntegration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MerchantIntegrationUpsertBulk) UpdateNewValues() *MerchantIntegrationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(merchantintegration.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MerchantIntegration.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MerchantIntegrationUpsertBulk) Ignore() *MerchantIntegrationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MerchantIntegrationUpsertBulk) DoNothing() *MerchantIntegrationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MerchantIntegrationCreateBulk.OnConflict
// documentation for more info.
func (u *MerchantIntegrationUpsertBulk) Update(set func(*MerchantIntegrationUpsert)) *MerchantIntegrationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MerchantIntegrationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MerchantIntegrationUpsertBulk) SetUpdatedAt(v time.Time) *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertBulk) UpdateUpdatedAt() *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *MerchantIntegrationUpsertBulk) SetName(v string) *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertBulk) UpdateName() *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateName()
	})
}

// SetCode sets the "code" field.
func (u *MerchantIntegrationUpsertBulk) SetCode(v string) *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertBulk) UpdateCode() *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateCode()
	})
}

// SetMode sets the "mode" field.
func (u *MerchantIntegrationUpsertBulk) SetMode(v string) *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertBulk) UpdateMode() *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateMode()
	})
}

// SetMerchantCode sets the "merchant_code" field.
func (u *MerchantIntegrationUpsertBulk) SetMerchantCode(v string) *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetMerchantCode(v)
	})
}

// UpdateMerchantCode sets the "merchant_code" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertBulk) UpdateMerchantCode() *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateMerchantCode()
	})
}

// SetDescription sets the "description" field.
func (u *MerchantIntegrationUpsertBulk) SetDescription(v string) *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertBulk) UpdateDescription() *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateDescription()
	})
}

// SetStatus sets the "status" field.
func (u *MerchantIntegrationUpsertBulk) SetStatus(v string) *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertBulk) UpdateStatus() *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateStatus()
	})
}

// SetEnabled sets the "enabled" field.
func (u *MerchantIntegrationUpsertBulk) SetEnabled(v bool) *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertBulk) UpdateEnabled() *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateEnabled()
	})
}

// SetRedirectHosts sets the "redirect_hosts" field.
func (u *MerchantIntegrationUpsertBulk) SetRedirectHosts(v []string) *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.SetRedirectHosts(v)
	})
}

// UpdateRedirectHosts sets the "redirect_hosts" field to the value that was provided on create.
func (u *MerchantIntegrationUpsertBulk) UpdateRedirectHosts() *MerchantIntegrationUpsertBulk {
	return u.Update(func(s *MerchantIntegrationUpsert) {
		s.UpdateRedirectHosts()
	})
}

// Exec executes the query.
func (u *MerchantIntegrationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MerchantIntegrationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MerchantIntegrationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MerchantIntegrationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
