// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/merchantbinding"
	"github.com/Wei-Shaw/sub2api/ent/merchantintegration"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// MerchantBinding is the model entity for the MerchantBinding schema.
type MerchantBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// IntegrationID holds the value of the "integration_id" field.
	IntegrationID int64 `json:"integration_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ExternalUserID holds the value of the "external_user_id" field.
	ExternalUserID string `json:"external_user_id,omitempty"`
	// ExternalAccount holds the value of the "external_account" field.
	ExternalAccount string `json:"external_account,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// LastLoginAt holds the value of the "last_login_at" field.
	LastLoginAt *time.Time `json:"last_login_at,omitempty"`
	// LastSyncAt holds the value of the "last_sync_at" field.
	LastSyncAt *time.Time `json:"last_sync_at,omitempty"`
	// LastRechargeSyncAt holds the value of the "last_recharge_sync_at" field.
	LastRechargeSyncAt *time.Time `json:"last_recharge_sync_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MerchantBindingQuery when eager-loading is set.
	Edges        MerchantBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MerchantBindingEdges holds the relations/edges for other nodes in the graph.
type MerchantBindingEdges struct {
	// Integration holds the value of the integration edge.
	Integration *MerchantIntegration `json:"integration,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// IntegrationOrErr returns the Integration value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MerchantBindingEdges) IntegrationOrErr() (*MerchantIntegration, error) {
	if e.Integration != nil {
		return e.Integration, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: merchantintegration.Label}
	}
	return nil, &NotLoadedError{edge: "integration"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MerchantBindingEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MerchantBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case merchantbinding.FieldID, merchantbinding.FieldIntegrationID, merchantbinding.FieldUserID:
			values[i] = new(sql.NullInt64)
		case merchantbinding.FieldExternalUserID, merchantbinding.FieldExternalAccount, merchantbinding.FieldStatus:
			values[i] = new(sql.NullString)
		case merchantbinding.FieldCreatedAt, merchantbinding.FieldUpdatedAt, merchantbinding.FieldLastLoginAt, merchantbinding.FieldLastSyncAt, merchantbinding.FieldLastRechargeSyncAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MerchantBinding fields.
func (_m *MerchantBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case merchantbinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case merchantbinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case merchantbinding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case merchantbinding.FieldIntegrationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field integration_id", values[i])
			} else if value.Valid {
				_m.IntegrationID = value.Int64
			}
		case merchantbinding.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case merchantbinding.FieldExternalUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_user_id", values[i])
			} else if value.Valid {
				_m.ExternalUserID = value.String
			}
		case merchantbinding.FieldExternalAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_account", values[i])
			} else if value.Valid {
				_m.ExternalAccount = value.String
			}
		case merchantbinding.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case merchantbinding.FieldLastLoginAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_login_at", values[i])
			} else if value.Valid {
				_m.LastLoginAt = new(time.Time)
				*_m.LastLoginAt = value.Time
			}
		case merchantbinding.FieldLastSyncAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_at", values[i])
			} else if value.Valid {
				_m.LastSyncAt = new(time.Time)
				*_m.LastSyncAt = value.Time
			}
		case merchantbinding.FieldLastRechargeSyncAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_recharge_sync_at", values[i])
			} else if value.Valid {
				_m.LastRechargeSyncAt = new(time.Time)
				*_m.LastRechargeSyncAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MerchantBinding.
// This includes values selected through modifiers, order, etc.
func (_m *MerchantBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryIntegration queries the "integration" edge of the MerchantBinding entity.
func (_m *MerchantBinding) QueryIntegration() *MerchantIntegrationQuery {
	return NewMerchantBindingClient(_m.config).QueryIntegration(_m)
}

// QueryUser queries the "user" edge of the MerchantBinding entity.
func (_m *MerchantBinding) QueryUser() *UserQuery {
	return NewMerchantBindingClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this MerchantBinding.
// Note that you need to call MerchantBinding.Unwrap() before calling this method if this MerchantBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MerchantBinding) Update() *MerchantBindingUpdateOne {
	return NewMerchantBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MerchantBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MerchantBinding) Unwrap() *MerchantBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MerchantBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MerchantBinding) String() string {
	var builder strings.Builder
	builder.WriteString("MerchantBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("integration_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.IntegrationID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("external_user_id=")
	builder.WriteString(_m.ExternalUserID)
	builder.WriteString(", ")
	builder.WriteString("external_account=")
	builder.WriteString(_m.ExternalAccount)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.LastLoginAt; v != nil {
		builder.WriteString("last_login_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastSyncAt; v != nil {
		builder.WriteString("last_sync_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastRechargeSyncAt; v != nil {
		builder.WriteString("last_recharge_sync_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MerchantBindings is a parsable slice of MerchantBinding.
type MerchantBindings []*MerchantBinding
