// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rewardcampaignuserstate"
)

// RewardCampaignUserStateUpdate is the builder for updating RewardCampaignUserState entities.
type RewardCampaignUserStateUpdate struct {
	config
	hooks    []Hook
	mutation *RewardCampaignUserStateMutation
}

// Where appends a list predicates to the RewardCampaignUserStateUpdate builder.
func (_u *RewardCampaignUserStateUpdate) Where(ps ...predicate.RewardCampaignUserState) *RewardCampaignUserStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RewardCampaignUserStateUpdate) SetUpdatedAt(v time.Time) *RewardCampaignUserStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (_u *RewardCampaignUserStateUpdate) SetLastEvaluatedAt(v time.Time) *RewardCampaignUserStateUpdate {
	_u.mutation.SetLastEvaluatedAt(v)
	return _u
}

// SetNillableLastEvaluatedAt sets the "last_evaluated_at" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdate) SetNillableLastEvaluatedAt(v *time.Time) *RewardCampaignUserStateUpdate {
	if v != nil {
		_u.SetLastEvaluatedAt(*v)
	}
	return _u
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (_u *RewardCampaignUserStateUpdate) ClearLastEvaluatedAt() *RewardCampaignUserStateUpdate {
	_u.mutation.ClearLastEvaluatedAt()
	return _u
}

// SetLastWonAt sets the "last_won_at" field.
func (_u *RewardCampaignUserStateUpdate) SetLastWonAt(v time.Time) *RewardCampaignUserStateUpdate {
	_u.mutation.SetLastWonAt(v)
	return _u
}

// SetNillableLastWonAt sets the "last_won_at" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdate) SetNillableLastWonAt(v *time.Time) *RewardCampaignUserStateUpdate {
	if v != nil {
		_u.SetLastWonAt(*v)
	}
	return _u
}

// ClearLastWonAt clears the value of the "last_won_at" field.
func (_u *RewardCampaignUserStateUpdate) ClearLastWonAt() *RewardCampaignUserStateUpdate {
	_u.mutation.ClearLastWonAt()
	return _u
}

// SetLastGrantedAt sets the "last_granted_at" field.
func (_u *RewardCampaignUserStateUpdate) SetLastGrantedAt(v time.Time) *RewardCampaignUserStateUpdate {
	_u.mutation.SetLastGrantedAt(v)
	return _u
}

// SetNillableLastGrantedAt sets the "last_granted_at" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdate) SetNillableLastGrantedAt(v *time.Time) *RewardCampaignUserStateUpdate {
	if v != nil {
		_u.SetLastGrantedAt(*v)
	}
	return _u
}

// ClearLastGrantedAt clears the value of the "last_granted_at" field.
func (_u *RewardCampaignUserStateUpdate) ClearLastGrantedAt() *RewardCampaignUserStateUpdate {
	_u.mutation.ClearLastGrantedAt()
	return _u
}

// SetLastClaimedAt sets the "last_claimed_at" field.
func (_u *RewardCampaignUserStateUpdate) SetLastClaimedAt(v time.Time) *RewardCampaignUserStateUpdate {
	_u.mutation.SetLastClaimedAt(v)
	return _u
}

// SetNillableLastClaimedAt sets the "last_claimed_at" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdate) SetNillableLastClaimedAt(v *time.Time) *RewardCampaignUserStateUpdate {
	if v != nil {
		_u.SetLastClaimedAt(*v)
	}
	return _u
}

// ClearLastClaimedAt clears the value of the "last_claimed_at" field.
func (_u *RewardCampaignUserStateUpdate) ClearLastClaimedAt() *RewardCampaignUserStateUpdate {
	_u.mutation.ClearLastClaimedAt()
	return _u
}

// SetNextEligibleAt sets the "next_eligible_at" field.
func (_u *RewardCampaignUserStateUpdate) SetNextEligibleAt(v time.Time) *RewardCampaignUserStateUpdate {
	_u.mutation.SetNextEligibleAt(v)
	return _u
}

// SetNillableNextEligibleAt sets the "next_eligible_at" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdate) SetNillableNextEligibleAt(v *time.Time) *RewardCampaignUserStateUpdate {
	if v != nil {
		_u.SetNextEligibleAt(*v)
	}
	return _u
}

// ClearNextEligibleAt clears the value of the "next_eligible_at" field.
func (_u *RewardCampaignUserStateUpdate) ClearNextEligibleAt() *RewardCampaignUserStateUpdate {
	_u.mutation.ClearNextEligibleAt()
	return _u
}

// SetEvaluationCount sets the "evaluation_count" field.
func (_u *RewardCampaignUserStateUpdate) SetEvaluationCount(v int64) *RewardCampaignUserStateUpdate {
	_u.mutation.ResetEvaluationCount()
	_u.mutation.SetEvaluationCount(v)
	return _u
}

// SetNillableEvaluationCount sets the "evaluation_count" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdate) SetNillableEvaluationCount(v *int64) *RewardCampaignUserStateUpdate {
	if v != nil {
		_u.SetEvaluationCount(*v)
	}
	return _u
}

// AddEvaluationCount adds value to the "evaluation_count" field.
func (_u *RewardCampaignUserStateUpdate) AddEvaluationCount(v int64) *RewardCampaignUserStateUpdate {
	_u.mutation.AddEvaluationCount(v)
	return _u
}

// SetWinCount sets the "win_count" field.
func (_u *RewardCampaignUserStateUpdate) SetWinCount(v int64) *RewardCampaignUserStateUpdate {
	_u.mutation.ResetWinCount()
	_u.mutation.SetWinCount(v)
	return _u
}

// SetNillableWinCount sets the "win_count" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdate) SetNillableWinCount(v *int64) *RewardCampaignUserStateUpdate {
	if v != nil {
		_u.SetWinCount(*v)
	}
	return _u
}

// AddWinCount adds value to the "win_count" field.
func (_u *RewardCampaignUserStateUpdate) AddWinCount(v int64) *RewardCampaignUserStateUpdate {
	_u.mutation.AddWinCount(v)
	return _u
}

// SetGrantCount sets the "grant_count" field.
func (_u *RewardCampaignUserStateUpdate) SetGrantCount(v int64) *RewardCampaignUserStateUpdate {
	_u.mutation.ResetGrantCount()
	_u.mutation.SetGrantCount(v)
	return _u
}

// SetNillableGrantCount sets the "grant_count" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdate) SetNillableGrantCount(v *int64) *RewardCampaignUserStateUpdate {
	if v != nil {
		_u.SetGrantCount(*v)
	}
	return _u
}

// AddGrantCount adds value to the "grant_count" field.
func (_u *RewardCampaignUserStateUpdate) AddGrantCount(v int64) *RewardCampaignUserStateUpdate {
	_u.mutation.AddGrantCount(v)
	return _u
}

// SetClaimCount sets the "claim_count" field.
func (_u *RewardCampaignUserStateUpdate) SetClaimCount(v int64) *RewardCampaignUserStateUpdate {
	_u.mutation.ResetClaimCount()
	_u.mutation.SetClaimCount(v)
	return _u
}

// SetNillableClaimCount sets the "claim_count" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdate) SetNillableClaimCount(v *int64) *RewardCampaignUserStateUpdate {
	if v != nil {
		_u.SetClaimCount(*v)
	}
	return _u
}

// AddClaimCount adds value to the "claim_count" field.
func (_u *RewardCampaignUserStateUpdate) AddClaimCount(v int64) *RewardCampaignUserStateUpdate {
	_u.mutation.AddClaimCount(v)
	return _u
}

// SetControlGroup sets the "control_group" field.
func (_u *RewardCampaignUserStateUpdate) SetControlGroup(v bool) *RewardCampaignUserStateUpdate {
	_u.mutation.SetControlGroup(v)
	return _u
}

// SetNillableControlGroup sets the "control_group" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdate) SetNillableControlGroup(v *bool) *RewardCampaignUserStateUpdate {
	if v != nil {
		_u.SetControlGroup(*v)
	}
	return _u
}

// SetCurrentCycleKey sets the "current_cycle_key" field.
func (_u *RewardCampaignUserStateUpdate) SetCurrentCycleKey(v string) *RewardCampaignUserStateUpdate {
	_u.mutation.SetCurrentCycleKey(v)
	return _u
}

// SetNillableCurrentCycleKey sets the "current_cycle_key" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdate) SetNillableCurrentCycleKey(v *string) *RewardCampaignUserStateUpdate {
	if v != nil {
		_u.SetCurrentCycleKey(*v)
	}
	return _u
}

// Mutation returns the RewardCampaignUserStateMutation object of the builder.
func (_u *RewardCampaignUserStateUpdate) Mutation() *RewardCampaignUserStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RewardCampaignUserStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RewardCampaignUserStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RewardCampaignUserStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RewardCampaignUserStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RewardCampaignUserStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rewardcampaignuserstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RewardCampaignUserStateUpdate) check() error {
	if v, ok := _u.mutation.EvaluationCount(); ok {
		if err := rewardcampaignuserstate.EvaluationCountValidator(v); err != nil {
			return &ValidationError{Name: "evaluation_count", err: fmt.Errorf(`ent: validator failed for field "RewardCampaignUserState.evaluation_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WinCount(); ok {
		if err := rewardcampaignuserstate.WinCountValidator(v); err != nil {
			return &ValidationError{Name: "win_count", err: fmt.Errorf(`ent: validator failed for field "RewardCampaignUserState.win_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GrantCount(); ok {
		if err := rewardcampaignuserstate.GrantCountValidator(v); err != nil {
			return &ValidationError{Name: "grant_count", err: fmt.Errorf(`ent: validator failed for field "RewardCampaignUserState.grant_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClaimCount(); ok {
		if err := rewardcampaignuserstate.ClaimCountValidator(v); err != nil {
			return &ValidationError{Name: "claim_count", err: fmt.Errorf(`ent: validator failed for field "RewardCampaignUserState.claim_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentCycleKey(); ok {
		if err := rewardcampaignuserstate.CurrentCycleKeyValidator(v); err != nil {
			return &ValidationError{Name: "current_cycle_key", err: fmt.Errorf(`ent: validator failed for field "RewardCampaignUserState.current_cycle_key": %w`, err)}
		}
	}
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RewardCampaignUserState.campaign"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RewardCampaignUserState.user"`)
	}
	return nil
}

func (_u *RewardCampaignUserStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rewardcampaignuserstate.Table, rewardcampaignuserstate.Columns, sqlgraph.NewFieldSpec(rewardcampaignuserstate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastEvaluatedAt(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldLastEvaluatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastEvaluatedAtCleared() {
		_spec.ClearField(rewardcampaignuserstate.FieldLastEvaluatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastWonAt(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldLastWonAt, field.TypeTime, value)
	}
	if _u.mutation.LastWonAtCleared() {
		_spec.ClearField(rewardcampaignuserstate.FieldLastWonAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastGrantedAt(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldLastGrantedAt, field.TypeTime, value)
	}
	if _u.mutation.LastGrantedAtCleared() {
		_spec.ClearField(rewardcampaignuserstate.FieldLastGrantedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastClaimedAt(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldLastClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.LastClaimedAtCleared() {
		_spec.ClearField(rewardcampaignuserstate.FieldLastClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextEligibleAt(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldNextEligibleAt, field.TypeTime, value)
	}
	if _u.mutation.NextEligibleAtCleared() {
		_spec.ClearField(rewardcampaignuserstate.FieldNextEligibleAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EvaluationCount(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldEvaluationCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEvaluationCount(); ok {
		_spec.AddField(rewardcampaignuserstate.FieldEvaluationCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WinCount(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldWinCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWinCount(); ok {
		_spec.AddField(rewardcampaignuserstate.FieldWinCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GrantCount(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldGrantCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGrantCount(); ok {
		_spec.AddField(rewardcampaignuserstate.FieldGrantCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ClaimCount(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldClaimCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClaimCount(); ok {
		_spec.AddField(rewardcampaignuserstate.FieldClaimCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ControlGroup(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldControlGroup, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CurrentCycleKey(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldCurrentCycleKey, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rewardcampaignuserstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RewardCampaignUserStateUpdateOne is the builder for updating a single RewardCampaignUserState entity.
type RewardCampaignUserStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RewardCampaignUserStateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RewardCampaignUserStateUpdateOne) SetUpdatedAt(v time.Time) *RewardCampaignUserStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (_u *RewardCampaignUserStateUpdateOne) SetLastEvaluatedAt(v time.Time) *RewardCampaignUserStateUpdateOne {
	_u.mutation.SetLastEvaluatedAt(v)
	return _u
}

// SetNillableLastEvaluatedAt sets the "last_evaluated_at" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdateOne) SetNillableLastEvaluatedAt(v *time.Time) *RewardCampaignUserStateUpdateOne {
	if v != nil {
		_u.SetLastEvaluatedAt(*v)
	}
	return _u
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (_u *RewardCampaignUserStateUpdateOne) ClearLastEvaluatedAt() *RewardCampaignUserStateUpdateOne {
	_u.mutation.ClearLastEvaluatedAt()
	return _u
}

// SetLastWonAt sets the "last_won_at" field.
func (_u *RewardCampaignUserStateUpdateOne) SetLastWonAt(v time.Time) *RewardCampaignUserStateUpdateOne {
	_u.mutation.SetLastWonAt(v)
	return _u
}

// SetNillableLastWonAt sets the "last_won_at" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdateOne) SetNillableLastWonAt(v *time.Time) *RewardCampaignUserStateUpdateOne {
	if v != nil {
		_u.SetLastWonAt(*v)
	}
	return _u
}

// ClearLastWonAt clears the value of the "last_won_at" field.
func (_u *RewardCampaignUserStateUpdateOne) ClearLastWonAt() *RewardCampaignUserStateUpdateOne {
	_u.mutation.ClearLastWonAt()
	return _u
}

// SetLastGrantedAt sets the "last_granted_at" field.
func (_u *RewardCampaignUserStateUpdateOne) SetLastGrantedAt(v time.Time) *RewardCampaignUserStateUpdateOne {
	_u.mutation.SetLastGrantedAt(v)
	return _u
}

// SetNillableLastGrantedAt sets the "last_granted_at" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdateOne) SetNillableLastGrantedAt(v *time.Time) *RewardCampaignUserStateUpdateOne {
	if v != nil {
		_u.SetLastGrantedAt(*v)
	}
	return _u
}

// ClearLastGrantedAt clears the value of the "last_granted_at" field.
func (_u *RewardCampaignUserStateUpdateOne) ClearLastGrantedAt() *RewardCampaignUserStateUpdateOne {
	_u.mutation.ClearLastGrantedAt()
	return _u
}

// SetLastClaimedAt sets the "last_claimed_at" field.
func (_u *RewardCampaignUserStateUpdateOne) SetLastClaimedAt(v time.Time) *RewardCampaignUserStateUpdateOne {
	_u.mutation.SetLastClaimedAt(v)
	return _u
}

// SetNillableLastClaimedAt sets the "last_claimed_at" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdateOne) SetNillableLastClaimedAt(v *time.Time) *RewardCampaignUserStateUpdateOne {
	if v != nil {
		_u.SetLastClaimedAt(*v)
	}
	return _u
}

// ClearLastClaimedAt clears the value of the "last_claimed_at" field.
func (_u *RewardCampaignUserStateUpdateOne) ClearLastClaimedAt() *RewardCampaignUserStateUpdateOne {
	_u.mutation.ClearLastClaimedAt()
	return _u
}

// SetNextEligibleAt sets the "next_eligible_at" field.
func (_u *RewardCampaignUserStateUpdateOne) SetNextEligibleAt(v time.Time) *RewardCampaignUserStateUpdateOne {
	_u.mutation.SetNextEligibleAt(v)
	return _u
}

// SetNillableNextEligibleAt sets the "next_eligible_at" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdateOne) SetNillableNextEligibleAt(v *time.Time) *RewardCampaignUserStateUpdateOne {
	if v != nil {
		_u.SetNextEligibleAt(*v)
	}
	return _u
}

// ClearNextEligibleAt clears the value of the "next_eligible_at" field.
func (_u *RewardCampaignUserStateUpdateOne) ClearNextEligibleAt() *RewardCampaignUserStateUpdateOne {
	_u.mutation.ClearNextEligibleAt()
	return _u
}

// SetEvaluationCount sets the "evaluation_count" field.
func (_u *RewardCampaignUserStateUpdateOne) SetEvaluationCount(v int64) *RewardCampaignUserStateUpdateOne {
	_u.mutation.ResetEvaluationCount()
	_u.mutation.SetEvaluationCount(v)
	return _u
}

// SetNillableEvaluationCount sets the "evaluation_count" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdateOne) SetNillableEvaluationCount(v *int64) *RewardCampaignUserStateUpdateOne {
	if v != nil {
		_u.SetEvaluationCount(*v)
	}
	return _u
}

// AddEvaluationCount adds value to the "evaluation_count" field.
func (_u *RewardCampaignUserStateUpdateOne) AddEvaluationCount(v int64) *RewardCampaignUserStateUpdateOne {
	_u.mutation.AddEvaluationCount(v)
	return _u
}

// SetWinCount sets the "win_count" field.
func (_u *RewardCampaignUserStateUpdateOne) SetWinCount(v int64) *RewardCampaignUserStateUpdateOne {
	_u.mutation.ResetWinCount()
	_u.mutation.SetWinCount(v)
	return _u
}

// SetNillableWinCount sets the "win_count" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdateOne) SetNillableWinCount(v *int64) *RewardCampaignUserStateUpdateOne {
	if v != nil {
		_u.SetWinCount(*v)
	}
	return _u
}

// AddWinCount adds value to the "win_count" field.
func (_u *RewardCampaignUserStateUpdateOne) AddWinCount(v int64) *RewardCampaignUserStateUpdateOne {
	_u.mutation.AddWinCount(v)
	return _u
}

// SetGrantCount sets the "grant_count" field.
func (_u *RewardCampaignUserStateUpdateOne) SetGrantCount(v int64) *RewardCampaignUserStateUpdateOne {
	_u.mutation.ResetGrantCount()
	_u.mutation.SetGrantCount(v)
	return _u
}

// SetNillableGrantCount sets the "grant_count" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdateOne) SetNillableGrantCount(v *int64) *RewardCampaignUserStateUpdateOne {
	if v != nil {
		_u.SetGrantCount(*v)
	}
	return _u
}

// AddGrantCount adds value to the "grant_count" field.
func (_u *RewardCampaignUserStateUpdateOne) AddGrantCount(v int64) *RewardCampaignUserStateUpdateOne {
	_u.mutation.AddGrantCount(v)
	return _u
}

// SetClaimCount sets the "claim_count" field.
func (_u *RewardCampaignUserStateUpdateOne) SetClaimCount(v int64) *RewardCampaignUserStateUpdateOne {
	_u.mutation.ResetClaimCount()
	_u.mutation.SetClaimCount(v)
	return _u
}

// SetNillableClaimCount sets the "claim_count" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdateOne) SetNillableClaimCount(v *int64) *RewardCampaignUserStateUpdateOne {
	if v != nil {
		_u.SetClaimCount(*v)
	}
	return _u
}

// AddClaimCount adds value to the "claim_count" field.
func (_u *RewardCampaignUserStateUpdateOne) AddClaimCount(v int64) *RewardCampaignUserStateUpdateOne {
	_u.mutation.AddClaimCount(v)
	return _u
}

// SetControlGroup sets the "control_group" field.
func (_u *RewardCampaignUserStateUpdateOne) SetControlGroup(v bool) *RewardCampaignUserStateUpdateOne {
	_u.mutation.SetControlGroup(v)
	return _u
}

// SetNillableControlGroup sets the "control_group" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdateOne) SetNillableControlGroup(v *bool) *RewardCampaignUserStateUpdateOne {
	if v != nil {
		_u.SetControlGroup(*v)
	}
	return _u
}

// SetCurrentCycleKey sets the "current_cycle_key" field.
func (_u *RewardCampaignUserStateUpdateOne) SetCurrentCycleKey(v string) *RewardCampaignUserStateUpdateOne {
	_u.mutation.SetCurrentCycleKey(v)
	return _u
}

// SetNillableCurrentCycleKey sets the "current_cycle_key" field if the given value is not nil.
func (_u *RewardCampaignUserStateUpdateOne) SetNillableCurrentCycleKey(v *string) *RewardCampaignUserStateUpdateOne {
	if v != nil {
		_u.SetCurrentCycleKey(*v)
	}
	return _u
}

// Mutation returns the RewardCampaignUserStateMutation object of the builder.
func (_u *RewardCampaignUserStateUpdateOne) Mutation() *RewardCampaignUserStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the RewardCampaignUserStateUpdate builder.
func (_u *RewardCampaignUserStateUpdateOne) Where(ps ...predicate.RewardCampaignUserState) *RewardCampaignUserStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RewardCampaignUserStateUpdateOne) Select(field string, fields ...string) *RewardCampaignUserStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RewardCampaignUserState entity.
func (_u *RewardCampaignUserStateUpdateOne) Save(ctx context.Context) (*RewardCampaignUserState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RewardCampaignUserStateUpdateOne) SaveX(ctx context.Context) *RewardCampaignUserState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RewardCampaignUserStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RewardCampaignUserStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RewardCampaignUserStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rewardcampaignuserstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RewardCampaignUserStateUpdateOne) check() error {
	if v, ok := _u.mutation.EvaluationCount(); ok {
		if err := rewardcampaignuserstate.EvaluationCountValidator(v); err != nil {
			return &ValidationError{Name: "evaluation_count", err: fmt.Errorf(`ent: validator failed for field "RewardCampaignUserState.evaluation_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WinCount(); ok {
		if err := rewardcampaignuserstate.WinCountValidator(v); err != nil {
			return &ValidationError{Name: "win_count", err: fmt.Errorf(`ent: validator failed for field "RewardCampaignUserState.win_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GrantCount(); ok {
		if err := rewardcampaignuserstate.GrantCountValidator(v); err != nil {
			return &ValidationError{Name: "grant_count", err: fmt.Errorf(`ent: validator failed for field "RewardCampaignUserState.grant_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClaimCount(); ok {
		if err := rewardcampaignuserstate.ClaimCountValidator(v); err != nil {
			return &ValidationError{Name: "claim_count", err: fmt.Errorf(`ent: validator failed for field "RewardCampaignUserState.claim_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentCycleKey(); ok {
		if err := rewardcampaignuserstate.CurrentCycleKeyValidator(v); err != nil {
			return &ValidationError{Name: "current_cycle_key", err: fmt.Errorf(`ent: validator failed for field "RewardCampaignUserState.current_cycle_key": %w`, err)}
		}
	}
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RewardCampaignUserState.campaign"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RewardCampaignUserState.user"`)
	}
	return nil
}

func (_u *RewardCampaignUserStateUpdateOne) sqlSave(ctx context.Context) (_node *RewardCampaignUserState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rewardcampaignuserstate.Table, rewardcampaignuserstate.Columns, sqlgraph.NewFieldSpec(rewardcampaignuserstate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RewardCampaignUserState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rewardcampaignuserstate.FieldID)
		for _, f := range fields {
			if !rewardcampaignuserstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rewardcampaignuserstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastEvaluatedAt(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldLastEvaluatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastEvaluatedAtCleared() {
		_spec.ClearField(rewardcampaignuserstate.FieldLastEvaluatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastWonAt(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldLastWonAt, field.TypeTime, value)
	}
	if _u.mutation.LastWonAtCleared() {
		_spec.ClearField(rewardcampaignuserstate.FieldLastWonAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastGrantedAt(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldLastGrantedAt, field.TypeTime, value)
	}
	if _u.mutation.LastGrantedAtCleared() {
		_spec.ClearField(rewardcampaignuserstate.FieldLastGrantedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastClaimedAt(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldLastClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.LastClaimedAtCleared() {
		_spec.ClearField(rewardcampaignuserstate.FieldLastClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextEligibleAt(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldNextEligibleAt, field.TypeTime, value)
	}
	if _u.mutation.NextEligibleAtCleared() {
		_spec.ClearField(rewardcampaignuserstate.FieldNextEligibleAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EvaluationCount(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldEvaluationCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEvaluationCount(); ok {
		_spec.AddField(rewardcampaignuserstate.FieldEvaluationCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WinCount(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldWinCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWinCount(); ok {
		_spec.AddField(rewardcampaignuserstate.FieldWinCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GrantCount(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldGrantCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGrantCount(); ok {
		_spec.AddField(rewardcampaignuserstate.FieldGrantCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ClaimCount(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldClaimCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClaimCount(); ok {
		_spec.AddField(rewardcampaignuserstate.FieldClaimCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ControlGroup(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldControlGroup, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CurrentCycleKey(); ok {
		_spec.SetField(rewardcampaignuserstate.FieldCurrentCycleKey, field.TypeString, value)
	}
	_node = &RewardCampaignUserState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rewardcampaignuserstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
