// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rewardskin"
	"github.com/Wei-Shaw/sub2api/ent/userrewardgrant"
)

// RewardSkinUpdate is the builder for updating RewardSkin entities.
type RewardSkinUpdate struct {
	config
	hooks    []Hook
	mutation *RewardSkinMutation
}

// Where appends a list predicates to the RewardSkinUpdate builder.
func (_u *RewardSkinUpdate) Where(ps ...predicate.RewardSkin) *RewardSkinUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RewardSkinUpdate) SetUpdatedAt(v time.Time) *RewardSkinUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *RewardSkinUpdate) SetName(v string) *RewardSkinUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RewardSkinUpdate) SetNillableName(v *string) *RewardSkinUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RewardSkinUpdate) SetDescription(v string) *RewardSkinUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RewardSkinUpdate) SetNillableDescription(v *string) *RewardSkinUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAltText sets the "alt_text" field.
func (_u *RewardSkinUpdate) SetAltText(v string) *RewardSkinUpdate {
	_u.mutation.SetAltText(v)
	return _u
}

// SetNillableAltText sets the "alt_text" field if the given value is not nil.
func (_u *RewardSkinUpdate) SetNillableAltText(v *string) *RewardSkinUpdate {
	if v != nil {
		_u.SetAltText(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RewardSkinUpdate) SetStatus(v string) *RewardSkinUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RewardSkinUpdate) SetNillableStatus(v *string) *RewardSkinUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *RewardSkinUpdate) SetUpdatedBy(v int64) *RewardSkinUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *RewardSkinUpdate) SetNillableUpdatedBy(v *int64) *RewardSkinUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *RewardSkinUpdate) AddUpdatedBy(v int64) *RewardSkinUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *RewardSkinUpdate) ClearUpdatedBy() *RewardSkinUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *RewardSkinUpdate) SetArchivedAt(v time.Time) *RewardSkinUpdate {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *RewardSkinUpdate) SetNillableArchivedAt(v *time.Time) *RewardSkinUpdate {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *RewardSkinUpdate) ClearArchivedAt() *RewardSkinUpdate {
	_u.mutation.ClearArchivedAt()
	return _u
}

// AddGrantIDs adds the "grants" edge to the UserRewardGrant entity by IDs.
func (_u *RewardSkinUpdate) AddGrantIDs(ids ...int64) *RewardSkinUpdate {
	_u.mutation.AddGrantIDs(ids...)
	return _u
}

// AddGrants adds the "grants" edges to the UserRewardGrant entity.
func (_u *RewardSkinUpdate) AddGrants(v ...*UserRewardGrant) *RewardSkinUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGrantIDs(ids...)
}

// Mutation returns the RewardSkinMutation object of the builder.
func (_u *RewardSkinUpdate) Mutation() *RewardSkinMutation {
	return _u.mutation
}

// ClearGrants clears all "grants" edges to the UserRewardGrant entity.
func (_u *RewardSkinUpdate) ClearGrants() *RewardSkinUpdate {
	_u.mutation.ClearGrants()
	return _u
}

// RemoveGrantIDs removes the "grants" edge to UserRewardGrant entities by IDs.
func (_u *RewardSkinUpdate) RemoveGrantIDs(ids ...int64) *RewardSkinUpdate {
	_u.mutation.RemoveGrantIDs(ids...)
	return _u
}

// RemoveGrants removes "grants" edges to UserRewardGrant entities.
func (_u *RewardSkinUpdate) RemoveGrants(v ...*UserRewardGrant) *RewardSkinUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGrantIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RewardSkinUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RewardSkinUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RewardSkinUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RewardSkinUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RewardSkinUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rewardskin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RewardSkinUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rewardskin.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RewardSkin.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AltText(); ok {
		if err := rewardskin.AltTextValidator(v); err != nil {
			return &ValidationError{Name: "alt_text", err: fmt.Errorf(`ent: validator failed for field "RewardSkin.alt_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rewardskin.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RewardSkin.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RewardSkinUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rewardskin.Table, rewardskin.Columns, sqlgraph.NewFieldSpec(rewardskin.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rewardskin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rewardskin.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rewardskin.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.AltText(); ok {
		_spec.SetField(rewardskin.FieldAltText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rewardskin.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(rewardskin.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(rewardskin.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(rewardskin.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(rewardskin.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(rewardskin.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(rewardskin.FieldArchivedAt, field.TypeTime)
	}
	if _u.mutation.GrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardskin.GrantsTable,
			Columns: []string{rewardskin.GrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGrantsIDs(); len(nodes) > 0 && !_u.mutation.GrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardskin.GrantsTable,
			Columns: []string{rewardskin.GrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardskin.GrantsTable,
			Columns: []string{rewardskin.GrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rewardskin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RewardSkinUpdateOne is the builder for updating a single RewardSkin entity.
type RewardSkinUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RewardSkinMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RewardSkinUpdateOne) SetUpdatedAt(v time.Time) *RewardSkinUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *RewardSkinUpdateOne) SetName(v string) *RewardSkinUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RewardSkinUpdateOne) SetNillableName(v *string) *RewardSkinUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RewardSkinUpdateOne) SetDescription(v string) *RewardSkinUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RewardSkinUpdateOne) SetNillableDescription(v *string) *RewardSkinUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAltText sets the "alt_text" field.
func (_u *RewardSkinUpdateOne) SetAltText(v string) *RewardSkinUpdateOne {
	_u.mutation.SetAltText(v)
	return _u
}

// SetNillableAltText sets the "alt_text" field if the given value is not nil.
func (_u *RewardSkinUpdateOne) SetNillableAltText(v *string) *RewardSkinUpdateOne {
	if v != nil {
		_u.SetAltText(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RewardSkinUpdateOne) SetStatus(v string) *RewardSkinUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RewardSkinUpdateOne) SetNillableStatus(v *string) *RewardSkinUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *RewardSkinUpdateOne) SetUpdatedBy(v int64) *RewardSkinUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *RewardSkinUpdateOne) SetNillableUpdatedBy(v *int64) *RewardSkinUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *RewardSkinUpdateOne) AddUpdatedBy(v int64) *RewardSkinUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *RewardSkinUpdateOne) ClearUpdatedBy() *RewardSkinUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *RewardSkinUpdateOne) SetArchivedAt(v time.Time) *RewardSkinUpdateOne {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *RewardSkinUpdateOne) SetNillableArchivedAt(v *time.Time) *RewardSkinUpdateOne {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *RewardSkinUpdateOne) ClearArchivedAt() *RewardSkinUpdateOne {
	_u.mutation.ClearArchivedAt()
	return _u
}

// AddGrantIDs adds the "grants" edge to the UserRewardGrant entity by IDs.
func (_u *RewardSkinUpdateOne) AddGrantIDs(ids ...int64) *RewardSkinUpdateOne {
	_u.mutation.AddGrantIDs(ids...)
	return _u
}

// AddGrants adds the "grants" edges to the UserRewardGrant entity.
func (_u *RewardSkinUpdateOne) AddGrants(v ...*UserRewardGrant) *RewardSkinUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGrantIDs(ids...)
}

// Mutation returns the RewardSkinMutation object of the builder.
func (_u *RewardSkinUpdateOne) Mutation() *RewardSkinMutation {
	return _u.mutation
}

// ClearGrants clears all "grants" edges to the UserRewardGrant entity.
func (_u *RewardSkinUpdateOne) ClearGrants() *RewardSkinUpdateOne {
	_u.mutation.ClearGrants()
	return _u
}

// RemoveGrantIDs removes the "grants" edge to UserRewardGrant entities by IDs.
func (_u *RewardSkinUpdateOne) RemoveGrantIDs(ids ...int64) *RewardSkinUpdateOne {
	_u.mutation.RemoveGrantIDs(ids...)
	return _u
}

// RemoveGrants removes "grants" edges to UserRewardGrant entities.
func (_u *RewardSkinUpdateOne) RemoveGrants(v ...*UserRewardGrant) *RewardSkinUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGrantIDs(ids...)
}

// Where appends a list predicates to the RewardSkinUpdate builder.
func (_u *RewardSkinUpdateOne) Where(ps ...predicate.RewardSkin) *RewardSkinUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RewardSkinUpdateOne) Select(field string, fields ...string) *RewardSkinUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RewardSkin entity.
func (_u *RewardSkinUpdateOne) Save(ctx context.Context) (*RewardSkin, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RewardSkinUpdateOne) SaveX(ctx context.Context) *RewardSkin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RewardSkinUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RewardSkinUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RewardSkinUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rewardskin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RewardSkinUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rewardskin.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RewardSkin.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AltText(); ok {
		if err := rewardskin.AltTextValidator(v); err != nil {
			return &ValidationError{Name: "alt_text", err: fmt.Errorf(`ent: validator failed for field "RewardSkin.alt_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rewardskin.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RewardSkin.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RewardSkinUpdateOne) sqlSave(ctx context.Context) (_node *RewardSkin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rewardskin.Table, rewardskin.Columns, sqlgraph.NewFieldSpec(rewardskin.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RewardSkin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rewardskin.FieldID)
		for _, f := range fields {
			if !rewardskin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rewardskin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rewardskin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rewardskin.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rewardskin.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.AltText(); ok {
		_spec.SetField(rewardskin.FieldAltText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rewardskin.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(rewardskin.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(rewardskin.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(rewardskin.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(rewardskin.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(rewardskin.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(rewardskin.FieldArchivedAt, field.TypeTime)
	}
	if _u.mutation.GrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardskin.GrantsTable,
			Columns: []string{rewardskin.GrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGrantsIDs(); len(nodes) > 0 && !_u.mutation.GrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardskin.GrantsTable,
			Columns: []string{rewardskin.GrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardskin.GrantsTable,
			Columns: []string{rewardskin.GrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RewardSkin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rewardskin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
