// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rewardcampaign"
	"github.com/Wei-Shaw/sub2api/ent/rewardcampaignjob"
	"github.com/Wei-Shaw/sub2api/ent/rewardcampaignversion"
	"github.com/Wei-Shaw/sub2api/ent/userrewardgrant"
)

// RewardCampaignVersionUpdate is the builder for updating RewardCampaignVersion entities.
type RewardCampaignVersionUpdate struct {
	config
	hooks    []Hook
	mutation *RewardCampaignVersionMutation
}

// Where appends a list predicates to the RewardCampaignVersionUpdate builder.
func (_u *RewardCampaignVersionUpdate) Where(ps ...predicate.RewardCampaignVersion) *RewardCampaignVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// AddCurrentForCampaignIDs adds the "current_for_campaigns" edge to the RewardCampaign entity by IDs.
func (_u *RewardCampaignVersionUpdate) AddCurrentForCampaignIDs(ids ...int64) *RewardCampaignVersionUpdate {
	_u.mutation.AddCurrentForCampaignIDs(ids...)
	return _u
}

// AddCurrentForCampaigns adds the "current_for_campaigns" edges to the RewardCampaign entity.
func (_u *RewardCampaignVersionUpdate) AddCurrentForCampaigns(v ...*RewardCampaign) *RewardCampaignVersionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCurrentForCampaignIDs(ids...)
}

// AddGrantIDs adds the "grants" edge to the UserRewardGrant entity by IDs.
func (_u *RewardCampaignVersionUpdate) AddGrantIDs(ids ...int64) *RewardCampaignVersionUpdate {
	_u.mutation.AddGrantIDs(ids...)
	return _u
}

// AddGrants adds the "grants" edges to the UserRewardGrant entity.
func (_u *RewardCampaignVersionUpdate) AddGrants(v ...*UserRewardGrant) *RewardCampaignVersionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGrantIDs(ids...)
}

// AddJobIDs adds the "jobs" edge to the RewardCampaignJob entity by IDs.
func (_u *RewardCampaignVersionUpdate) AddJobIDs(ids ...int64) *RewardCampaignVersionUpdate {
	_u.mutation.AddJobIDs(ids...)
	return _u
}

// AddJobs adds the "jobs" edges to the RewardCampaignJob entity.
func (_u *RewardCampaignVersionUpdate) AddJobs(v ...*RewardCampaignJob) *RewardCampaignVersionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJobIDs(ids...)
}

// Mutation returns the RewardCampaignVersionMutation object of the builder.
func (_u *RewardCampaignVersionUpdate) Mutation() *RewardCampaignVersionMutation {
	return _u.mutation
}

// ClearCurrentForCampaigns clears all "current_for_campaigns" edges to the RewardCampaign entity.
func (_u *RewardCampaignVersionUpdate) ClearCurrentForCampaigns() *RewardCampaignVersionUpdate {
	_u.mutation.ClearCurrentForCampaigns()
	return _u
}

// RemoveCurrentForCampaignIDs removes the "current_for_campaigns" edge to RewardCampaign entities by IDs.
func (_u *RewardCampaignVersionUpdate) RemoveCurrentForCampaignIDs(ids ...int64) *RewardCampaignVersionUpdate {
	_u.mutation.RemoveCurrentForCampaignIDs(ids...)
	return _u
}

// RemoveCurrentForCampaigns removes "current_for_campaigns" edges to RewardCampaign entities.
func (_u *RewardCampaignVersionUpdate) RemoveCurrentForCampaigns(v ...*RewardCampaign) *RewardCampaignVersionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCurrentForCampaignIDs(ids...)
}

// ClearGrants clears all "grants" edges to the UserRewardGrant entity.
func (_u *RewardCampaignVersionUpdate) ClearGrants() *RewardCampaignVersionUpdate {
	_u.mutation.ClearGrants()
	return _u
}

// RemoveGrantIDs removes the "grants" edge to UserRewardGrant entities by IDs.
func (_u *RewardCampaignVersionUpdate) RemoveGrantIDs(ids ...int64) *RewardCampaignVersionUpdate {
	_u.mutation.RemoveGrantIDs(ids...)
	return _u
}

// RemoveGrants removes "grants" edges to UserRewardGrant entities.
func (_u *RewardCampaignVersionUpdate) RemoveGrants(v ...*UserRewardGrant) *RewardCampaignVersionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGrantIDs(ids...)
}

// ClearJobs clears all "jobs" edges to the RewardCampaignJob entity.
func (_u *RewardCampaignVersionUpdate) ClearJobs() *RewardCampaignVersionUpdate {
	_u.mutation.ClearJobs()
	return _u
}

// RemoveJobIDs removes the "jobs" edge to RewardCampaignJob entities by IDs.
func (_u *RewardCampaignVersionUpdate) RemoveJobIDs(ids ...int64) *RewardCampaignVersionUpdate {
	_u.mutation.RemoveJobIDs(ids...)
	return _u
}

// RemoveJobs removes "jobs" edges to RewardCampaignJob entities.
func (_u *RewardCampaignVersionUpdate) RemoveJobs(v ...*RewardCampaignJob) *RewardCampaignVersionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJobIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RewardCampaignVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RewardCampaignVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RewardCampaignVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RewardCampaignVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RewardCampaignVersionUpdate) check() error {
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RewardCampaignVersion.campaign"`)
	}
	return nil
}

func (_u *RewardCampaignVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rewardcampaignversion.Table, rewardcampaignversion.Columns, sqlgraph.NewFieldSpec(rewardcampaignversion.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(rewardcampaignversion.FieldCreatedBy, field.TypeInt64)
	}
	if _u.mutation.CurrentForCampaignsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.CurrentForCampaignsTable,
			Columns: []string{rewardcampaignversion.CurrentForCampaignsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCurrentForCampaignsIDs(); len(nodes) > 0 && !_u.mutation.CurrentForCampaignsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.CurrentForCampaignsTable,
			Columns: []string{rewardcampaignversion.CurrentForCampaignsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentForCampaignsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.CurrentForCampaignsTable,
			Columns: []string{rewardcampaignversion.CurrentForCampaignsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.GrantsTable,
			Columns: []string{rewardcampaignversion.GrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGrantsIDs(); len(nodes) > 0 && !_u.mutation.GrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.GrantsTable,
			Columns: []string{rewardcampaignversion.GrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.GrantsTable,
			Columns: []string{rewardcampaignversion.GrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.JobsTable,
			Columns: []string{rewardcampaignversion.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaignjob.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJobsIDs(); len(nodes) > 0 && !_u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.JobsTable,
			Columns: []string{rewardcampaignversion.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaignjob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.JobsTable,
			Columns: []string{rewardcampaignversion.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaignjob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rewardcampaignversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RewardCampaignVersionUpdateOne is the builder for updating a single RewardCampaignVersion entity.
type RewardCampaignVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RewardCampaignVersionMutation
}

// AddCurrentForCampaignIDs adds the "current_for_campaigns" edge to the RewardCampaign entity by IDs.
func (_u *RewardCampaignVersionUpdateOne) AddCurrentForCampaignIDs(ids ...int64) *RewardCampaignVersionUpdateOne {
	_u.mutation.AddCurrentForCampaignIDs(ids...)
	return _u
}

// AddCurrentForCampaigns adds the "current_for_campaigns" edges to the RewardCampaign entity.
func (_u *RewardCampaignVersionUpdateOne) AddCurrentForCampaigns(v ...*RewardCampaign) *RewardCampaignVersionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCurrentForCampaignIDs(ids...)
}

// AddGrantIDs adds the "grants" edge to the UserRewardGrant entity by IDs.
func (_u *RewardCampaignVersionUpdateOne) AddGrantIDs(ids ...int64) *RewardCampaignVersionUpdateOne {
	_u.mutation.AddGrantIDs(ids...)
	return _u
}

// AddGrants adds the "grants" edges to the UserRewardGrant entity.
func (_u *RewardCampaignVersionUpdateOne) AddGrants(v ...*UserRewardGrant) *RewardCampaignVersionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGrantIDs(ids...)
}

// AddJobIDs adds the "jobs" edge to the RewardCampaignJob entity by IDs.
func (_u *RewardCampaignVersionUpdateOne) AddJobIDs(ids ...int64) *RewardCampaignVersionUpdateOne {
	_u.mutation.AddJobIDs(ids...)
	return _u
}

// AddJobs adds the "jobs" edges to the RewardCampaignJob entity.
func (_u *RewardCampaignVersionUpdateOne) AddJobs(v ...*RewardCampaignJob) *RewardCampaignVersionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJobIDs(ids...)
}

// Mutation returns the RewardCampaignVersionMutation object of the builder.
func (_u *RewardCampaignVersionUpdateOne) Mutation() *RewardCampaignVersionMutation {
	return _u.mutation
}

// ClearCurrentForCampaigns clears all "current_for_campaigns" edges to the RewardCampaign entity.
func (_u *RewardCampaignVersionUpdateOne) ClearCurrentForCampaigns() *RewardCampaignVersionUpdateOne {
	_u.mutation.ClearCurrentForCampaigns()
	return _u
}

// RemoveCurrentForCampaignIDs removes the "current_for_campaigns" edge to RewardCampaign entities by IDs.
func (_u *RewardCampaignVersionUpdateOne) RemoveCurrentForCampaignIDs(ids ...int64) *RewardCampaignVersionUpdateOne {
	_u.mutation.RemoveCurrentForCampaignIDs(ids...)
	return _u
}

// RemoveCurrentForCampaigns removes "current_for_campaigns" edges to RewardCampaign entities.
func (_u *RewardCampaignVersionUpdateOne) RemoveCurrentForCampaigns(v ...*RewardCampaign) *RewardCampaignVersionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCurrentForCampaignIDs(ids...)
}

// ClearGrants clears all "grants" edges to the UserRewardGrant entity.
func (_u *RewardCampaignVersionUpdateOne) ClearGrants() *RewardCampaignVersionUpdateOne {
	_u.mutation.ClearGrants()
	return _u
}

// RemoveGrantIDs removes the "grants" edge to UserRewardGrant entities by IDs.
func (_u *RewardCampaignVersionUpdateOne) RemoveGrantIDs(ids ...int64) *RewardCampaignVersionUpdateOne {
	_u.mutation.RemoveGrantIDs(ids...)
	return _u
}

// RemoveGrants removes "grants" edges to UserRewardGrant entities.
func (_u *RewardCampaignVersionUpdateOne) RemoveGrants(v ...*UserRewardGrant) *RewardCampaignVersionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGrantIDs(ids...)
}

// ClearJobs clears all "jobs" edges to the RewardCampaignJob entity.
func (_u *RewardCampaignVersionUpdateOne) ClearJobs() *RewardCampaignVersionUpdateOne {
	_u.mutation.ClearJobs()
	return _u
}

// RemoveJobIDs removes the "jobs" edge to RewardCampaignJob entities by IDs.
func (_u *RewardCampaignVersionUpdateOne) RemoveJobIDs(ids ...int64) *RewardCampaignVersionUpdateOne {
	_u.mutation.RemoveJobIDs(ids...)
	return _u
}

// RemoveJobs removes "jobs" edges to RewardCampaignJob entities.
func (_u *RewardCampaignVersionUpdateOne) RemoveJobs(v ...*RewardCampaignJob) *RewardCampaignVersionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJobIDs(ids...)
}

// Where appends a list predicates to the RewardCampaignVersionUpdate builder.
func (_u *RewardCampaignVersionUpdateOne) Where(ps ...predicate.RewardCampaignVersion) *RewardCampaignVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RewardCampaignVersionUpdateOne) Select(field string, fields ...string) *RewardCampaignVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RewardCampaignVersion entity.
func (_u *RewardCampaignVersionUpdateOne) Save(ctx context.Context) (*RewardCampaignVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RewardCampaignVersionUpdateOne) SaveX(ctx context.Context) *RewardCampaignVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RewardCampaignVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RewardCampaignVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RewardCampaignVersionUpdateOne) check() error {
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RewardCampaignVersion.campaign"`)
	}
	return nil
}

func (_u *RewardCampaignVersionUpdateOne) sqlSave(ctx context.Context) (_node *RewardCampaignVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rewardcampaignversion.Table, rewardcampaignversion.Columns, sqlgraph.NewFieldSpec(rewardcampaignversion.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RewardCampaignVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rewardcampaignversion.FieldID)
		for _, f := range fields {
			if !rewardcampaignversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rewardcampaignversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(rewardcampaignversion.FieldCreatedBy, field.TypeInt64)
	}
	if _u.mutation.CurrentForCampaignsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.CurrentForCampaignsTable,
			Columns: []string{rewardcampaignversion.CurrentForCampaignsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCurrentForCampaignsIDs(); len(nodes) > 0 && !_u.mutation.CurrentForCampaignsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.CurrentForCampaignsTable,
			Columns: []string{rewardcampaignversion.CurrentForCampaignsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentForCampaignsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.CurrentForCampaignsTable,
			Columns: []string{rewardcampaignversion.CurrentForCampaignsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.GrantsTable,
			Columns: []string{rewardcampaignversion.GrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGrantsIDs(); len(nodes) > 0 && !_u.mutation.GrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.GrantsTable,
			Columns: []string{rewardcampaignversion.GrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.GrantsTable,
			Columns: []string{rewardcampaignversion.GrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.JobsTable,
			Columns: []string{rewardcampaignversion.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaignjob.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJobsIDs(); len(nodes) > 0 && !_u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.JobsTable,
			Columns: []string{rewardcampaignversion.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaignjob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rewardcampaignversion.JobsTable,
			Columns: []string{rewardcampaignversion.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaignjob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RewardCampaignVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rewardcampaignversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
