// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rewardcampaign"
	"github.com/Wei-Shaw/sub2api/ent/rewardcampaignjob"
	"github.com/Wei-Shaw/sub2api/ent/rewardcampaignversion"
	"github.com/Wei-Shaw/sub2api/ent/userrewardgrant"
)

// RewardCampaignVersionQuery is the builder for querying RewardCampaignVersion entities.
type RewardCampaignVersionQuery struct {
	config
	ctx                     *QueryContext
	order                   []rewardcampaignversion.OrderOption
	inters                  []Interceptor
	predicates              []predicate.RewardCampaignVersion
	withCampaign            *RewardCampaignQuery
	withCurrentForCampaigns *RewardCampaignQuery
	withGrants              *UserRewardGrantQuery
	withJobs                *RewardCampaignJobQuery
	modifiers               []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RewardCampaignVersionQuery builder.
func (_q *RewardCampaignVersionQuery) Where(ps ...predicate.RewardCampaignVersion) *RewardCampaignVersionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RewardCampaignVersionQuery) Limit(limit int) *RewardCampaignVersionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RewardCampaignVersionQuery) Offset(offset int) *RewardCampaignVersionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RewardCampaignVersionQuery) Unique(unique bool) *RewardCampaignVersionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RewardCampaignVersionQuery) Order(o ...rewardcampaignversion.OrderOption) *RewardCampaignVersionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCampaign chains the current query on the "campaign" edge.
func (_q *RewardCampaignVersionQuery) QueryCampaign() *RewardCampaignQuery {
	query := (&RewardCampaignClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rewardcampaignversion.Table, rewardcampaignversion.FieldID, selector),
			sqlgraph.To(rewardcampaign.Table, rewardcampaign.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, rewardcampaignversion.CampaignTable, rewardcampaignversion.CampaignColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCurrentForCampaigns chains the current query on the "current_for_campaigns" edge.
func (_q *RewardCampaignVersionQuery) QueryCurrentForCampaigns() *RewardCampaignQuery {
	query := (&RewardCampaignClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rewardcampaignversion.Table, rewardcampaignversion.FieldID, selector),
			sqlgraph.To(rewardcampaign.Table, rewardcampaign.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, rewardcampaignversion.CurrentForCampaignsTable, rewardcampaignversion.CurrentForCampaignsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGrants chains the current query on the "grants" edge.
func (_q *RewardCampaignVersionQuery) QueryGrants() *UserRewardGrantQuery {
	query := (&UserRewardGrantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rewardcampaignversion.Table, rewardcampaignversion.FieldID, selector),
			sqlgraph.To(userrewardgrant.Table, userrewardgrant.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, rewardcampaignversion.GrantsTable, rewardcampaignversion.GrantsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryJobs chains the current query on the "jobs" edge.
func (_q *RewardCampaignVersionQuery) QueryJobs() *RewardCampaignJobQuery {
	query := (&RewardCampaignJobClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rewardcampaignversion.Table, rewardcampaignversion.FieldID, selector),
			sqlgraph.To(rewardcampaignjob.Table, rewardcampaignjob.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, rewardcampaignversion.JobsTable, rewardcampaignversion.JobsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RewardCampaignVersion entity from the query.
// Returns a *NotFoundError when no RewardCampaignVersion was found.
func (_q *RewardCampaignVersionQuery) First(ctx context.Context) (*RewardCampaignVersion, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rewardcampaignversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RewardCampaignVersionQuery) FirstX(ctx context.Context) *RewardCampaignVersion {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RewardCampaignVersion ID from the query.
// Returns a *NotFoundError when no RewardCampaignVersion ID was found.
func (_q *RewardCampaignVersionQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rewardcampaignversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RewardCampaignVersionQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RewardCampaignVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RewardCampaignVersion entity is found.
// Returns a *NotFoundError when no RewardCampaignVersion entities are found.
func (_q *RewardCampaignVersionQuery) Only(ctx context.Context) (*RewardCampaignVersion, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rewardcampaignversion.Label}
	default:
		return nil, &NotSingularError{rewardcampaignversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RewardCampaignVersionQuery) OnlyX(ctx context.Context) *RewardCampaignVersion {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RewardCampaignVersion ID in the query.
// Returns a *NotSingularError when more than one RewardCampaignVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RewardCampaignVersionQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rewardcampaignversion.Label}
	default:
		err = &NotSingularError{rewardcampaignversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RewardCampaignVersionQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RewardCampaignVersions.
func (_q *RewardCampaignVersionQuery) All(ctx context.Context) ([]*RewardCampaignVersion, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RewardCampaignVersion, *RewardCampaignVersionQuery]()
	return withInterceptors[[]*RewardCampaignVersion](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RewardCampaignVersionQuery) AllX(ctx context.Context) []*RewardCampaignVersion {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RewardCampaignVersion IDs.
func (_q *RewardCampaignVersionQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(rewardcampaignversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RewardCampaignVersionQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RewardCampaignVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RewardCampaignVersionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RewardCampaignVersionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RewardCampaignVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RewardCampaignVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RewardCampaignVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RewardCampaignVersionQuery) Clone() *RewardCampaignVersionQuery {
	if _q == nil {
		return nil
	}
	return &RewardCampaignVersionQuery{
		config:                  _q.config,
		ctx:                     _q.ctx.Clone(),
		order:                   append([]rewardcampaignversion.OrderOption{}, _q.order...),
		inters:                  append([]Interceptor{}, _q.inters...),
		predicates:              append([]predicate.RewardCampaignVersion{}, _q.predicates...),
		withCampaign:            _q.withCampaign.Clone(),
		withCurrentForCampaigns: _q.withCurrentForCampaigns.Clone(),
		withGrants:              _q.withGrants.Clone(),
		withJobs:                _q.withJobs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCampaign tells the query-builder to eager-load the nodes that are connected to
// the "campaign" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RewardCampaignVersionQuery) WithCampaign(opts ...func(*RewardCampaignQuery)) *RewardCampaignVersionQuery {
	query := (&RewardCampaignClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCampaign = query
	return _q
}

// WithCurrentForCampaigns tells the query-builder to eager-load the nodes that are connected to
// the "current_for_campaigns" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RewardCampaignVersionQuery) WithCurrentForCampaigns(opts ...func(*RewardCampaignQuery)) *RewardCampaignVersionQuery {
	query := (&RewardCampaignClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCurrentForCampaigns = query
	return _q
}

// WithGrants tells the query-builder to eager-load the nodes that are connected to
// the "grants" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RewardCampaignVersionQuery) WithGrants(opts ...func(*UserRewardGrantQuery)) *RewardCampaignVersionQuery {
	query := (&UserRewardGrantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGrants = query
	return _q
}

// WithJobs tells the query-builder to eager-load the nodes that are connected to
// the "jobs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RewardCampaignVersionQuery) WithJobs(opts ...func(*RewardCampaignJobQuery)) *RewardCampaignVersionQuery {
	query := (&RewardCampaignJobClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withJobs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CampaignID int64 `json:"campaign_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RewardCampaignVersion.Query().
//		GroupBy(rewardcampaignversion.FieldCampaignID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RewardCampaignVersionQuery) GroupBy(field string, fields ...string) *RewardCampaignVersionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RewardCampaignVersionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = rewardcampaignversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CampaignID int64 `json:"campaign_id,omitempty"`
//	}
//
//	client.RewardCampaignVersion.Query().
//		Select(rewardcampaignversion.FieldCampaignID).
//		Scan(ctx, &v)
func (_q *RewardCampaignVersionQuery) Select(fields ...string) *RewardCampaignVersionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RewardCampaignVersionSelect{RewardCampaignVersionQuery: _q}
	sbuild.label = rewardcampaignversion.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RewardCampaignVersionSelect configured with the given aggregations.
func (_q *RewardCampaignVersionQuery) Aggregate(fns ...AggregateFunc) *RewardCampaignVersionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RewardCampaignVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !rewardcampaignversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RewardCampaignVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RewardCampaignVersion, error) {
	var (
		nodes       = []*RewardCampaignVersion{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withCampaign != nil,
			_q.withCurrentForCampaigns != nil,
			_q.withGrants != nil,
			_q.withJobs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RewardCampaignVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RewardCampaignVersion{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCampaign; query != nil {
		if err := _q.loadCampaign(ctx, query, nodes, nil,
			func(n *RewardCampaignVersion, e *RewardCampaign) { n.Edges.Campaign = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCurrentForCampaigns; query != nil {
		if err := _q.loadCurrentForCampaigns(ctx, query, nodes,
			func(n *RewardCampaignVersion) { n.Edges.CurrentForCampaigns = []*RewardCampaign{} },
			func(n *RewardCampaignVersion, e *RewardCampaign) {
				n.Edges.CurrentForCampaigns = append(n.Edges.CurrentForCampaigns, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withGrants; query != nil {
		if err := _q.loadGrants(ctx, query, nodes,
			func(n *RewardCampaignVersion) { n.Edges.Grants = []*UserRewardGrant{} },
			func(n *RewardCampaignVersion, e *UserRewardGrant) { n.Edges.Grants = append(n.Edges.Grants, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withJobs; query != nil {
		if err := _q.loadJobs(ctx, query, nodes,
			func(n *RewardCampaignVersion) { n.Edges.Jobs = []*RewardCampaignJob{} },
			func(n *RewardCampaignVersion, e *RewardCampaignJob) { n.Edges.Jobs = append(n.Edges.Jobs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RewardCampaignVersionQuery) loadCampaign(ctx context.Context, query *RewardCampaignQuery, nodes []*RewardCampaignVersion, init func(*RewardCampaignVersion), assign func(*RewardCampaignVersion, *RewardCampaign)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*RewardCampaignVersion)
	for i := range nodes {
		fk := nodes[i].CampaignID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(rewardcampaign.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "campaign_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RewardCampaignVersionQuery) loadCurrentForCampaigns(ctx context.Context, query *RewardCampaignQuery, nodes []*RewardCampaignVersion, init func(*RewardCampaignVersion), assign func(*RewardCampaignVersion, *RewardCampaign)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RewardCampaignVersion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rewardcampaign.FieldCurrentVersionID)
	}
	query.Where(predicate.RewardCampaign(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(rewardcampaignversion.CurrentForCampaignsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CurrentVersionID
		if fk == nil {
			return fmt.Errorf(`foreign-key "current_version_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "current_version_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RewardCampaignVersionQuery) loadGrants(ctx context.Context, query *UserRewardGrantQuery, nodes []*RewardCampaignVersion, init func(*RewardCampaignVersion), assign func(*RewardCampaignVersion, *UserRewardGrant)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RewardCampaignVersion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(userrewardgrant.FieldCampaignVersionID)
	}
	query.Where(predicate.UserRewardGrant(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(rewardcampaignversion.GrantsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CampaignVersionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "campaign_version_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RewardCampaignVersionQuery) loadJobs(ctx context.Context, query *RewardCampaignJobQuery, nodes []*RewardCampaignVersion, init func(*RewardCampaignVersion), assign func(*RewardCampaignVersion, *RewardCampaignJob)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RewardCampaignVersion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rewardcampaignjob.FieldCampaignVersionID)
	}
	query.Where(predicate.RewardCampaignJob(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(rewardcampaignversion.JobsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CampaignVersionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "campaign_version_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *RewardCampaignVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RewardCampaignVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rewardcampaignversion.Table, rewardcampaignversion.Columns, sqlgraph.NewFieldSpec(rewardcampaignversion.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rewardcampaignversion.FieldID)
		for i := range fields {
			if fields[i] != rewardcampaignversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCampaign != nil {
			_spec.Node.AddColumnOnce(rewardcampaignversion.FieldCampaignID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RewardCampaignVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(rewardcampaignversion.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = rewardcampaignversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *RewardCampaignVersionQuery) ForUpdate(opts ...sql.LockOption) *RewardCampaignVersionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *RewardCampaignVersionQuery) ForShare(opts ...sql.LockOption) *RewardCampaignVersionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// RewardCampaignVersionGroupBy is the group-by builder for RewardCampaignVersion entities.
type RewardCampaignVersionGroupBy struct {
	selector
	build *RewardCampaignVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RewardCampaignVersionGroupBy) Aggregate(fns ...AggregateFunc) *RewardCampaignVersionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RewardCampaignVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RewardCampaignVersionQuery, *RewardCampaignVersionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RewardCampaignVersionGroupBy) sqlScan(ctx context.Context, root *RewardCampaignVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RewardCampaignVersionSelect is the builder for selecting fields of RewardCampaignVersion entities.
type RewardCampaignVersionSelect struct {
	*RewardCampaignVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RewardCampaignVersionSelect) Aggregate(fns ...AggregateFunc) *RewardCampaignVersionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RewardCampaignVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RewardCampaignVersionQuery, *RewardCampaignVersionSelect](ctx, _s.RewardCampaignVersionQuery, _s, _s.inters, v)
}

func (_s *RewardCampaignVersionSelect) sqlScan(ctx context.Context, root *RewardCampaignVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
