// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrenewal"
)

// SubscriptionRenewalDelete is the builder for deleting a SubscriptionRenewal entity.
type SubscriptionRenewalDelete struct {
	config
	hooks    []Hook
	mutation *SubscriptionRenewalMutation
}

// Where appends a list predicates to the SubscriptionRenewalDelete builder.
func (_d *SubscriptionRenewalDelete) Where(ps ...predicate.SubscriptionRenewal) *SubscriptionRenewalDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SubscriptionRenewalDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionRenewalDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SubscriptionRenewalDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(subscriptionrenewal.Table, sqlgraph.NewFieldSpec(subscriptionrenewal.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SubscriptionRenewalDeleteOne is the builder for deleting a single SubscriptionRenewal entity.
type SubscriptionRenewalDeleteOne struct {
	_d *SubscriptionRenewalDelete
}

// Where appends a list predicates to the SubscriptionRenewalDelete builder.
func (_d *SubscriptionRenewalDeleteOne) Where(ps ...predicate.SubscriptionRenewal) *SubscriptionRenewalDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SubscriptionRenewalDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subscriptionrenewal.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionRenewalDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
