// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/userbehaviordaily"
)

// UserBehaviorDailyUpdate is the builder for updating UserBehaviorDaily entities.
type UserBehaviorDailyUpdate struct {
	config
	hooks    []Hook
	mutation *UserBehaviorDailyMutation
}

// Where appends a list predicates to the UserBehaviorDailyUpdate builder.
func (_u *UserBehaviorDailyUpdate) Where(ps ...predicate.UserBehaviorDaily) *UserBehaviorDailyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *UserBehaviorDailyUpdate) SetRequestCount(v int64) *UserBehaviorDailyUpdate {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *UserBehaviorDailyUpdate) SetNillableRequestCount(v *int64) *UserBehaviorDailyUpdate {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *UserBehaviorDailyUpdate) AddRequestCount(v int64) *UserBehaviorDailyUpdate {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *UserBehaviorDailyUpdate) SetActualCost(v float64) *UserBehaviorDailyUpdate {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *UserBehaviorDailyUpdate) SetNillableActualCost(v *float64) *UserBehaviorDailyUpdate {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *UserBehaviorDailyUpdate) AddActualCost(v float64) *UserBehaviorDailyUpdate {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetRechargeAmount sets the "recharge_amount" field.
func (_u *UserBehaviorDailyUpdate) SetRechargeAmount(v float64) *UserBehaviorDailyUpdate {
	_u.mutation.ResetRechargeAmount()
	_u.mutation.SetRechargeAmount(v)
	return _u
}

// SetNillableRechargeAmount sets the "recharge_amount" field if the given value is not nil.
func (_u *UserBehaviorDailyUpdate) SetNillableRechargeAmount(v *float64) *UserBehaviorDailyUpdate {
	if v != nil {
		_u.SetRechargeAmount(*v)
	}
	return _u
}

// AddRechargeAmount adds value to the "recharge_amount" field.
func (_u *UserBehaviorDailyUpdate) AddRechargeAmount(v float64) *UserBehaviorDailyUpdate {
	_u.mutation.AddRechargeAmount(v)
	return _u
}

// SetLastAPIUseAt sets the "last_api_use_at" field.
func (_u *UserBehaviorDailyUpdate) SetLastAPIUseAt(v time.Time) *UserBehaviorDailyUpdate {
	_u.mutation.SetLastAPIUseAt(v)
	return _u
}

// SetNillableLastAPIUseAt sets the "last_api_use_at" field if the given value is not nil.
func (_u *UserBehaviorDailyUpdate) SetNillableLastAPIUseAt(v *time.Time) *UserBehaviorDailyUpdate {
	if v != nil {
		_u.SetLastAPIUseAt(*v)
	}
	return _u
}

// ClearLastAPIUseAt clears the value of the "last_api_use_at" field.
func (_u *UserBehaviorDailyUpdate) ClearLastAPIUseAt() *UserBehaviorDailyUpdate {
	_u.mutation.ClearLastAPIUseAt()
	return _u
}

// SetLastActiveAt sets the "last_active_at" field.
func (_u *UserBehaviorDailyUpdate) SetLastActiveAt(v time.Time) *UserBehaviorDailyUpdate {
	_u.mutation.SetLastActiveAt(v)
	return _u
}

// SetNillableLastActiveAt sets the "last_active_at" field if the given value is not nil.
func (_u *UserBehaviorDailyUpdate) SetNillableLastActiveAt(v *time.Time) *UserBehaviorDailyUpdate {
	if v != nil {
		_u.SetLastActiveAt(*v)
	}
	return _u
}

// ClearLastActiveAt clears the value of the "last_active_at" field.
func (_u *UserBehaviorDailyUpdate) ClearLastActiveAt() *UserBehaviorDailyUpdate {
	_u.mutation.ClearLastActiveAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserBehaviorDailyUpdate) SetUpdatedAt(v time.Time) *UserBehaviorDailyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserBehaviorDailyMutation object of the builder.
func (_u *UserBehaviorDailyUpdate) Mutation() *UserBehaviorDailyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserBehaviorDailyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserBehaviorDailyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserBehaviorDailyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserBehaviorDailyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserBehaviorDailyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userbehaviordaily.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserBehaviorDailyUpdate) check() error {
	if v, ok := _u.mutation.RequestCount(); ok {
		if err := userbehaviordaily.RequestCountValidator(v); err != nil {
			return &ValidationError{Name: "request_count", err: fmt.Errorf(`ent: validator failed for field "UserBehaviorDaily.request_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualCost(); ok {
		if err := userbehaviordaily.ActualCostValidator(v); err != nil {
			return &ValidationError{Name: "actual_cost", err: fmt.Errorf(`ent: validator failed for field "UserBehaviorDaily.actual_cost": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RechargeAmount(); ok {
		if err := userbehaviordaily.RechargeAmountValidator(v); err != nil {
			return &ValidationError{Name: "recharge_amount", err: fmt.Errorf(`ent: validator failed for field "UserBehaviorDaily.recharge_amount": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBehaviorDaily.user"`)
	}
	return nil
}

func (_u *UserBehaviorDailyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userbehaviordaily.Table, userbehaviordaily.Columns, sqlgraph.NewFieldSpec(userbehaviordaily.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(userbehaviordaily.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(userbehaviordaily.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(userbehaviordaily.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(userbehaviordaily.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RechargeAmount(); ok {
		_spec.SetField(userbehaviordaily.FieldRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRechargeAmount(); ok {
		_spec.AddField(userbehaviordaily.FieldRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LastAPIUseAt(); ok {
		_spec.SetField(userbehaviordaily.FieldLastAPIUseAt, field.TypeTime, value)
	}
	if _u.mutation.LastAPIUseAtCleared() {
		_spec.ClearField(userbehaviordaily.FieldLastAPIUseAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastActiveAt(); ok {
		_spec.SetField(userbehaviordaily.FieldLastActiveAt, field.TypeTime, value)
	}
	if _u.mutation.LastActiveAtCleared() {
		_spec.ClearField(userbehaviordaily.FieldLastActiveAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userbehaviordaily.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userbehaviordaily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserBehaviorDailyUpdateOne is the builder for updating a single UserBehaviorDaily entity.
type UserBehaviorDailyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserBehaviorDailyMutation
}

// SetRequestCount sets the "request_count" field.
func (_u *UserBehaviorDailyUpdateOne) SetRequestCount(v int64) *UserBehaviorDailyUpdateOne {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *UserBehaviorDailyUpdateOne) SetNillableRequestCount(v *int64) *UserBehaviorDailyUpdateOne {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *UserBehaviorDailyUpdateOne) AddRequestCount(v int64) *UserBehaviorDailyUpdateOne {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *UserBehaviorDailyUpdateOne) SetActualCost(v float64) *UserBehaviorDailyUpdateOne {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *UserBehaviorDailyUpdateOne) SetNillableActualCost(v *float64) *UserBehaviorDailyUpdateOne {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *UserBehaviorDailyUpdateOne) AddActualCost(v float64) *UserBehaviorDailyUpdateOne {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetRechargeAmount sets the "recharge_amount" field.
func (_u *UserBehaviorDailyUpdateOne) SetRechargeAmount(v float64) *UserBehaviorDailyUpdateOne {
	_u.mutation.ResetRechargeAmount()
	_u.mutation.SetRechargeAmount(v)
	return _u
}

// SetNillableRechargeAmount sets the "recharge_amount" field if the given value is not nil.
func (_u *UserBehaviorDailyUpdateOne) SetNillableRechargeAmount(v *float64) *UserBehaviorDailyUpdateOne {
	if v != nil {
		_u.SetRechargeAmount(*v)
	}
	return _u
}

// AddRechargeAmount adds value to the "recharge_amount" field.
func (_u *UserBehaviorDailyUpdateOne) AddRechargeAmount(v float64) *UserBehaviorDailyUpdateOne {
	_u.mutation.AddRechargeAmount(v)
	return _u
}

// SetLastAPIUseAt sets the "last_api_use_at" field.
func (_u *UserBehaviorDailyUpdateOne) SetLastAPIUseAt(v time.Time) *UserBehaviorDailyUpdateOne {
	_u.mutation.SetLastAPIUseAt(v)
	return _u
}

// SetNillableLastAPIUseAt sets the "last_api_use_at" field if the given value is not nil.
func (_u *UserBehaviorDailyUpdateOne) SetNillableLastAPIUseAt(v *time.Time) *UserBehaviorDailyUpdateOne {
	if v != nil {
		_u.SetLastAPIUseAt(*v)
	}
	return _u
}

// ClearLastAPIUseAt clears the value of the "last_api_use_at" field.
func (_u *UserBehaviorDailyUpdateOne) ClearLastAPIUseAt() *UserBehaviorDailyUpdateOne {
	_u.mutation.ClearLastAPIUseAt()
	return _u
}

// SetLastActiveAt sets the "last_active_at" field.
func (_u *UserBehaviorDailyUpdateOne) SetLastActiveAt(v time.Time) *UserBehaviorDailyUpdateOne {
	_u.mutation.SetLastActiveAt(v)
	return _u
}

// SetNillableLastActiveAt sets the "last_active_at" field if the given value is not nil.
func (_u *UserBehaviorDailyUpdateOne) SetNillableLastActiveAt(v *time.Time) *UserBehaviorDailyUpdateOne {
	if v != nil {
		_u.SetLastActiveAt(*v)
	}
	return _u
}

// ClearLastActiveAt clears the value of the "last_active_at" field.
func (_u *UserBehaviorDailyUpdateOne) ClearLastActiveAt() *UserBehaviorDailyUpdateOne {
	_u.mutation.ClearLastActiveAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserBehaviorDailyUpdateOne) SetUpdatedAt(v time.Time) *UserBehaviorDailyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserBehaviorDailyMutation object of the builder.
func (_u *UserBehaviorDailyUpdateOne) Mutation() *UserBehaviorDailyMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserBehaviorDailyUpdate builder.
func (_u *UserBehaviorDailyUpdateOne) Where(ps ...predicate.UserBehaviorDaily) *UserBehaviorDailyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserBehaviorDailyUpdateOne) Select(field string, fields ...string) *UserBehaviorDailyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserBehaviorDaily entity.
func (_u *UserBehaviorDailyUpdateOne) Save(ctx context.Context) (*UserBehaviorDaily, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserBehaviorDailyUpdateOne) SaveX(ctx context.Context) *UserBehaviorDaily {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserBehaviorDailyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserBehaviorDailyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserBehaviorDailyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userbehaviordaily.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserBehaviorDailyUpdateOne) check() error {
	if v, ok := _u.mutation.RequestCount(); ok {
		if err := userbehaviordaily.RequestCountValidator(v); err != nil {
			return &ValidationError{Name: "request_count", err: fmt.Errorf(`ent: validator failed for field "UserBehaviorDaily.request_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualCost(); ok {
		if err := userbehaviordaily.ActualCostValidator(v); err != nil {
			return &ValidationError{Name: "actual_cost", err: fmt.Errorf(`ent: validator failed for field "UserBehaviorDaily.actual_cost": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RechargeAmount(); ok {
		if err := userbehaviordaily.RechargeAmountValidator(v); err != nil {
			return &ValidationError{Name: "recharge_amount", err: fmt.Errorf(`ent: validator failed for field "UserBehaviorDaily.recharge_amount": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBehaviorDaily.user"`)
	}
	return nil
}

func (_u *UserBehaviorDailyUpdateOne) sqlSave(ctx context.Context) (_node *UserBehaviorDaily, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userbehaviordaily.Table, userbehaviordaily.Columns, sqlgraph.NewFieldSpec(userbehaviordaily.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserBehaviorDaily.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userbehaviordaily.FieldID)
		for _, f := range fields {
			if !userbehaviordaily.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userbehaviordaily.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(userbehaviordaily.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(userbehaviordaily.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(userbehaviordaily.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(userbehaviordaily.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RechargeAmount(); ok {
		_spec.SetField(userbehaviordaily.FieldRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRechargeAmount(); ok {
		_spec.AddField(userbehaviordaily.FieldRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LastAPIUseAt(); ok {
		_spec.SetField(userbehaviordaily.FieldLastAPIUseAt, field.TypeTime, value)
	}
	if _u.mutation.LastAPIUseAtCleared() {
		_spec.ClearField(userbehaviordaily.FieldLastAPIUseAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastActiveAt(); ok {
		_spec.SetField(userbehaviordaily.FieldLastActiveAt, field.TypeTime, value)
	}
	if _u.mutation.LastActiveAtCleared() {
		_spec.ClearField(userbehaviordaily.FieldLastActiveAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userbehaviordaily.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserBehaviorDaily{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userbehaviordaily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
