// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/userrewardgrant"
)

// UserRewardGrantUpdate is the builder for updating UserRewardGrant entities.
type UserRewardGrantUpdate struct {
	config
	hooks    []Hook
	mutation *UserRewardGrantMutation
}

// Where appends a list predicates to the UserRewardGrantUpdate builder.
func (_u *UserRewardGrantUpdate) Where(ps ...predicate.UserRewardGrant) *UserRewardGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserRewardGrantUpdate) SetUpdatedAt(v time.Time) *UserRewardGrantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserRewardGrantUpdate) SetStatus(v string) *UserRewardGrantUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserRewardGrantUpdate) SetNillableStatus(v *string) *UserRewardGrantUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetViewedAt sets the "viewed_at" field.
func (_u *UserRewardGrantUpdate) SetViewedAt(v time.Time) *UserRewardGrantUpdate {
	_u.mutation.SetViewedAt(v)
	return _u
}

// SetNillableViewedAt sets the "viewed_at" field if the given value is not nil.
func (_u *UserRewardGrantUpdate) SetNillableViewedAt(v *time.Time) *UserRewardGrantUpdate {
	if v != nil {
		_u.SetViewedAt(*v)
	}
	return _u
}

// ClearViewedAt clears the value of the "viewed_at" field.
func (_u *UserRewardGrantUpdate) ClearViewedAt() *UserRewardGrantUpdate {
	_u.mutation.ClearViewedAt()
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *UserRewardGrantUpdate) SetClaimedAt(v time.Time) *UserRewardGrantUpdate {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *UserRewardGrantUpdate) SetNillableClaimedAt(v *time.Time) *UserRewardGrantUpdate {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (_u *UserRewardGrantUpdate) ClearClaimedAt() *UserRewardGrantUpdate {
	_u.mutation.ClearClaimedAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *UserRewardGrantUpdate) SetExpiredAt(v time.Time) *UserRewardGrantUpdate {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *UserRewardGrantUpdate) SetNillableExpiredAt(v *time.Time) *UserRewardGrantUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *UserRewardGrantUpdate) ClearExpiredAt() *UserRewardGrantUpdate {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *UserRewardGrantUpdate) SetBalanceAfter(v float64) *UserRewardGrantUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *UserRewardGrantUpdate) SetNillableBalanceAfter(v *float64) *UserRewardGrantUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *UserRewardGrantUpdate) AddBalanceAfter(v float64) *UserRewardGrantUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (_u *UserRewardGrantUpdate) ClearBalanceAfter() *UserRewardGrantUpdate {
	_u.mutation.ClearBalanceAfter()
	return _u
}

// SetClaimRecordID sets the "claim_record_id" field.
func (_u *UserRewardGrantUpdate) SetClaimRecordID(v int64) *UserRewardGrantUpdate {
	_u.mutation.SetClaimRecordID(v)
	return _u
}

// SetNillableClaimRecordID sets the "claim_record_id" field if the given value is not nil.
func (_u *UserRewardGrantUpdate) SetNillableClaimRecordID(v *int64) *UserRewardGrantUpdate {
	if v != nil {
		_u.SetClaimRecordID(*v)
	}
	return _u
}

// ClearClaimRecordID clears the value of the "claim_record_id" field.
func (_u *UserRewardGrantUpdate) ClearClaimRecordID() *UserRewardGrantUpdate {
	_u.mutation.ClearClaimRecordID()
	return _u
}

// SetClaimReference sets the "claim_reference" field.
func (_u *UserRewardGrantUpdate) SetClaimReference(v string) *UserRewardGrantUpdate {
	_u.mutation.SetClaimReference(v)
	return _u
}

// SetNillableClaimReference sets the "claim_reference" field if the given value is not nil.
func (_u *UserRewardGrantUpdate) SetNillableClaimReference(v *string) *UserRewardGrantUpdate {
	if v != nil {
		_u.SetClaimReference(*v)
	}
	return _u
}

// SetClaimRecord sets the "claim_record" edge to the RedeemCode entity.
func (_u *UserRewardGrantUpdate) SetClaimRecord(v *RedeemCode) *UserRewardGrantUpdate {
	return _u.SetClaimRecordID(v.ID)
}

// Mutation returns the UserRewardGrantMutation object of the builder.
func (_u *UserRewardGrantUpdate) Mutation() *UserRewardGrantMutation {
	return _u.mutation
}

// ClearClaimRecord clears the "claim_record" edge to the RedeemCode entity.
func (_u *UserRewardGrantUpdate) ClearClaimRecord() *UserRewardGrantUpdate {
	_u.mutation.ClearClaimRecord()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserRewardGrantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRewardGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserRewardGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRewardGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserRewardGrantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userrewardgrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRewardGrantUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := userrewardgrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserRewardGrant.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClaimReference(); ok {
		if err := userrewardgrant.ClaimReferenceValidator(v); err != nil {
			return &ValidationError{Name: "claim_reference", err: fmt.Errorf(`ent: validator failed for field "UserRewardGrant.claim_reference": %w`, err)}
		}
	}
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRewardGrant.campaign"`)
	}
	if _u.mutation.CampaignVersionCleared() && len(_u.mutation.CampaignVersionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRewardGrant.campaign_version"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRewardGrant.user"`)
	}
	return nil
}

func (_u *UserRewardGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userrewardgrant.Table, userrewardgrant.Columns, sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userrewardgrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userrewardgrant.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(userrewardgrant.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ViewedAt(); ok {
		_spec.SetField(userrewardgrant.FieldViewedAt, field.TypeTime, value)
	}
	if _u.mutation.ViewedAtCleared() {
		_spec.ClearField(userrewardgrant.FieldViewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(userrewardgrant.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.ClaimedAtCleared() {
		_spec.ClearField(userrewardgrant.FieldClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(userrewardgrant.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(userrewardgrant.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(userrewardgrant.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(userrewardgrant.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAfterCleared() {
		_spec.ClearField(userrewardgrant.FieldBalanceAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ClaimReference(); ok {
		_spec.SetField(userrewardgrant.FieldClaimReference, field.TypeString, value)
	}
	if _u.mutation.ClaimRecordCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userrewardgrant.ClaimRecordTable,
			Columns: []string{userrewardgrant.ClaimRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClaimRecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userrewardgrant.ClaimRecordTable,
			Columns: []string{userrewardgrant.ClaimRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrewardgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserRewardGrantUpdateOne is the builder for updating a single UserRewardGrant entity.
type UserRewardGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserRewardGrantMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserRewardGrantUpdateOne) SetUpdatedAt(v time.Time) *UserRewardGrantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserRewardGrantUpdateOne) SetStatus(v string) *UserRewardGrantUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserRewardGrantUpdateOne) SetNillableStatus(v *string) *UserRewardGrantUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetViewedAt sets the "viewed_at" field.
func (_u *UserRewardGrantUpdateOne) SetViewedAt(v time.Time) *UserRewardGrantUpdateOne {
	_u.mutation.SetViewedAt(v)
	return _u
}

// SetNillableViewedAt sets the "viewed_at" field if the given value is not nil.
func (_u *UserRewardGrantUpdateOne) SetNillableViewedAt(v *time.Time) *UserRewardGrantUpdateOne {
	if v != nil {
		_u.SetViewedAt(*v)
	}
	return _u
}

// ClearViewedAt clears the value of the "viewed_at" field.
func (_u *UserRewardGrantUpdateOne) ClearViewedAt() *UserRewardGrantUpdateOne {
	_u.mutation.ClearViewedAt()
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *UserRewardGrantUpdateOne) SetClaimedAt(v time.Time) *UserRewardGrantUpdateOne {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *UserRewardGrantUpdateOne) SetNillableClaimedAt(v *time.Time) *UserRewardGrantUpdateOne {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (_u *UserRewardGrantUpdateOne) ClearClaimedAt() *UserRewardGrantUpdateOne {
	_u.mutation.ClearClaimedAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *UserRewardGrantUpdateOne) SetExpiredAt(v time.Time) *UserRewardGrantUpdateOne {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *UserRewardGrantUpdateOne) SetNillableExpiredAt(v *time.Time) *UserRewardGrantUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *UserRewardGrantUpdateOne) ClearExpiredAt() *UserRewardGrantUpdateOne {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *UserRewardGrantUpdateOne) SetBalanceAfter(v float64) *UserRewardGrantUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *UserRewardGrantUpdateOne) SetNillableBalanceAfter(v *float64) *UserRewardGrantUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *UserRewardGrantUpdateOne) AddBalanceAfter(v float64) *UserRewardGrantUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (_u *UserRewardGrantUpdateOne) ClearBalanceAfter() *UserRewardGrantUpdateOne {
	_u.mutation.ClearBalanceAfter()
	return _u
}

// SetClaimRecordID sets the "claim_record_id" field.
func (_u *UserRewardGrantUpdateOne) SetClaimRecordID(v int64) *UserRewardGrantUpdateOne {
	_u.mutation.SetClaimRecordID(v)
	return _u
}

// SetNillableClaimRecordID sets the "claim_record_id" field if the given value is not nil.
func (_u *UserRewardGrantUpdateOne) SetNillableClaimRecordID(v *int64) *UserRewardGrantUpdateOne {
	if v != nil {
		_u.SetClaimRecordID(*v)
	}
	return _u
}

// ClearClaimRecordID clears the value of the "claim_record_id" field.
func (_u *UserRewardGrantUpdateOne) ClearClaimRecordID() *UserRewardGrantUpdateOne {
	_u.mutation.ClearClaimRecordID()
	return _u
}

// SetClaimReference sets the "claim_reference" field.
func (_u *UserRewardGrantUpdateOne) SetClaimReference(v string) *UserRewardGrantUpdateOne {
	_u.mutation.SetClaimReference(v)
	return _u
}

// SetNillableClaimReference sets the "claim_reference" field if the given value is not nil.
func (_u *UserRewardGrantUpdateOne) SetNillableClaimReference(v *string) *UserRewardGrantUpdateOne {
	if v != nil {
		_u.SetClaimReference(*v)
	}
	return _u
}

// SetClaimRecord sets the "claim_record" edge to the RedeemCode entity.
func (_u *UserRewardGrantUpdateOne) SetClaimRecord(v *RedeemCode) *UserRewardGrantUpdateOne {
	return _u.SetClaimRecordID(v.ID)
}

// Mutation returns the UserRewardGrantMutation object of the builder.
func (_u *UserRewardGrantUpdateOne) Mutation() *UserRewardGrantMutation {
	return _u.mutation
}

// ClearClaimRecord clears the "claim_record" edge to the RedeemCode entity.
func (_u *UserRewardGrantUpdateOne) ClearClaimRecord() *UserRewardGrantUpdateOne {
	_u.mutation.ClearClaimRecord()
	return _u
}

// Where appends a list predicates to the UserRewardGrantUpdate builder.
func (_u *UserRewardGrantUpdateOne) Where(ps ...predicate.UserRewardGrant) *UserRewardGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserRewardGrantUpdateOne) Select(field string, fields ...string) *UserRewardGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserRewardGrant entity.
func (_u *UserRewardGrantUpdateOne) Save(ctx context.Context) (*UserRewardGrant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRewardGrantUpdateOne) SaveX(ctx context.Context) *UserRewardGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserRewardGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRewardGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserRewardGrantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userrewardgrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRewardGrantUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := userrewardgrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserRewardGrant.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClaimReference(); ok {
		if err := userrewardgrant.ClaimReferenceValidator(v); err != nil {
			return &ValidationError{Name: "claim_reference", err: fmt.Errorf(`ent: validator failed for field "UserRewardGrant.claim_reference": %w`, err)}
		}
	}
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRewardGrant.campaign"`)
	}
	if _u.mutation.CampaignVersionCleared() && len(_u.mutation.CampaignVersionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRewardGrant.campaign_version"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRewardGrant.user"`)
	}
	return nil
}

func (_u *UserRewardGrantUpdateOne) sqlSave(ctx context.Context) (_node *UserRewardGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userrewardgrant.Table, userrewardgrant.Columns, sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserRewardGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userrewardgrant.FieldID)
		for _, f := range fields {
			if !userrewardgrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userrewardgrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userrewardgrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userrewardgrant.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(userrewardgrant.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ViewedAt(); ok {
		_spec.SetField(userrewardgrant.FieldViewedAt, field.TypeTime, value)
	}
	if _u.mutation.ViewedAtCleared() {
		_spec.ClearField(userrewardgrant.FieldViewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(userrewardgrant.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.ClaimedAtCleared() {
		_spec.ClearField(userrewardgrant.FieldClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(userrewardgrant.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(userrewardgrant.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(userrewardgrant.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(userrewardgrant.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAfterCleared() {
		_spec.ClearField(userrewardgrant.FieldBalanceAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ClaimReference(); ok {
		_spec.SetField(userrewardgrant.FieldClaimReference, field.TypeString, value)
	}
	if _u.mutation.ClaimRecordCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userrewardgrant.ClaimRecordTable,
			Columns: []string{userrewardgrant.ClaimRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClaimRecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userrewardgrant.ClaimRecordTable,
			Columns: []string{userrewardgrant.ClaimRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserRewardGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrewardgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
