// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/rewardcampaign"
	"github.com/Wei-Shaw/sub2api/ent/rewardcampaignjob"
	"github.com/Wei-Shaw/sub2api/ent/rewardcampaignversion"
	"github.com/Wei-Shaw/sub2api/ent/rewardskin"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userrewardgrant"
)

// UserRewardGrantCreate is the builder for creating a UserRewardGrant entity.
type UserRewardGrantCreate struct {
	config
	mutation *UserRewardGrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserRewardGrantCreate) SetCreatedAt(v time.Time) *UserRewardGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserRewardGrantCreate) SetNillableCreatedAt(v *time.Time) *UserRewardGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserRewardGrantCreate) SetUpdatedAt(v time.Time) *UserRewardGrantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserRewardGrantCreate) SetNillableUpdatedAt(v *time.Time) *UserRewardGrantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCampaignID sets the "campaign_id" field.
func (_c *UserRewardGrantCreate) SetCampaignID(v int64) *UserRewardGrantCreate {
	_c.mutation.SetCampaignID(v)
	return _c
}

// SetCampaignVersionID sets the "campaign_version_id" field.
func (_c *UserRewardGrantCreate) SetCampaignVersionID(v int64) *UserRewardGrantCreate {
	_c.mutation.SetCampaignVersionID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserRewardGrantCreate) SetUserID(v int64) *UserRewardGrantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSkinID sets the "skin_id" field.
func (_c *UserRewardGrantCreate) SetSkinID(v int64) *UserRewardGrantCreate {
	_c.mutation.SetSkinID(v)
	return _c
}

// SetNillableSkinID sets the "skin_id" field if the given value is not nil.
func (_c *UserRewardGrantCreate) SetNillableSkinID(v *int64) *UserRewardGrantCreate {
	if v != nil {
		_c.SetSkinID(*v)
	}
	return _c
}

// SetJobID sets the "job_id" field.
func (_c *UserRewardGrantCreate) SetJobID(v int64) *UserRewardGrantCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_c *UserRewardGrantCreate) SetNillableJobID(v *int64) *UserRewardGrantCreate {
	if v != nil {
		_c.SetJobID(*v)
	}
	return _c
}

// SetCycleKey sets the "cycle_key" field.
func (_c *UserRewardGrantCreate) SetCycleKey(v string) *UserRewardGrantCreate {
	_c.mutation.SetCycleKey(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *UserRewardGrantCreate) SetSource(v string) *UserRewardGrantCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserRewardGrantCreate) SetStatus(v string) *UserRewardGrantCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserRewardGrantCreate) SetNillableStatus(v *string) *UserRewardGrantCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *UserRewardGrantCreate) SetAmount(v float64) *UserRewardGrantCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *UserRewardGrantCreate) SetPriority(v int) *UserRewardGrantCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *UserRewardGrantCreate) SetNillablePriority(v *int) *UserRewardGrantCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetCopySnapshot sets the "copy_snapshot" field.
func (_c *UserRewardGrantCreate) SetCopySnapshot(v map[string]interface{}) *UserRewardGrantCreate {
	_c.mutation.SetCopySnapshot(v)
	return _c
}

// SetSkinSnapshot sets the "skin_snapshot" field.
func (_c *UserRewardGrantCreate) SetSkinSnapshot(v map[string]interface{}) *UserRewardGrantCreate {
	_c.mutation.SetSkinSnapshot(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *UserRewardGrantCreate) SetMetadata(v map[string]interface{}) *UserRewardGrantCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserRewardGrantCreate) SetExpiresAt(v time.Time) *UserRewardGrantCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *UserRewardGrantCreate) SetNillableExpiresAt(v *time.Time) *UserRewardGrantCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetViewedAt sets the "viewed_at" field.
func (_c *UserRewardGrantCreate) SetViewedAt(v time.Time) *UserRewardGrantCreate {
	_c.mutation.SetViewedAt(v)
	return _c
}

// SetNillableViewedAt sets the "viewed_at" field if the given value is not nil.
func (_c *UserRewardGrantCreate) SetNillableViewedAt(v *time.Time) *UserRewardGrantCreate {
	if v != nil {
		_c.SetViewedAt(*v)
	}
	return _c
}

// SetClaimedAt sets the "claimed_at" field.
func (_c *UserRewardGrantCreate) SetClaimedAt(v time.Time) *UserRewardGrantCreate {
	_c.mutation.SetClaimedAt(v)
	return _c
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_c *UserRewardGrantCreate) SetNillableClaimedAt(v *time.Time) *UserRewardGrantCreate {
	if v != nil {
		_c.SetClaimedAt(*v)
	}
	return _c
}

// SetExpiredAt sets the "expired_at" field.
func (_c *UserRewardGrantCreate) SetExpiredAt(v time.Time) *UserRewardGrantCreate {
	_c.mutation.SetExpiredAt(v)
	return _c
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_c *UserRewardGrantCreate) SetNillableExpiredAt(v *time.Time) *UserRewardGrantCreate {
	if v != nil {
		_c.SetExpiredAt(*v)
	}
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *UserRewardGrantCreate) SetBalanceAfter(v float64) *UserRewardGrantCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_c *UserRewardGrantCreate) SetNillableBalanceAfter(v *float64) *UserRewardGrantCreate {
	if v != nil {
		_c.SetBalanceAfter(*v)
	}
	return _c
}

// SetClaimRecordID sets the "claim_record_id" field.
func (_c *UserRewardGrantCreate) SetClaimRecordID(v int64) *UserRewardGrantCreate {
	_c.mutation.SetClaimRecordID(v)
	return _c
}

// SetNillableClaimRecordID sets the "claim_record_id" field if the given value is not nil.
func (_c *UserRewardGrantCreate) SetNillableClaimRecordID(v *int64) *UserRewardGrantCreate {
	if v != nil {
		_c.SetClaimRecordID(*v)
	}
	return _c
}

// SetClaimReference sets the "claim_reference" field.
func (_c *UserRewardGrantCreate) SetClaimReference(v string) *UserRewardGrantCreate {
	_c.mutation.SetClaimReference(v)
	return _c
}

// SetNillableClaimReference sets the "claim_reference" field if the given value is not nil.
func (_c *UserRewardGrantCreate) SetNillableClaimReference(v *string) *UserRewardGrantCreate {
	if v != nil {
		_c.SetClaimReference(*v)
	}
	return _c
}

// SetCampaign sets the "campaign" edge to the RewardCampaign entity.
func (_c *UserRewardGrantCreate) SetCampaign(v *RewardCampaign) *UserRewardGrantCreate {
	return _c.SetCampaignID(v.ID)
}

// SetCampaignVersion sets the "campaign_version" edge to the RewardCampaignVersion entity.
func (_c *UserRewardGrantCreate) SetCampaignVersion(v *RewardCampaignVersion) *UserRewardGrantCreate {
	return _c.SetCampaignVersionID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserRewardGrantCreate) SetUser(v *User) *UserRewardGrantCreate {
	return _c.SetUserID(v.ID)
}

// SetSkin sets the "skin" edge to the RewardSkin entity.
func (_c *UserRewardGrantCreate) SetSkin(v *RewardSkin) *UserRewardGrantCreate {
	return _c.SetSkinID(v.ID)
}

// SetJob sets the "job" edge to the RewardCampaignJob entity.
func (_c *UserRewardGrantCreate) SetJob(v *RewardCampaignJob) *UserRewardGrantCreate {
	return _c.SetJobID(v.ID)
}

// SetClaimRecord sets the "claim_record" edge to the RedeemCode entity.
func (_c *UserRewardGrantCreate) SetClaimRecord(v *RedeemCode) *UserRewardGrantCreate {
	return _c.SetClaimRecordID(v.ID)
}

// Mutation returns the UserRewardGrantMutation object of the builder.
func (_c *UserRewardGrantCreate) Mutation() *UserRewardGrantMutation {
	return _c.mutation
}

// Save creates the UserRewardGrant in the database.
func (_c *UserRewardGrantCreate) Save(ctx context.Context) (*UserRewardGrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserRewardGrantCreate) SaveX(ctx context.Context) *UserRewardGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRewardGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRewardGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserRewardGrantCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userrewardgrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userrewardgrant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := userrewardgrant.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := userrewardgrant.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.ClaimReference(); !ok {
		v := userrewardgrant.DefaultClaimReference
		_c.mutation.SetClaimReference(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserRewardGrantCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserRewardGrant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserRewardGrant.updated_at"`)}
	}
	if _, ok := _c.mutation.CampaignID(); !ok {
		return &ValidationError{Name: "campaign_id", err: errors.New(`ent: missing required field "UserRewardGrant.campaign_id"`)}
	}
	if _, ok := _c.mutation.CampaignVersionID(); !ok {
		return &ValidationError{Name: "campaign_version_id", err: errors.New(`ent: missing required field "UserRewardGrant.campaign_version_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserRewardGrant.user_id"`)}
	}
	if _, ok := _c.mutation.CycleKey(); !ok {
		return &ValidationError{Name: "cycle_key", err: errors.New(`ent: missing required field "UserRewardGrant.cycle_key"`)}
	}
	if v, ok := _c.mutation.CycleKey(); ok {
		if err := userrewardgrant.CycleKeyValidator(v); err != nil {
			return &ValidationError{Name: "cycle_key", err: fmt.Errorf(`ent: validator failed for field "UserRewardGrant.cycle_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "UserRewardGrant.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := userrewardgrant.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "UserRewardGrant.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserRewardGrant.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := userrewardgrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserRewardGrant.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "UserRewardGrant.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := userrewardgrant.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "UserRewardGrant.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "UserRewardGrant.priority"`)}
	}
	if _, ok := _c.mutation.CopySnapshot(); !ok {
		return &ValidationError{Name: "copy_snapshot", err: errors.New(`ent: missing required field "UserRewardGrant.copy_snapshot"`)}
	}
	if _, ok := _c.mutation.SkinSnapshot(); !ok {
		return &ValidationError{Name: "skin_snapshot", err: errors.New(`ent: missing required field "UserRewardGrant.skin_snapshot"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "UserRewardGrant.metadata"`)}
	}
	if _, ok := _c.mutation.ClaimReference(); !ok {
		return &ValidationError{Name: "claim_reference", err: errors.New(`ent: missing required field "UserRewardGrant.claim_reference"`)}
	}
	if v, ok := _c.mutation.ClaimReference(); ok {
		if err := userrewardgrant.ClaimReferenceValidator(v); err != nil {
			return &ValidationError{Name: "claim_reference", err: fmt.Errorf(`ent: validator failed for field "UserRewardGrant.claim_reference": %w`, err)}
		}
	}
	if len(_c.mutation.CampaignIDs()) == 0 {
		return &ValidationError{Name: "campaign", err: errors.New(`ent: missing required edge "UserRewardGrant.campaign"`)}
	}
	if len(_c.mutation.CampaignVersionIDs()) == 0 {
		return &ValidationError{Name: "campaign_version", err: errors.New(`ent: missing required edge "UserRewardGrant.campaign_version"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserRewardGrant.user"`)}
	}
	return nil
}

func (_c *UserRewardGrantCreate) sqlSave(ctx context.Context) (*UserRewardGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserRewardGrantCreate) createSpec() (*UserRewardGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &UserRewardGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userrewardgrant.Table, sqlgraph.NewFieldSpec(userrewardgrant.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userrewardgrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userrewardgrant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CycleKey(); ok {
		_spec.SetField(userrewardgrant.FieldCycleKey, field.TypeString, value)
		_node.CycleKey = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(userrewardgrant.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(userrewardgrant.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(userrewardgrant.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(userrewardgrant.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.CopySnapshot(); ok {
		_spec.SetField(userrewardgrant.FieldCopySnapshot, field.TypeJSON, value)
		_node.CopySnapshot = value
	}
	if value, ok := _c.mutation.SkinSnapshot(); ok {
		_spec.SetField(userrewardgrant.FieldSkinSnapshot, field.TypeJSON, value)
		_node.SkinSnapshot = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(userrewardgrant.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(userrewardgrant.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.ViewedAt(); ok {
		_spec.SetField(userrewardgrant.FieldViewedAt, field.TypeTime, value)
		_node.ViewedAt = &value
	}
	if value, ok := _c.mutation.ClaimedAt(); ok {
		_spec.SetField(userrewardgrant.FieldClaimedAt, field.TypeTime, value)
		_node.ClaimedAt = &value
	}
	if value, ok := _c.mutation.ExpiredAt(); ok {
		_spec.SetField(userrewardgrant.FieldExpiredAt, field.TypeTime, value)
		_node.ExpiredAt = &value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(userrewardgrant.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = &value
	}
	if value, ok := _c.mutation.ClaimReference(); ok {
		_spec.SetField(userrewardgrant.FieldClaimReference, field.TypeString, value)
		_node.ClaimReference = value
	}
	if nodes := _c.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userrewardgrant.CampaignTable,
			Columns: []string{userrewardgrant.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CampaignID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CampaignVersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userrewardgrant.CampaignVersionTable,
			Columns: []string{userrewardgrant.CampaignVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaignversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CampaignVersionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userrewardgrant.UserTable,
			Columns: []string{userrewardgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SkinIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userrewardgrant.SkinTable,
			Columns: []string{userrewardgrant.SkinColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardskin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SkinID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userrewardgrant.JobTable,
			Columns: []string{userrewardgrant.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rewardcampaignjob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.JobID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ClaimRecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userrewardgrant.ClaimRecordTable,
			Columns: []string{userrewardgrant.ClaimRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ClaimRecordID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRewardGrant.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRewardGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRewardGrantCreate) OnConflict(opts ...sql.ConflictOption) *UserRewardGrantUpsertOne {
	_c.conflict = opts
	return &UserRewardGrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRewardGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRewardGrantCreate) OnConflictColumns(columns ...string) *UserRewardGrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRewardGrantUpsertOne{
		create: _c,
	}
}

type (
	// UserRewardGrantUpsertOne is the builder for "upsert"-ing
	//  one UserRewardGrant node.
	UserRewardGrantUpsertOne struct {
		create *UserRewardGrantCreate
	}

	// UserRewardGrantUpsert is the "OnConflict" setter.
	UserRewardGrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRewardGrantUpsert) SetUpdatedAt(v time.Time) *UserRewardGrantUpsert {
	u.Set(userrewardgrant.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRewardGrantUpsert) UpdateUpdatedAt() *UserRewardGrantUpsert {
	u.SetExcluded(userrewardgrant.FieldUpdatedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *UserRewardGrantUpsert) SetStatus(v string) *UserRewardGrantUpsert {
	u.Set(userrewardgrant.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserRewardGrantUpsert) UpdateStatus() *UserRewardGrantUpsert {
	u.SetExcluded(userrewardgrant.FieldStatus)
	return u
}

// SetViewedAt sets the "viewed_at" field.
func (u *UserRewardGrantUpsert) SetViewedAt(v time.Time) *UserRewardGrantUpsert {
	u.Set(userrewardgrant.FieldViewedAt, v)
	return u
}

// UpdateViewedAt sets the "viewed_at" field to the value that was provided on create.
func (u *UserRewardGrantUpsert) UpdateViewedAt() *UserRewardGrantUpsert {
	u.SetExcluded(userrewardgrant.FieldViewedAt)
	return u
}

// ClearViewedAt clears the value of the "viewed_at" field.
func (u *UserRewardGrantUpsert) ClearViewedAt() *UserRewardGrantUpsert {
	u.SetNull(userrewardgrant.FieldViewedAt)
	return u
}

// SetClaimedAt sets the "claimed_at" field.
func (u *UserRewardGrantUpsert) SetClaimedAt(v time.Time) *UserRewardGrantUpsert {
	u.Set(userrewardgrant.FieldClaimedAt, v)
	return u
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *UserRewardGrantUpsert) UpdateClaimedAt() *UserRewardGrantUpsert {
	u.SetExcluded(userrewardgrant.FieldClaimedAt)
	return u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *UserRewardGrantUpsert) ClearClaimedAt() *UserRewardGrantUpsert {
	u.SetNull(userrewardgrant.FieldClaimedAt)
	return u
}

// SetExpiredAt sets the "expired_at" field.
func (u *UserRewardGrantUpsert) SetExpiredAt(v time.Time) *UserRewardGrantUpsert {
	u.Set(userrewardgrant.FieldExpiredAt, v)
	return u
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *UserRewardGrantUpsert) UpdateExpiredAt() *UserRewardGrantUpsert {
	u.SetExcluded(userrewardgrant.FieldExpiredAt)
	return u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (u *UserRewardGrantUpsert) ClearExpiredAt() *UserRewardGrantUpsert {
	u.SetNull(userrewardgrant.FieldExpiredAt)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *UserRewardGrantUpsert) SetBalanceAfter(v float64) *UserRewardGrantUpsert {
	u.Set(userrewardgrant.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *UserRewardGrantUpsert) UpdateBalanceAfter() *UserRewardGrantUpsert {
	u.SetExcluded(userrewardgrant.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *UserRewardGrantUpsert) AddBalanceAfter(v float64) *UserRewardGrantUpsert {
	u.Add(userrewardgrant.FieldBalanceAfter, v)
	return u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (u *UserRewardGrantUpsert) ClearBalanceAfter() *UserRewardGrantUpsert {
	u.SetNull(userrewardgrant.FieldBalanceAfter)
	return u
}

// SetClaimRecordID sets the "claim_record_id" field.
func (u *UserRewardGrantUpsert) SetClaimRecordID(v int64) *UserRewardGrantUpsert {
	u.Set(userrewardgrant.FieldClaimRecordID, v)
	return u
}

// UpdateClaimRecordID sets the "claim_record_id" field to the value that was provided on create.
func (u *UserRewardGrantUpsert) UpdateClaimRecordID() *UserRewardGrantUpsert {
	u.SetExcluded(userrewardgrant.FieldClaimRecordID)
	return u
}

// ClearClaimRecordID clears the value of the "claim_record_id" field.
func (u *UserRewardGrantUpsert) ClearClaimRecordID() *UserRewardGrantUpsert {
	u.SetNull(userrewardgrant.FieldClaimRecordID)
	return u
}

// SetClaimReference sets the "claim_reference" field.
func (u *UserRewardGrantUpsert) SetClaimReference(v string) *UserRewardGrantUpsert {
	u.Set(userrewardgrant.FieldClaimReference, v)
	return u
}

// UpdateClaimReference sets the "claim_reference" field to the value that was provided on create.
func (u *UserRewardGrantUpsert) UpdateClaimReference() *UserRewardGrantUpsert {
	u.SetExcluded(userrewardgrant.FieldClaimReference)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserRewardGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserRewardGrantUpsertOne) UpdateNewValues() *UserRewardGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userrewardgrant.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.CampaignID(); exists {
			s.SetIgnore(userrewardgrant.FieldCampaignID)
		}
		if _, exists := u.create.mutation.CampaignVersionID(); exists {
			s.SetIgnore(userrewardgrant.FieldCampaignVersionID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(userrewardgrant.FieldUserID)
		}
		if _, exists := u.create.mutation.SkinID(); exists {
			s.SetIgnore(userrewardgrant.FieldSkinID)
		}
		if _, exists := u.create.mutation.JobID(); exists {
			s.SetIgnore(userrewardgrant.FieldJobID)
		}
		if _, exists := u.create.mutation.CycleKey(); exists {
			s.SetIgnore(userrewardgrant.FieldCycleKey)
		}
		if _, exists := u.create.mutation.Source(); exists {
			s.SetIgnore(userrewardgrant.FieldSource)
		}
		if _, exists := u.create.mutation.Amount(); exists {
			s.SetIgnore(userrewardgrant.FieldAmount)
		}
		if _, exists := u.create.mutation.Priority(); exists {
			s.SetIgnore(userrewardgrant.FieldPriority)
		}
		if _, exists := u.create.mutation.CopySnapshot(); exists {
			s.SetIgnore(userrewardgrant.FieldCopySnapshot)
		}
		if _, exists := u.create.mutation.SkinSnapshot(); exists {
			s.SetIgnore(userrewardgrant.FieldSkinSnapshot)
		}
		if _, exists := u.create.mutation.Metadata(); exists {
			s.SetIgnore(userrewardgrant.FieldMetadata)
		}
		if _, exists := u.create.mutation.ExpiresAt(); exists {
			s.SetIgnore(userrewardgrant.FieldExpiresAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRewardGrant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserRewardGrantUpsertOne) Ignore() *UserRewardGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRewardGrantUpsertOne) DoNothing() *UserRewardGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRewardGrantCreate.OnConflict
// documentation for more info.
func (u *UserRewardGrantUpsertOne) Update(set func(*UserRewardGrantUpsert)) *UserRewardGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRewardGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRewardGrantUpsertOne) SetUpdatedAt(v time.Time) *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRewardGrantUpsertOne) UpdateUpdatedAt() *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserRewardGrantUpsertOne) SetStatus(v string) *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserRewardGrantUpsertOne) UpdateStatus() *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateStatus()
	})
}

// SetViewedAt sets the "viewed_at" field.
func (u *UserRewardGrantUpsertOne) SetViewedAt(v time.Time) *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetViewedAt(v)
	})
}

// UpdateViewedAt sets the "viewed_at" field to the value that was provided on create.
func (u *UserRewardGrantUpsertOne) UpdateViewedAt() *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateViewedAt()
	})
}

// ClearViewedAt clears the value of the "viewed_at" field.
func (u *UserRewardGrantUpsertOne) ClearViewedAt() *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.ClearViewedAt()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *UserRewardGrantUpsertOne) SetClaimedAt(v time.Time) *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *UserRewardGrantUpsertOne) UpdateClaimedAt() *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateClaimedAt()
	})
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *UserRewardGrantUpsertOne) ClearClaimedAt() *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.ClearClaimedAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *UserRewardGrantUpsertOne) SetExpiredAt(v time.Time) *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *UserRewardGrantUpsertOne) UpdateExpiredAt() *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateExpiredAt()
	})
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (u *UserRewardGrantUpsertOne) ClearExpiredAt() *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.ClearExpiredAt()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *UserRewardGrantUpsertOne) SetBalanceAfter(v float64) *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *UserRewardGrantUpsertOne) AddBalanceAfter(v float64) *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *UserRewardGrantUpsertOne) UpdateBalanceAfter() *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateBalanceAfter()
	})
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (u *UserRewardGrantUpsertOne) ClearBalanceAfter() *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.ClearBalanceAfter()
	})
}

// SetClaimRecordID sets the "claim_record_id" field.
func (u *UserRewardGrantUpsertOne) SetClaimRecordID(v int64) *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetClaimRecordID(v)
	})
}

// UpdateClaimRecordID sets the "claim_record_id" field to the value that was provided on create.
func (u *UserRewardGrantUpsertOne) UpdateClaimRecordID() *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateClaimRecordID()
	})
}

// ClearClaimRecordID clears the value of the "claim_record_id" field.
func (u *UserRewardGrantUpsertOne) ClearClaimRecordID() *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.ClearClaimRecordID()
	})
}

// SetClaimReference sets the "claim_reference" field.
func (u *UserRewardGrantUpsertOne) SetClaimReference(v string) *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetClaimReference(v)
	})
}

// UpdateClaimReference sets the "claim_reference" field to the value that was provided on create.
func (u *UserRewardGrantUpsertOne) UpdateClaimReference() *UserRewardGrantUpsertOne {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateClaimReference()
	})
}

// Exec executes the query.
func (u *UserRewardGrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRewardGrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRewardGrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserRewardGrantUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserRewardGrantUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserRewardGrantCreateBulk is the builder for creating many UserRewardGrant entities in bulk.
type UserRewardGrantCreateBulk struct {
	config
	err      error
	builders []*UserRewardGrantCreate
	conflict []sql.ConflictOption
}

// Save creates the UserRewardGrant entities in the database.
func (_c *UserRewardGrantCreateBulk) Save(ctx context.Context) ([]*UserRewardGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserRewardGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserRewardGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserRewardGrantCreateBulk) SaveX(ctx context.Context) []*UserRewardGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRewardGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRewardGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRewardGrant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRewardGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRewardGrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserRewardGrantUpsertBulk {
	_c.conflict = opts
	return &UserRewardGrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRewardGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRewardGrantCreateBulk) OnConflictColumns(columns ...string) *UserRewardGrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRewardGrantUpsertBulk{
		create: _c,
	}
}

// UserRewardGrantUpsertBulk is the builder for "upsert"-ing
// a bulk of UserRewardGrant nodes.
type UserRewardGrantUpsertBulk struct {
	create *UserRewardGrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserRewardGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserRewardGrantUpsertBulk) UpdateNewValues() *UserRewardGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userrewardgrant.FieldCreatedAt)
			}
			if _, exists := b.mutation.CampaignID(); exists {
				s.SetIgnore(userrewardgrant.FieldCampaignID)
			}
			if _, exists := b.mutation.CampaignVersionID(); exists {
				s.SetIgnore(userrewardgrant.FieldCampaignVersionID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(userrewardgrant.FieldUserID)
			}
			if _, exists := b.mutation.SkinID(); exists {
				s.SetIgnore(userrewardgrant.FieldSkinID)
			}
			if _, exists := b.mutation.JobID(); exists {
				s.SetIgnore(userrewardgrant.FieldJobID)
			}
			if _, exists := b.mutation.CycleKey(); exists {
				s.SetIgnore(userrewardgrant.FieldCycleKey)
			}
			if _, exists := b.mutation.Source(); exists {
				s.SetIgnore(userrewardgrant.FieldSource)
			}
			if _, exists := b.mutation.Amount(); exists {
				s.SetIgnore(userrewardgrant.FieldAmount)
			}
			if _, exists := b.mutation.Priority(); exists {
				s.SetIgnore(userrewardgrant.FieldPriority)
			}
			if _, exists := b.mutation.CopySnapshot(); exists {
				s.SetIgnore(userrewardgrant.FieldCopySnapshot)
			}
			if _, exists := b.mutation.SkinSnapshot(); exists {
				s.SetIgnore(userrewardgrant.FieldSkinSnapshot)
			}
			if _, exists := b.mutation.Metadata(); exists {
				s.SetIgnore(userrewardgrant.FieldMetadata)
			}
			if _, exists := b.mutation.ExpiresAt(); exists {
				s.SetIgnore(userrewardgrant.FieldExpiresAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRewardGrant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserRewardGrantUpsertBulk) Ignore() *UserRewardGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRewardGrantUpsertBulk) DoNothing() *UserRewardGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRewardGrantCreateBulk.OnConflict
// documentation for more info.
func (u *UserRewardGrantUpsertBulk) Update(set func(*UserRewardGrantUpsert)) *UserRewardGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRewardGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRewardGrantUpsertBulk) SetUpdatedAt(v time.Time) *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRewardGrantUpsertBulk) UpdateUpdatedAt() *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserRewardGrantUpsertBulk) SetStatus(v string) *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserRewardGrantUpsertBulk) UpdateStatus() *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateStatus()
	})
}

// SetViewedAt sets the "viewed_at" field.
func (u *UserRewardGrantUpsertBulk) SetViewedAt(v time.Time) *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetViewedAt(v)
	})
}

// UpdateViewedAt sets the "viewed_at" field to the value that was provided on create.
func (u *UserRewardGrantUpsertBulk) UpdateViewedAt() *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateViewedAt()
	})
}

// ClearViewedAt clears the value of the "viewed_at" field.
func (u *UserRewardGrantUpsertBulk) ClearViewedAt() *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.ClearViewedAt()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *UserRewardGrantUpsertBulk) SetClaimedAt(v time.Time) *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *UserRewardGrantUpsertBulk) UpdateClaimedAt() *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateClaimedAt()
	})
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *UserRewardGrantUpsertBulk) ClearClaimedAt() *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.ClearClaimedAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *UserRewardGrantUpsertBulk) SetExpiredAt(v time.Time) *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *UserRewardGrantUpsertBulk) UpdateExpiredAt() *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateExpiredAt()
	})
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (u *UserRewardGrantUpsertBulk) ClearExpiredAt() *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.ClearExpiredAt()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *UserRewardGrantUpsertBulk) SetBalanceAfter(v float64) *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *UserRewardGrantUpsertBulk) AddBalanceAfter(v float64) *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *UserRewardGrantUpsertBulk) UpdateBalanceAfter() *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateBalanceAfter()
	})
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (u *UserRewardGrantUpsertBulk) ClearBalanceAfter() *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.ClearBalanceAfter()
	})
}

// SetClaimRecordID sets the "claim_record_id" field.
func (u *UserRewardGrantUpsertBulk) SetClaimRecordID(v int64) *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetClaimRecordID(v)
	})
}

// UpdateClaimRecordID sets the "claim_record_id" field to the value that was provided on create.
func (u *UserRewardGrantUpsertBulk) UpdateClaimRecordID() *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateClaimRecordID()
	})
}

// ClearClaimRecordID clears the value of the "claim_record_id" field.
func (u *UserRewardGrantUpsertBulk) ClearClaimRecordID() *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.ClearClaimRecordID()
	})
}

// SetClaimReference sets the "claim_reference" field.
func (u *UserRewardGrantUpsertBulk) SetClaimReference(v string) *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.SetClaimReference(v)
	})
}

// UpdateClaimReference sets the "claim_reference" field to the value that was provided on create.
func (u *UserRewardGrantUpsertBulk) UpdateClaimReference() *UserRewardGrantUpsertBulk {
	return u.Update(func(s *UserRewardGrantUpsert) {
		s.UpdateClaimReference()
	})
}

// Exec executes the query.
func (u *UserRewardGrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserRewardGrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRewardGrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRewardGrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
