// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/userbehaviordaily"
)

// UserBehaviorDailyDelete is the builder for deleting a UserBehaviorDaily entity.
type UserBehaviorDailyDelete struct {
	config
	hooks    []Hook
	mutation *UserBehaviorDailyMutation
}

// Where appends a list predicates to the UserBehaviorDailyDelete builder.
func (_d *UserBehaviorDailyDelete) Where(ps ...predicate.UserBehaviorDaily) *UserBehaviorDailyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserBehaviorDailyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserBehaviorDailyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserBehaviorDailyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userbehaviordaily.Table, sqlgraph.NewFieldSpec(userbehaviordaily.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserBehaviorDailyDeleteOne is the builder for deleting a single UserBehaviorDaily entity.
type UserBehaviorDailyDeleteOne struct {
	_d *UserBehaviorDailyDelete
}

// Where appends a list predicates to the UserBehaviorDailyDelete builder.
func (_d *UserBehaviorDailyDeleteOne) Where(ps ...predicate.UserBehaviorDaily) *UserBehaviorDailyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserBehaviorDailyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userbehaviordaily.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserBehaviorDailyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
