// Code generated by ent, DO NOT EDIT.

package userrewardgrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userrewardgrant type in the database.
	Label = "user_reward_grant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCampaignID holds the string denoting the campaign_id field in the database.
	FieldCampaignID = "campaign_id"
	// FieldCampaignVersionID holds the string denoting the campaign_version_id field in the database.
	FieldCampaignVersionID = "campaign_version_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldSkinID holds the string denoting the skin_id field in the database.
	FieldSkinID = "skin_id"
	// FieldJobID holds the string denoting the job_id field in the database.
	FieldJobID = "job_id"
	// FieldCycleKey holds the string denoting the cycle_key field in the database.
	FieldCycleKey = "cycle_key"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldCopySnapshot holds the string denoting the copy_snapshot field in the database.
	FieldCopySnapshot = "copy_snapshot"
	// FieldSkinSnapshot holds the string denoting the skin_snapshot field in the database.
	FieldSkinSnapshot = "skin_snapshot"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldViewedAt holds the string denoting the viewed_at field in the database.
	FieldViewedAt = "viewed_at"
	// FieldClaimedAt holds the string denoting the claimed_at field in the database.
	FieldClaimedAt = "claimed_at"
	// FieldExpiredAt holds the string denoting the expired_at field in the database.
	FieldExpiredAt = "expired_at"
	// FieldBalanceAfter holds the string denoting the balance_after field in the database.
	FieldBalanceAfter = "balance_after"
	// FieldClaimRecordID holds the string denoting the claim_record_id field in the database.
	FieldClaimRecordID = "claim_record_id"
	// FieldClaimReference holds the string denoting the claim_reference field in the database.
	FieldClaimReference = "claim_reference"
	// EdgeCampaign holds the string denoting the campaign edge name in mutations.
	EdgeCampaign = "campaign"
	// EdgeCampaignVersion holds the string denoting the campaign_version edge name in mutations.
	EdgeCampaignVersion = "campaign_version"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeSkin holds the string denoting the skin edge name in mutations.
	EdgeSkin = "skin"
	// EdgeJob holds the string denoting the job edge name in mutations.
	EdgeJob = "job"
	// EdgeClaimRecord holds the string denoting the claim_record edge name in mutations.
	EdgeClaimRecord = "claim_record"
	// Table holds the table name of the userrewardgrant in the database.
	Table = "user_reward_grants"
	// CampaignTable is the table that holds the campaign relation/edge.
	CampaignTable = "user_reward_grants"
	// CampaignInverseTable is the table name for the RewardCampaign entity.
	// It exists in this package in order to avoid circular dependency with the "rewardcampaign" package.
	CampaignInverseTable = "reward_campaigns"
	// CampaignColumn is the table column denoting the campaign relation/edge.
	CampaignColumn = "campaign_id"
	// CampaignVersionTable is the table that holds the campaign_version relation/edge.
	CampaignVersionTable = "user_reward_grants"
	// CampaignVersionInverseTable is the table name for the RewardCampaignVersion entity.
	// It exists in this package in order to avoid circular dependency with the "rewardcampaignversion" package.
	CampaignVersionInverseTable = "reward_campaign_versions"
	// CampaignVersionColumn is the table column denoting the campaign_version relation/edge.
	CampaignVersionColumn = "campaign_version_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_reward_grants"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// SkinTable is the table that holds the skin relation/edge.
	SkinTable = "user_reward_grants"
	// SkinInverseTable is the table name for the RewardSkin entity.
	// It exists in this package in order to avoid circular dependency with the "rewardskin" package.
	SkinInverseTable = "reward_skins"
	// SkinColumn is the table column denoting the skin relation/edge.
	SkinColumn = "skin_id"
	// JobTable is the table that holds the job relation/edge.
	JobTable = "user_reward_grants"
	// JobInverseTable is the table name for the RewardCampaignJob entity.
	// It exists in this package in order to avoid circular dependency with the "rewardcampaignjob" package.
	JobInverseTable = "reward_campaign_jobs"
	// JobColumn is the table column denoting the job relation/edge.
	JobColumn = "job_id"
	// ClaimRecordTable is the table that holds the claim_record relation/edge.
	ClaimRecordTable = "user_reward_grants"
	// ClaimRecordInverseTable is the table name for the RedeemCode entity.
	// It exists in this package in order to avoid circular dependency with the "redeemcode" package.
	ClaimRecordInverseTable = "redeem_codes"
	// ClaimRecordColumn is the table column denoting the claim_record relation/edge.
	ClaimRecordColumn = "claim_record_id"
)

// Columns holds all SQL columns for userrewardgrant fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCampaignID,
	FieldCampaignVersionID,
	FieldUserID,
	FieldSkinID,
	FieldJobID,
	FieldCycleKey,
	FieldSource,
	FieldStatus,
	FieldAmount,
	FieldPriority,
	FieldCopySnapshot,
	FieldSkinSnapshot,
	FieldMetadata,
	FieldExpiresAt,
	FieldViewedAt,
	FieldClaimedAt,
	FieldExpiredAt,
	FieldBalanceAfter,
	FieldClaimRecordID,
	FieldClaimReference,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CycleKeyValidator is a validator for the "cycle_key" field. It is called by the builders before save.
	CycleKeyValidator func(string) error
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(float64) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultClaimReference holds the default value on creation for the "claim_reference" field.
	DefaultClaimReference string
	// ClaimReferenceValidator is a validator for the "claim_reference" field. It is called by the builders before save.
	ClaimReferenceValidator func(string) error
)

// OrderOption defines the ordering options for the UserRewardGrant queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCampaignID orders the results by the campaign_id field.
func ByCampaignID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCampaignID, opts...).ToFunc()
}

// ByCampaignVersionID orders the results by the campaign_version_id field.
func ByCampaignVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCampaignVersionID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// BySkinID orders the results by the skin_id field.
func BySkinID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkinID, opts...).ToFunc()
}

// ByJobID orders the results by the job_id field.
func ByJobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobID, opts...).ToFunc()
}

// ByCycleKey orders the results by the cycle_key field.
func ByCycleKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCycleKey, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByViewedAt orders the results by the viewed_at field.
func ByViewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewedAt, opts...).ToFunc()
}

// ByClaimedAt orders the results by the claimed_at field.
func ByClaimedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimedAt, opts...).ToFunc()
}

// ByExpiredAt orders the results by the expired_at field.
func ByExpiredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiredAt, opts...).ToFunc()
}

// ByBalanceAfter orders the results by the balance_after field.
func ByBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAfter, opts...).ToFunc()
}

// ByClaimRecordID orders the results by the claim_record_id field.
func ByClaimRecordID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimRecordID, opts...).ToFunc()
}

// ByClaimReference orders the results by the claim_reference field.
func ByClaimReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimReference, opts...).ToFunc()
}

// ByCampaignField orders the results by campaign field.
func ByCampaignField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCampaignStep(), sql.OrderByField(field, opts...))
	}
}

// ByCampaignVersionField orders the results by campaign_version field.
func ByCampaignVersionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCampaignVersionStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// BySkinField orders the results by skin field.
func BySkinField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSkinStep(), sql.OrderByField(field, opts...))
	}
}

// ByJobField orders the results by job field.
func ByJobField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJobStep(), sql.OrderByField(field, opts...))
	}
}

// ByClaimRecordField orders the results by claim_record field.
func ByClaimRecordField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClaimRecordStep(), sql.OrderByField(field, opts...))
	}
}
func newCampaignStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CampaignInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CampaignTable, CampaignColumn),
	)
}
func newCampaignVersionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CampaignVersionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CampaignVersionTable, CampaignVersionColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newSkinStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SkinInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SkinTable, SkinColumn),
	)
}
func newJobStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JobInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, JobTable, JobColumn),
	)
}
func newClaimRecordStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClaimRecordInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, ClaimRecordTable, ClaimRecordColumn),
	)
}
