// Code generated by ent, DO NOT EDIT.

package rewardcampaign

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the rewardcampaign type in the database.
	Label = "reward_campaign"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSystemKey holds the string denoting the system_key field in the database.
	FieldSystemKey = "system_key"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIssuanceMode holds the string denoting the issuance_mode field in the database.
	FieldIssuanceMode = "issuance_mode"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// FieldStartsAt holds the string denoting the starts_at field in the database.
	FieldStartsAt = "starts_at"
	// FieldEndsAt holds the string denoting the ends_at field in the database.
	FieldEndsAt = "ends_at"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldTotalBudget holds the string denoting the total_budget field in the database.
	FieldTotalBudget = "total_budget"
	// FieldReservedBudget holds the string denoting the reserved_budget field in the database.
	FieldReservedBudget = "reserved_budget"
	// FieldSpentBudget holds the string denoting the spent_budget field in the database.
	FieldSpentBudget = "spent_budget"
	// FieldReleasedBudget holds the string denoting the released_budget field in the database.
	FieldReleasedBudget = "released_budget"
	// FieldCurrentVersionID holds the string denoting the current_version_id field in the database.
	FieldCurrentVersionID = "current_version_id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldPausedAt holds the string denoting the paused_at field in the database.
	FieldPausedAt = "paused_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// FieldArchivedAt holds the string denoting the archived_at field in the database.
	FieldArchivedAt = "archived_at"
	// EdgeVersions holds the string denoting the versions edge name in mutations.
	EdgeVersions = "versions"
	// EdgeCurrentVersion holds the string denoting the current_version edge name in mutations.
	EdgeCurrentVersion = "current_version"
	// EdgeGrants holds the string denoting the grants edge name in mutations.
	EdgeGrants = "grants"
	// EdgeUserStates holds the string denoting the user_states edge name in mutations.
	EdgeUserStates = "user_states"
	// EdgeJobs holds the string denoting the jobs edge name in mutations.
	EdgeJobs = "jobs"
	// Table holds the table name of the rewardcampaign in the database.
	Table = "reward_campaigns"
	// VersionsTable is the table that holds the versions relation/edge.
	VersionsTable = "reward_campaign_versions"
	// VersionsInverseTable is the table name for the RewardCampaignVersion entity.
	// It exists in this package in order to avoid circular dependency with the "rewardcampaignversion" package.
	VersionsInverseTable = "reward_campaign_versions"
	// VersionsColumn is the table column denoting the versions relation/edge.
	VersionsColumn = "campaign_id"
	// CurrentVersionTable is the table that holds the current_version relation/edge.
	CurrentVersionTable = "reward_campaigns"
	// CurrentVersionInverseTable is the table name for the RewardCampaignVersion entity.
	// It exists in this package in order to avoid circular dependency with the "rewardcampaignversion" package.
	CurrentVersionInverseTable = "reward_campaign_versions"
	// CurrentVersionColumn is the table column denoting the current_version relation/edge.
	CurrentVersionColumn = "current_version_id"
	// GrantsTable is the table that holds the grants relation/edge.
	GrantsTable = "user_reward_grants"
	// GrantsInverseTable is the table name for the UserRewardGrant entity.
	// It exists in this package in order to avoid circular dependency with the "userrewardgrant" package.
	GrantsInverseTable = "user_reward_grants"
	// GrantsColumn is the table column denoting the grants relation/edge.
	GrantsColumn = "campaign_id"
	// UserStatesTable is the table that holds the user_states relation/edge.
	UserStatesTable = "reward_campaign_user_states"
	// UserStatesInverseTable is the table name for the RewardCampaignUserState entity.
	// It exists in this package in order to avoid circular dependency with the "rewardcampaignuserstate" package.
	UserStatesInverseTable = "reward_campaign_user_states"
	// UserStatesColumn is the table column denoting the user_states relation/edge.
	UserStatesColumn = "campaign_id"
	// JobsTable is the table that holds the jobs relation/edge.
	JobsTable = "reward_campaign_jobs"
	// JobsInverseTable is the table name for the RewardCampaignJob entity.
	// It exists in this package in order to avoid circular dependency with the "rewardcampaignjob" package.
	JobsInverseTable = "reward_campaign_jobs"
	// JobsColumn is the table column denoting the jobs relation/edge.
	JobsColumn = "campaign_id"
)

// Columns holds all SQL columns for rewardcampaign fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSystemKey,
	FieldName,
	FieldDescription,
	FieldStatus,
	FieldIssuanceMode,
	FieldTimezone,
	FieldStartsAt,
	FieldEndsAt,
	FieldPriority,
	FieldTotalBudget,
	FieldReservedBudget,
	FieldSpentBudget,
	FieldReleasedBudget,
	FieldCurrentVersionID,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldPublishedAt,
	FieldPausedAt,
	FieldEndedAt,
	FieldArchivedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// SystemKeyValidator is a validator for the "system_key" field. It is called by the builders before save.
	SystemKeyValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultIssuanceMode holds the default value on creation for the "issuance_mode" field.
	DefaultIssuanceMode string
	// IssuanceModeValidator is a validator for the "issuance_mode" field. It is called by the builders before save.
	IssuanceModeValidator func(string) error
	// DefaultTimezone holds the default value on creation for the "timezone" field.
	DefaultTimezone string
	// TimezoneValidator is a validator for the "timezone" field. It is called by the builders before save.
	TimezoneValidator func(string) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultTotalBudget holds the default value on creation for the "total_budget" field.
	DefaultTotalBudget float64
	// TotalBudgetValidator is a validator for the "total_budget" field. It is called by the builders before save.
	TotalBudgetValidator func(float64) error
	// DefaultReservedBudget holds the default value on creation for the "reserved_budget" field.
	DefaultReservedBudget float64
	// ReservedBudgetValidator is a validator for the "reserved_budget" field. It is called by the builders before save.
	ReservedBudgetValidator func(float64) error
	// DefaultSpentBudget holds the default value on creation for the "spent_budget" field.
	DefaultSpentBudget float64
	// SpentBudgetValidator is a validator for the "spent_budget" field. It is called by the builders before save.
	SpentBudgetValidator func(float64) error
	// DefaultReleasedBudget holds the default value on creation for the "released_budget" field.
	DefaultReleasedBudget float64
	// ReleasedBudgetValidator is a validator for the "released_budget" field. It is called by the builders before save.
	ReleasedBudgetValidator func(float64) error
)

// OrderOption defines the ordering options for the RewardCampaign queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySystemKey orders the results by the system_key field.
func BySystemKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemKey, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIssuanceMode orders the results by the issuance_mode field.
func ByIssuanceMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuanceMode, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByStartsAt orders the results by the starts_at field.
func ByStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsAt, opts...).ToFunc()
}

// ByEndsAt orders the results by the ends_at field.
func ByEndsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndsAt, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByTotalBudget orders the results by the total_budget field.
func ByTotalBudget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalBudget, opts...).ToFunc()
}

// ByReservedBudget orders the results by the reserved_budget field.
func ByReservedBudget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedBudget, opts...).ToFunc()
}

// BySpentBudget orders the results by the spent_budget field.
func BySpentBudget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpentBudget, opts...).ToFunc()
}

// ByReleasedBudget orders the results by the released_budget field.
func ByReleasedBudget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleasedBudget, opts...).ToFunc()
}

// ByCurrentVersionID orders the results by the current_version_id field.
func ByCurrentVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentVersionID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByPausedAt orders the results by the paused_at field.
func ByPausedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPausedAt, opts...).ToFunc()
}

// ByEndedAt orders the results by the ended_at field.
func ByEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedAt, opts...).ToFunc()
}

// ByArchivedAt orders the results by the archived_at field.
func ByArchivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArchivedAt, opts...).ToFunc()
}

// ByVersionsCount orders the results by versions count.
func ByVersionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVersionsStep(), opts...)
	}
}

// ByVersions orders the results by versions terms.
func ByVersions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVersionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCurrentVersionField orders the results by current_version field.
func ByCurrentVersionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCurrentVersionStep(), sql.OrderByField(field, opts...))
	}
}

// ByGrantsCount orders the results by grants count.
func ByGrantsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGrantsStep(), opts...)
	}
}

// ByGrants orders the results by grants terms.
func ByGrants(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGrantsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserStatesCount orders the results by user_states count.
func ByUserStatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserStatesStep(), opts...)
	}
}

// ByUserStates orders the results by user_states terms.
func ByUserStates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByJobsCount orders the results by jobs count.
func ByJobsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newJobsStep(), opts...)
	}
}

// ByJobs orders the results by jobs terms.
func ByJobs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJobsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newVersionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VersionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VersionsTable, VersionsColumn),
	)
}
func newCurrentVersionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CurrentVersionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CurrentVersionTable, CurrentVersionColumn),
	)
}
func newGrantsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GrantsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GrantsTable, GrantsColumn),
	)
}
func newUserStatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserStatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserStatesTable, UserStatesColumn),
	)
}
func newJobsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JobsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, JobsTable, JobsColumn),
	)
}
